### ISSUE TITLE
product/edit routing

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#102]
You come from the shopping card and click edit to go to product/edit. You change and get the pop up "2 Items in shopping cart." with link to card and products.

leave the popup and enter directly the shopping card where you came from.

**Comment by inbaz** [comment]
fixed in 0.2.13

**Comment by smadamit** [comment]
no does not work!

**Comment by inbaz** [comment]
I changed the overlay behaviour, therefore you can choose now where you want to go. And please still have a look at the version number at the bottom right before testing. For each test run you should clear your shopping cart.

**Comment by smadamit** [comment]
I think you didn't get the point:
- shopping card
- click edit of a procduct
- edit form of the product
- click edit card
- **you get a pop up: go to products or go to card** -> please discard the popup if you came from the shopping card and direct the user to the shopping card after editing the product.

Or are you of another opinion? Why?

0.2.15

**Comment by inbaz** [comment]
Please, make a topic for the agenda of this point.

**Comment by smadamit** [comment]
You still get the popup: "Added week ticket adult to your shopping cart."

In a bug I got the popup: "Changed week ticket adult in your shopping cart." or something like this. Maybe this is what you want?

But in the end I don't like it. Just leave the popup. We will discuss via Skype.

**Comment by smadamit** [comment]
I make new issues. This is overloaded with infos which are not recent anymore
