### ISSUE TITLE
participant/index participants -> persons

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#103]
you renamed the menu and some of the buttons. can you rename:
- title of the page: My Participants
- link: Add participant
- would be perfect if you can rename the controller? If it is not too much effort.

same for product/add:
- rename message: "Please choose a participant. This is a personalized ticket. You have to choose a participant for whom this ticket will be valid."
- rename title to select field: Participant

**Comment by inbaz** [comment]
I hope I didn't miss any part, please recheck.

Changing the buttons and descriptions is one thing but changing the controller will go very deep into the code and I need to edit many files. Is it really that important to have person instead of participant in the url?

**Comment by smadamit** [comment]
no don't change the controller.

changes are OK.

one last change:
- participant/add: rename title

**Comment by inbaz** [comment]
Changed an even changed the edit and delete dialogue.

**Comment by inbaz** [comment]
Less is more, I removed the add Person button and just added a link to add a participant to the list above, but have a look yourself. Check if this is better. We could change the label above the select element to say something like "you need to choose a person" when the ticket is personalized and "you can choose a person" if it's not.

**Comment by smadamit** [comment]
looks good.

yes please rename the label as you said.

**Comment by inbaz** [comment]
I'd like to have another run with external testers on that. I think I'll write a second email to the whole team when some other things are fixed aswell.
