### ISSUE TITLE
Check if encoding is correct everywhere

### ISSUE THREAD

**Issue by inbaz** [inbaz/ers#106]
I hope I fixed the encoding in the emails, this was the main problem. You can check it by having a look if the euro sign in displayed correctly in both, html an text mode. Please also check if everything is working correct with german umlauts in firstname and surname or in any descriptions.

**Comment by smadamit** [comment]
First test works fine. UTF-8 readable. I keep an eye on this issue...

**Comment by smadamit** [comment]
Version: 0.2.24:

it works:
- FUPN6419	09.03.2015 16:07:41	İbrahim Abdülkadir Meriçboyu	120,00 €

**Comment by smadamit** [comment]
I want to have the issue open since the etickets are implemented. Then I will check the encoding there. I am pretty sure you will implement it right in UTF-8 :-)

**Comment by inbaz** [comment]
This will not change, because the EmailService with which the order confirmation mails were sent and with which the eticket mails and all other mails will be sent will be the same. If somebody has an encoding problem it will be a major one and will affect all mails.

**Comment by smadamit** [comment]
OK :-)
