### ISSUE TITLE
setup preprod environment

### ISSUE THREAD

**Issue by inbaz** [inbaz/ers#107]
Could you please setup a preprod environment and a prod environment to have two system which are nearly the same? preprod should have access to a htpasswd saved phpmyadmin, please not on /phpmyadmin, but another name. Both environments should only be accessible via ssl. A self signed certificate will be ok for now. For the GoLive we'll replace the ssl certificates with a correctly signed one.

Please setup two databases with two users aswell.

**Comment by staffanu** [comment]
I'm just repeating the requirement, worded a bit differently, to make sure I understand what you want:

You want to set up a system that is as close to the production system as possible, but with phpmyadmin added? I would do that on a different server, and I would assume it does not matter that this is a virtual server hosted somewhere else?  Once set up I'll give you ssh access to that server as well.

**Comment by inbaz** [comment]
A preprod system should be exactly the same as the prod system, but without users on it. In our case it's important which ip address the system has, according the SPF record, therefor I'd like to have a second VirtualHost on the productive server fot the preprod system.

Before GoLive preprod will be the system where we setup the whole shop with all products and settings. For GoLive we'll copy this system to production. After a day or two I'd like to do a snapshot from the production system back to preprod to make sure this step is working correctly.

When we're live preprod will provide an instance where all live data is available so it's possible to test the whole system as it would be the productive system but with no risk to brake productive data, because we can simply snapshot the productive system to preprod.

Especially for the whole mailing stuff it would be great to have a system with productive data on the productive server but not accessible to the whole world.

If we have such a system which is already secured by a htpasswd we do not need to open phpmyadmin to the whole world, too. But to have a phpmyadmin for the productive data could be very useful in some cases.

What do you think? Any concerns?

**Comment by staffanu** [comment]
Sounds fine, and also not much work to set up. (I thought you wanted a complete separate linux installation, which would have taken a few hours, but this should be quick.)

**Comment by staffanu** [comment]
This is now mostly done.  There are two host names pointing to the same server: prereg.eja.net and preregpp.eja.net.  The databases are called "ers" and "erspp" respectively.  Users and directories etc all have a "pp" suffic for the preproduction version.

prereg.eja.net has a real ssl ceritifacte. preregpp.eja.net has a self signed certificate.

They are both protocted by the same http passwords.

I have not installed phpmyadmin yet (will maybe today or otherwise later this week).

I set up the latest version from git for the pp site. The readme was still missing some information, which I added. Do you want me to commit that kind of changes or do you prefer to do commits yourselves? (I think I was granted access to commit, but could be mistaken?)

Staffan

**Comment by inbaz** [comment]
It would be nice if you could do push requests for README changes. I think that's the easiest way for both sides.

**Comment by smadamit** [comment]
@staffanu has you implemented phpmyadmin?

**Comment by staffanu** [comment]
Hi,

I wrote this in a mail about a week ago:

phpmyadmin is now installed in prergpp/dbaccess. I had the impression you
only wanted it installed on the preregpp virtual host (which will always be
password protected)?  I set it up to reach both databases. I never used
phpmyadmin myself and haven't really tested it (I do understand what it's
supposed to do so something works). Tell me it needs more configuration.

Please tell me if there is anything else needed.

Staffan

**Comment by smadamit** [comment]
@inbaz Do you need anything else from Staffan? If not, please close the ticket.
