### ISSUE TITLE
Check total price of orders

### ISSUE THREAD

**Issue by inbaz** [inbaz/ers#110]
Please do a test round only having a look at all prices on all pages, especially the calculated ones:

- order/index
- order/checkout
- confirmation mail

Are the prices calculated correctly? VAT? Payment Type costs?

Can you do that at least two times? One week before go live and one or two days before go live? Maybe it's a good idea to check the admin panel aswell.

**Comment by smadamit** [comment]
I have already tested some cases. But I will test it systematical once again.

**Comment by smadamit** [comment]
test: 0.2.26 -> OK

I will retest

**Comment by smadamit** [comment]
test 0.2.45:
- credit card fees -> correct. The fees are rounded down. So 90,525 € -> 90,52 €. That fine for me.
- In the order details and in the email there is no VAT calculated. Should it be displayed? At least in the invoices we will need the VAT displayed.

I will retest the VAT later.

**Comment by smadamit** [comment]
We will have no invoices, so there is no VAT to display. Or should we display the VAT in the order details, emails, ...?

**Comment by christianbross** [comment]
I think we don't create the invoices, but for the user/juggler there is a VAT. I would not change anything here and keep the VAT text&displays "as-is". The only thing that changes is the term "invoice" --> "ticket confirmation" (or similar term). The rest stays the same from my point of view.

**Comment by smadamit** [comment]
@christianbross  the question was if we should calculate and display the VAT (Euro amount) in the order email etc. At the moment that is not the case. And I think we don't need it.

**Comment by christianbross** [comment]
ok. I agree to not "add now". And other things (e.g. web interface) stay "as-is".
fine. :-)
