### ISSUE TITLE
English language #01

### ISSUE THREAD

**Issue by christianbross** [inbaz/ers#112]
In page week ticket adult (http://test.ers.inbaz.org/product/add/2)
text 1 "you need to assign this thicket to a person" --> change "thicket" to "ticket"
text 2 "This is a personalized ticket. You have to choose a person for whom this ticket will be valid." --> modify to "This is a personalized ticket. You have to enter the person who will use the ticket for the event."

**Comment by inbaz** [comment]
fixed in 0.2.23

**Comment by christianbross** [comment]
retest ok
