### ISSUE TITLE
Shopping Cart - Edit Product doesn't work

### ISSUE THREAD

**Issue by christianbross** [inbaz/ers#113]
In the shopping cart the "edit" button for each product doesn't work. I get a "404" error. (Version 0.2.22)

Sample link for "edit" button = http://test.ers.inbaz.org/product/edit/3/2/1/null

**Comment by inbaz** [comment]
If you cut off /null at the end it works. This was a try to get the variants back to the product view to preselect what the user has chose before. In the next version (0.2.23) this will be removed until I find a valuable solution for this problem.

**Comment by christianbross** [comment]
ok. Does this mean the issue is now closed? At least until you "break" it again? ;-)

**Comment by inbaz** [comment]
No, it's not closed because it's not possible to edit products from shopping cart with having the preselected values set automatically. For this task I need this ticket as a reminder.

**Comment by smadamit** [comment]
We can close it, because it is a duplicate to #28

**Comment by inbaz** [comment]
Please retest in 0.2.24. This was a hard one, I need to change many things to get this solved.

**Comment by smadamit** [comment]
No don't work!

**Comment by smadamit** [comment]
see also: #150

**Comment by inbaz** [comment]
Next round: I fixed some things. What I already tried:
1. Test
- add t-shirt (unassigned)
- edit from shopping cart
- add person and assign product to this person
2. Test
- add t-shirt (unassigned)
- add two persons via My Persons
- assign t-shirt to the first person
- edit from shopping cart
- directly assign the product to the second person

Maybe you find something which is still broken, hoppenfully not.

**Comment by inbaz** [comment]
Can you please retest? I think it's working.

**Comment by smadamit** [comment]
tested in 0.2.36 -> OK
