### ISSUE TITLE
Edit item in cart doesn't work if I add a new person

### ISSUE THREAD

**Issue by christianbross** [inbaz/ers#114]
I'm using these steps in Version 0.2.23
Add personalized item to cart (week ticket)
Open shopping cart
click "edit" on item
add new person to list
click "edit cart" --> doesn't work, URL is http://test.ers.inbaz.org/cart/add/4/1

Comment: it works, if I don't add a new person, but instead use an existing one

**Comment by inbaz** [comment]
Please retest in 0.2.25. There could be some bugs according to the product variants and product variant values are configured. We need the official products to correctly retest this issue. Please check if everything what is already configured works.

**Comment by smadamit** [comment]
tested: Version: 0.2.26 -> OK
