### ISSUE TITLE
product/edit: Usability in "edit cart"

### ISSUE THREAD

**Issue by christianbross** [inbaz/ers#116]
(Version 0.2.23)
three usability imporvements:
1) change text on button from "edit cart" to "save changes"
2) add button/link for "cancel" that brings you back to shopping cart *without* saving changes
3) "optional": disable button "save changes" until user did change something, then enable it

**Comment by inbaz** [comment]
Points 1 and 2 fixed in 0.2.24. Point 3 is nice to have.
