### ISSUE TITLE
Bug in checkout, when I edit product

### ISSUE THREAD

**Issue by christianbross** [inbaz/ers#118]
Version 0.2.23
If I'm in checkout and then click on the "edit" link for a product, I run into a 404 error.
The URL is "http://test.ers.inbaz.org/product/view/6/3/2"

**Comment by christianbross** [comment]
If I'm not in "checkout" mode, the link will be "http://test.ers.inbaz.org/product/edit/6/3/2"  and that works

**Comment by inbaz** [comment]
fixed in 0.2.24, please retest

**Comment by smadamit** [comment]
tested in 0.2.24 -> works
