### ISSUE TITLE
Puchaser choice is lost after re-entry to checkout

### ISSUE THREAD

**Issue by christianbross** [inbaz/ers#119]
Version 0.2.23
I try "checkout" and select e.g. person #2 as purchaser
Then I go e.g. to "edit" person
later on, I do "checkout" again, but this time person #4 is pre-selected as purchaser, i.e. my previous choice on person #2 = purchaser has been lost

**Comment by inbaz** [comment]
Hmm, strange. I can reproduce this in test, but not in dev. I put in more debugging output to retest this issue in test with version 0.2.24.

**Comment by inbaz** [comment]
Does this issue still exist? Can please somebody retest?

**Comment by smadamit** [comment]
tested in 0.2.36 -> OK
