### ISSUE TITLE
Feedback buying a product is missing

### ISSUE THREAD

**Issue by jackcaveman** [inbaz/ers#12]
When you add a product to your Cart you go back to the "products" page. Which is a quite logical page to go to. However, no (visual) feedback is given that the product was added successfully. This is a bit confusing.
Suggestions: 
* either forward the visitor to the Cart for an overview. 
* or have some "popup" text saying the product was added to the cart

**Comment by inbaz** [comment]
added an overlay after a product was added tot he shopping cart to choose if you want to go back to products or to your shopping cart.

**Comment by jackcaveman** [comment]
The overlay makes it more clear.
Can you change the text to "Added Weekticket Adult to your cart".
If that is too much work, then please remove the total number of items in your cart. It does not reflect your current action (adding 1 item) to the total number of items (4 items)...

**Comment by inbaz** [comment]
I changed the behaviour of the overlay. Please recheck in 0.2.13

**Comment by smadamit** [comment]
I think now it's OK
