### ISSUE TITLE
Usability in "checkout" - change button "Register" into "Purchaser"

### ISSUE THREAD

**Issue by christianbross** [inbaz/ers#120]
Version 0.2.23
After I have selected a purchaser once, and then I change my order, if I re-enter the "checkout" process the button "register" is very unclear. I wouldn't have guessed, that this button allows me to change again the choice for "purchaser". I recomment to change the button text from "Register" to "Select Purchaser".

2) optional improvement -> also change button "Payment" to "Select Payment"

**Comment by inbaz** [comment]
I changed register to purchaser and changed payment to payment type. Is that ok? If I put select in front of payment or payment type I should do that for Purchaser, too. This will be to much text for the buttons.

**Comment by smadamit** [comment]
For me it's fine, like it is in v 0.2.24

@christianbross If you agree, close it.
