### ISSUE TITLE
edit product crucial bug

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#124]
v 0.2.24
- I put in a week ticket for tim
- I put in a t shirt not assigned
- I created isabelle
- I edit the unassigned t-shirt
- I assigned the t-shirt to Isabelle
- in my card are now: 2 t-shirts: one for Isabelle and one unassigned. My week ticket is gone.
- now I edit the assigned t-shirt and change to unassigned -> blank page. But action was succesfull: 2 unassigned t-shirts in card. no week ticket.

**Comment by smadamit** [comment]
even more buggy. After the steps before I clicked on edit of one of the unassigned tshirts and got:
- edit form of the t-shirt with popup: "Changed t-shirt in your shopping cart."

**Comment by inbaz** [comment]
There were many changes, please retest.

**Comment by smadamit** [comment]
tested and fixed with #145
