### ISSUE TITLE
popups bug

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#126]
@inbaz please review your popup routines. I had several cases where I got a popup where there was no action. e.g. I clicked on tshirt in the product list and got a popup "added to card", but was not the case... There were even more cases...

**Comment by inbaz** [comment]
I need the click route to be able to reproduce this error. Since the popups are triggert through a session variable I need to know to which page you've left the product page and how you got back to it.

**Comment by smadamit** [comment]
Can not reproduce it at the moment.

It was in the session you can follow in #124 There you can see the steps, but I'm not 100% sure. Was a very confusing test.

**Comment by smadamit** [comment]
New case in 0.2.26. After this bug: #145 
- go back to card
- click on edit week ticket
- got popup before entering the edit form of the week ticket

**Comment by smadamit** [comment]
@inbaz I think this issue is solved with #124 and #145 Do you agree? Please close it if you agree.
