### ISSUE TITLE
admin/product-variant-value/add bug

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#129]
coming from admin/product-variant-value and click "Add"

error:
- message: "Route with name "product-variant-value" not found"

**Comment by smadamit** [comment]
But action was done!

**Comment by smadamit** [comment]
same for admin/product-variant-value/edit

**Comment by smadamit** [comment]
preprod v0.2.16

**Comment by inbaz** [comment]
From where did you get to admin/product-variant-value? I think these functions are only available through the product detail page. Add and edit functions are working in 0.2.24. If you need an update of preprod just push an issue.

**Comment by smadamit** [comment]
tested in 0.2.27: OK
