### ISSUE TITLE
sorting of the countries

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#134]
- Italy
- Europe by size
- important of the world: USA...
- rest of the world

**Comment by inbaz** [comment]
Do we have statistics of the last EJCs? I'd like to show the Country in which the EJC will take place first and then the top 10 Countries of participants. After that the rest of the world alphabetically.

**Comment by smadamit** [comment]
**participants EJC 2011**
	
country | participants
-----------|----------------
German | 3490
French | 594
Italian | 369
Austrian | 270
British | 249
Swiss | 179
Dutch | 176
Belgian | 129
Spanish | 89
Czech | 62
Us-american | 62
Irish | 57
Polish | 52
Swedish | 37
Japanese | 36
Slovenian | 33
Finnish | 30
Israeli | 30
Brazilian | 26
Luxembourger | 26
Costa rican | 25
Danish | 25
Canadian | 23
Hungarian | 23
Mexican | 21
Norwegian | 19
Lithuanian | 16
Turkish | 15
Australian | 14
Russian | 13
Slovakian | 13
Monacan | 11
Greek | 10
Argentinean | 9
Taiwanese | 9
Ukrainian | 8
Chilean | 7
Colombian | 6
Estonian | 6
New zealander | 6
Portuguese | 6
Scottish | 5
Belarusian | 4
Indonesian | 4
Singaporean | 4
Northern irish | 3
Peruvian | 3
Romanian | 3
Serbian | 3
Bulgarian | 2
Iranian | 2
Venezuelan | 2
Chinese | 1
Croatian | 1
Ghanaian | 1
Icelander | 1
Salvadoran | 1
South korean | 1
Thai | 1
Uruguayan | 1
Vietnamese | 1
Welsh | 1

**Comment by inbaz** [comment]
Uh, only 89 from Spain? I thought this were more.

**Comment by smadamit** [comment]
-> Financial crisis of 2007

**Comment by smadamit** [comment]
top 5
