### ISSUE TITLE
warning on existing user account

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#135]
I ordered as İbrahim Abdülkadir Meriçboyu

But in the confirmation mail and in admin/order I get: Adams test:

U7RUWM71	09.03.2015 14:55:53	Adams test 	120,00 €	unpaid

**Comment by inbaz** [comment]
That's all correct. Nobody can change the name of the account with your email address.

**Comment by smadamit** [comment]
You are right. Do we need a warning that the email address has already an account. Maybe the juggler has to log in first to do a new order.

**Comment by inbaz** [comment]
Possibly, I don't like it to have a system where somebody can test which email address is in the system. Therefore I'm against this warning, but on the other hand a message for the user would be nice.

**Comment by smadamit** [comment]
There is no workaround for your concern. And it's the same for all systems with email based accounts. We talk in Skype...

**Comment by smadamit** [comment]
in the moment the users can log in to their accounts we need the feature: warning that the email is already in use.

**Comment by inbaz** [comment]
I set up this warning when choosing the purchaser. A purchaser needs to login to this account if it already exists.

**Comment by smadamit** [comment]
Yes I have seen. It works. But that is a problem for testing. I have to change the email for any new order. An idea for a workaround for testing?

**Comment by inbaz** [comment]
activated again in 0.3.0

**Comment by smadamit** [comment]
tested in 0.3.1 -> OK
