### ISSUE TITLE
Template not found on "Update participant data" in Profile

### ISSUE THREAD

**Issue by philip-n** [inbaz/ers#136]
New account, no orders created or anything, just clicking through the menus. Should probably create a (nice) error message instead, saying "No participant created yet" or similar?

http://ers.inbaz.org/profile > "Update participant data" resulted in the following error @ http://ers.inbaz.org/profile/participant :

An error occurred
An error occurred during execution; please try again later.
Additional information:
Zend\View\Exception\RuntimeException

File:

    /home/ers/www/ers.sixhop.net/vendor/zendframework/zendframework/library/Zend/View/Renderer/PhpRenderer.php:498

Message:

    Zend\View\Renderer\PhpRenderer::render: Unable to render template "pre-reg/profile/participant"; resolver could not resolve to a file

Stack trace:

    #0 /home/ers/www/ers.sixhop.net/vendor/zendframework/zendframework/library/Zend/View/View.php(205): Zend\View\Renderer\PhpRenderer->render(Object(Zend\View\Model\ViewModel))
    #1 /home/ers/www/ers.sixhop.net/vendor/zendframework/zendframework/library/Zend/View/View.php(233): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
    #2 /home/ers/www/ers.sixhop.net/vendor/zendframework/zendframework/library/Zend/View/View.php(198): Zend\View\View->renderChildren(Object(Zend\View\Model\ViewModel))
    #3 /home/ers/www/ers.sixhop.net/vendor/zendframework/zendframework/library/Zend/Mvc/View/Http/DefaultRenderingStrategy.php(103): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
    #4 [internal function]: Zend\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Zend\Mvc\MvcEvent))
    #5 /home/ers/www/ers.sixhop.net/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
    #6 /home/ers/www/ers.sixhop.net/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('render', Object(Zend\Mvc\MvcEvent), Array)
    #7 /home/ers/www/ers.sixhop.net/vendor/zendframework/zendframework/library/Zend/Mvc/Application.php(352): Zend\EventManager\EventManager->trigger('render', Object(Zend\Mvc\MvcEvent))
    #8 /home/ers/www/ers.sixhop.net/vendor/zendframework/zendframework/library/Zend/Mvc/Application.php(327): Zend\Mvc\Application->completeRequest(Object(Zend\Mvc\MvcEvent))
    #9 /home/ers/www/ers.sixhop.net/public/index.php(18): Zend\Mvc\Application->run()
    #10 {main}

**Comment by smadamit** [comment]
profile is not yet implemented #57
