### ISSUE TITLE
Template not found on "View tickets" in new Profile 

### ISSUE THREAD

**Issue by philip-n** [inbaz/ers#137]
Probably same problem  as #136:

New account, no orders created or anything, just clicking through the menus. Should probably create a (nice) error message instead, saying "No ticket ordered yet" or similar?

http://ers.inbaz.org/profile > "View tickets" resulted in the following error @ http://ers.inbaz.org/package :

An error occurred
An error occurred during execution; please try again later.
Additional information:
Zend\ServiceManager\Exception\ServiceNotFoundException

File:

    /home/ers/www/ers.sixhop.net/vendor/zendframework/zendframework/library/Zend/ServiceManager/AbstractPluginManager.php:168

Message:

    Zend\Mvc\Controller\ControllerManager::createFromInvokable: failed retrieving "preregcontrollerpackage(alias: PreReg\Controller\Package)" via invokable class "PreReg\Controller\PackageController"; class does not exist

Stack trace:

    #0 /home/ers/www/ers.sixhop.net/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php(637): Zend\ServiceManager\AbstractPluginManager->createFromInvokable('preregcontrolle...', 'PreReg\\Controll...')
    #1 /home/ers/www/ers.sixhop.net/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php(593): Zend\ServiceManager\ServiceManager->doCreate('PreReg\\Controll...', 'preregcontrolle...')
    #2 /home/ers/www/ers.sixhop.net/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php(525): Zend\ServiceManager\ServiceManager->create(Array)
    #3 /home/ers/www/ers.sixhop.net/vendor/zendframework/zendframework/library/Zend/ServiceManager/AbstractPluginManager.php(103): Zend\ServiceManager\ServiceManager->get('PreReg\\Controll...', false)
    #4 /home/ers/www/ers.sixhop.net/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/ControllerManager.php(137): Zend\ServiceManager\AbstractPluginManager->get('PreReg\\Controll...', Array, false)
    #5 /home/ers/www/ers.sixhop.net/vendor/zendframework/zendframework/library/Zend/Mvc/DispatchListener.php(96): Zend\Mvc\Controller\ControllerManager->get('PreReg\\Controll...')
    #6 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
    #7 /home/ers/www/ers.sixhop.net/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
    #8 /home/ers/www/ers.sixhop.net/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
    #9 /home/ers/www/ers.sixhop.net/vendor/zendframework/zendframework/library/Zend/Mvc/Application.php(313): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
    #10 /home/ers/www/ers.sixhop.net/public/index.php(18): Zend\Mvc\Application->run()
    #11 {main}

**Comment by philip-n** [comment]
Same behaviour if a ticket was already ordered.

An error occurred

An error occurred during execution; please try again later.


Additional information:

Zend\ServiceManager\Exception\ServiceNotFoundException
File:/home/test/www/test.ers.inbaz.org/vendor/zendframework/zendframework/library/Zend/ServiceManager/AbstractPluginManager.php:168
Message:Zend\Mvc\Controller\ControllerManager::createFromInvokable: failed retrieving "preregcontrollerpackage(alias: PreReg\Controller\Package)" via invokable class "PreReg\Controller\PackageController"; class does not exist
Stack trace:#0 /home/test/www/test.ers.inbaz.org/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php(637): Zend\ServiceManager\AbstractPluginManager->createFromInvokable('preregcontrolle...', 'PreReg\\CCnnroll...')
#1 /home/test/www/test.ers.inbaz.org/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php(593): Zend\ServiceManager\ServiceManager->doCreate('PreReg\\CCnnroll...', 'preregcontrolle...')
#2 /home/test/www/test.ers.inbaz.org/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php(525): Zend\ServiceManager\ServiceManager->create(Array)
#3 /home/test/www/test.ers.inbaz.org/vendor/zendframework/zendframework/library/Zend/ServiceManager/AbstractPluginManager.php(103): Zend\ServiceManager\ServiceManager->get('PreReg\\CCnnroll...', false)
#4 /home/test/www/test.ers.inbaz.org/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/ControllerManager.php(137): Zend\ServiceManager\AbstractPluginManager->get('PreReg\\CCnnroll...', Array, false)
#5 /home/test/www/test.ers.inbaz.org/vendor/zendframework/zendframework/library/Zend/Mvc/DispatchListener.php(96): Zend\Mvc\Controller\ControllerManager->get('PreReg\\CCnnroll...')
#6 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#7 /home/test/www/test.ers.inbaz.org/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#8 /home/test/www/test.ers.inbaz.org/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#9 /home/test/www/test.ers.inbaz.org/vendor/zendframework/zendframework/library/Zend/Mvc/Application.php(313): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#10 /home/test/www/test.ers.inbaz.org/public/index.php(18): Zend\Mvc\Application->run()
#11 {main}

**Comment by smadamit** [comment]
profile is not yet implemented #57
