### ISSUE TITLE
Participants age is not checked against reasonable limits

### ISSUE THREAD

**Issue by philip-n** [inbaz/ers#139]
It's possible to create a person with a birthdate in e.g. 2016, 1700 etc.
Tested on product -> "Add participant" and "My Persons" > Person ... "edit"

Missing or desired behaviour?

**Comment by philip-n** [comment]
Fix together with #144?

**Comment by inbaz** [comment]
A participant can give 01.01.1900 as minimal birthdate and today as maximal birthdate - hmm, it's the other way round: 01.01.1900 as maximal birthdate and today as minimal birthdate. Depends on the point of view, but it's working. :D

**Comment by philip-n** [comment]
Just tested on test.ers.inbaz.org: 01.01.1700 and 01.01.2020 were both accepted as birth dates. Tried in product selection screen (add person) and under my persons > edit person.

**Comment by inbaz** [comment]
Oh, sorry, I think I forgot to add the version in which this is added, it's 0.2.33, test and preprod still run on 0.2.32.

**Comment by philip-n** [comment]
Tested on 0.2.34, works as intended.
