### ISSUE TITLE
Exception not caught on payment/index

### ISSUE THREAD

**Issue by jackcaveman** [inbaz/ers#14]
I finished the checkout process, clicked "buy now" and ended up at http://test.ers.inbaz.org/payment/banktransfer. This worked fine.
For some random reason I pointed by browser to: http://test.ers.inbaz.org/payment
Then I got some exception. Perhaps more pages are not caught properly (i.e. error 404).

Zend\View\Exception\RuntimeException
Zend\View\Renderer\PhpRenderer::render: Unable to render template "pre-reg/payment/index"; resolver could not resolve to a file

**Comment by inbaz** [comment]
Give me a hint. What should be displayed on this page or where should I redirect the user? What did you do to get to this page? I think it's not linked anywhere in the system.

**Comment by jackcaveman** [comment]
That's correct, it's no linked anywhere. I just made that up. It think
should return "error 404 - page not found".

**Comment by inbaz** [comment]
done
