### ISSUE TITLE
Error message on invalid credit card

### ISSUE THREAD

**Issue by philip-n** [inbaz/ers#140]
Trying to pay by credit card with random numbers results in following error message. Could we have a nicer one here? :-)

$_GET
array ( 'trxuser_id' => '99999', 'trx_amount' => '38198', 'trx_currency' => 'EUR', 'trx_paymenttyp' => 'cc', 'shopper_id' => 'MR6C7N13', 'addr_name' => 'ich', 'csrf' => 'e810c53a870442f75a27d662e871ce8b-9a459a34b83123ccd9ff87b6334a7bb3', 'submit' => 'pay now', 'trx_typ' => 'auth', 'ret_errorcode' => '5002', 'ret_fatalerror' => '0', 'ret_errormsg' => 'Die angegebene Kreditkartennummer ist fehlerhaft.', 'ret_additionalmsg' => 'The Creditcard-Number is invalid (0)', 'ret_ip' => '88.117.142.114', 'redirect_needed' => '0', 'ret_status' => 'ERROR', )
$_POST
array ( )

**Comment by inbaz** [comment]
I fixed the error message, please recheck.

**Comment by smadamit** [comment]
checked in 0.2.45 -> OK
