### ISSUE TITLE
product/edit week ticket change person bug

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#145]
test: 0.2.26:

- put in week ticket for isabelle
- go to card
- edit week ticket and create new person tim and assign the ticket to tim
- go to card
- edit week ticket and assign the ticket to isabelle
- got a blank page

**Comment by smadamit** [comment]
maybe similar to #113 #124

**Comment by inbaz** [comment]
Please retest.

**Comment by smadamit** [comment]
test 0.2.27 -> OK

- new session logged out
- product
- week ticket adult
- add person to this list
- tim -> add
- add to card
- popup -> shopping card
- product
- t-shirt: green, L, do not assign
- add to card
- popup -> shopping card
- t-shirt -> edit
- (bug edit t-shirt -> default select values wrong)
- t-shirt: red, S, tim
- popup -> shopping card
- tim -> edit
- change birthdate -> save
- t-shirt edit
- add person to this list
- leonie -> save
- t-shirt: red, S, leonie -> save changes
- popup -> shopping card
- t-shirt -> edit
- not assign -> save
- popup -> product
- day ticket child
- add person
- isabelle -> save
- 2 August, isabelle -> add to card
- popup -> shopping card
- shirt -> edit
- isabelle -> save
- popup -> shopping card
- checkout this card
- tim -> save purchaser
- bank -> save payment
- buy now

-> OK

**Comment by smadamit** [comment]
retest the same 0.2.27 -> OK

- logged out
- product
- week ticket adult
- add person to this list
- tim -> add
- add to card
- popup -> shopping card
- product
- t-shirt: green, L, do not assign
- add to card
- popup -> shopping card
- t-shirt -> edit
- (bug edit t-shirt -> default select values wrong)
- t-shirt: red, S, tim
- popup -> shopping card
- tim -> edit
- change birthdate -> save
- t-shirt edit
- add person to this list
- leonie -> save
- t-shirt: red, S, leonie -> save changes
- popup -> shopping card
- t-shirt -> edit
- not assign -> save
- popup -> product
- day ticket child
- add person
- isabelle -> save
- 2 August, isabelle -> add to card
- popup -> shopping card
- shirt -> edit
- isabelle -> save
- popup -> shopping card
- checkout this card
- tim -> save purchaser
- bank -> save payment
- buy now
