### ISSUE TITLE
Parse name string against invalid characters

### ISSUE THREAD

**Issue by philip-n** [inbaz/ers#147]
Currently, the name allows for characters such as (";{[ to be entered. Also, there seems to be no character limit.

Both seem not to be a problem around the site (?), but might pose problems when interfacing with external systems (e.g. CSV export).

Proposal: a) Impose a character limit and b) filter potentially "malicious" characters.

**Comment by inbaz** [comment]
Could you provide a list of chars that won't appear in names?

**Comment by inbaz** [comment]
I added a list of !"§$%()=<>|^;{}[] to be not allowed. Test in 0.2.31

**Comment by philip-n** [comment]
List sounds good. Maybe add

# + * 1 2 3 4 5 6 7 8 9 0 , ?

**Comment by inbaz** [comment]
What needs to be fixed with that is that nobody can inject code over these fields, correct? I don't know if anybody of our crazy people do have numbers or anything else in their name, therefore I'd like to let this open. I thin with the above list we're secure.
