### ISSUE TITLE
hilight checkout steps

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#148]
I got a feedback from a tester to the checkout.

enhancements:
- order/index -> it's from code view not the same as order/overview, but it is from user view. So why not highlight "Shopping Card" for both cases
- what about highlighting the checkout steps depending on the status: bold for active step, backgroundcolor:green for finished steps and white for unfinished steps.

similar to #62 Maybe this issue can solve #62 too.

**Comment by inbaz** [comment]
Because if I hilight on order/index the first element of the checkout menu "Shopping Cart" will be hilighted through all steps because order/purchaser, order/payment and order/checkout are subpages of order/index. So this is the workaround for that.

**Comment by inbaz** [comment]
Please close if this is working for you aswell.

**Comment by smadamit** [comment]
Let's keep it open. But for after EJC2015.

For me this would be a nice enhancement:
- what about highlighting the checkout steps depending on the status: bold for active step, backgroundcolor:green for finished steps and white for unfinished steps.

**Comment by inbaz** [comment]
fixed with #221.
