### ISSUE TITLE
Participants name not appearing in confirmation mail

### ISSUE THREAD

**Issue by philip-n** [inbaz/ers#149]
See also #143 for full mail text.

The participants name is not shown at the top: "Dear ,". Also, in the last paragraph (see below), the ticket is listed under "unassigned items". I guess this should rather be the participant name as well?

---

You purchased the following items:

unassigned items

Product Amount  Price  
week ticket adult   1   120,00 €  
Subtotal:   120,00 €  
Order amount:   120,00 €
Payment Charge: 0,00 €
Total amount:   120,00 €

**Comment by inbaz** [comment]
What did you do to get this mail?

**Comment by philip-n** [comment]
Same behaviour in three different occasions. Last time: 
1. Put sth in shopping cart
2. Click "check out" and get notified that informaiton is missing
3. Select purchaser
4. Select "bank transfer"
5. Confirm agb and check out

---


```
Dear ,

This is the confirmation for your order from 10.03.2015 with the order ID 6A2CYM02.

Thank you for registering for the 38th European Juggling Convention! Your registration helps us to improve the EJC 2015 for you and for all fellow jugglers.

You chose Bank Bruneck as payment method.

Please transfer the entire amount of your order within 14 days. To gain from the pre-booking conditions, please make sure that the payment is processed on time (31st of May / 15th of June), even if there are less than 14 days left.

In case you chose 'bank transfer' as payment method please transfer the entire amount of your order to the following account:

Please transfer the amount by SEPA bank transfer to the following account:

To make the orgas life easy, please add the reason for payment: 6A2CYM02
Owner 	STICHTING EUROPEAN JUGGLING ASSOCIATION
IBAN 	NL84 INGB 0007 8721 92
BIC 	INGBNL2A
Amount 	158,00 €
reason for payment 	6A2CYM02

Please state your order ID 6A2CYM02 as reference at your transfer form.

In case you chose credit card as payment method and your payment was not successful, you can restart your credit card payment via the following link:
%resume_link%

Please consider our general terms and conditions, which are attached to this email. To be able to read the document, you need to install Adobe Acrobat Reader, which you can download here: http://get.adobe.com/de/reader

Your eTickets and further information concerning the 38th European Juggling Convention will be delivered in another email after your payment has been confirmed.

We are looking forward to welcoming you in Bruneck!

Best regards,
Your European Juggling Association and the local EJC 2015 organizers

You purchased the following items:
unassigned items
Product 	Amount 	Price 	
t-shirt ( color: red; size: S ) 	1 	15,00 € 	
	Subtotal: 	15,00 € 	
unassigned items
Product 	Amount 	Price 	
week ticket adult 	1 	120,00 € 	
	Subtotal: 	120,00 € 	
unassigned items
Product 	Amount 	Price 	
week ticket including gala show (adult) 	1 	23,00 € 	
	Subtotal: 	23,00 € 	
Order amount: 	158,00 €
Payment Charge: 	0,00 €
Total amount: 	158,00 €
```

**Comment by inbaz** [comment]
One thin is the missing saluation. That is easy explained: The registration process at the moment does not take first- and surname so your name is not in the database. If you give the name with your email address while purchasing an item I will not save the name, because that opens the possibility to everyone who knows your email address to change your name. Maybe a warning "Please login first" would be a solution on that.

The second thing which is confusing is that all your items are unassigned, even if it is a week ticket. What exactly did you choose to get these tickets unassigned?

**Comment by philip-n** [comment]
Last time: Just put lots oft week tickets into the shopping cart, all for the same participant. Checked out. Result see below (I had "unassigned on all test orders, I think). Can retest later?

---

Dear ,

This is the confirmation for your order from 10.03.2015 with the order ID X621A458.

Thank you for registering for the 38th European Juggling Convention! Your registration helps us to improve the EJC 2015 for you and for all fellow jugglers.

You chose Bank Bruneck as payment method.

Please transfer the entire amount of your order within 14 days. To gain from the pre-booking conditions, please make sure that the payment is processed on time (31st of May / 15th of June), even if there are less than 14 days left.

In case you chose 'bank transfer' as payment method please transfer the entire amount of your order to the following account:

Please transfer the amount by SEPA bank transfer to the following account:

To make the orgas life easy, please add the reason for payment: X621A458

Owner	STICHTING EUROPEAN JUGGLING ASSOCIATION
IBAN	NL84 INGB 0007 8721 92
BIC	INGBNL2A
Amount	3.000,00 €
reason for payment	X621A458
Please state your order ID X621A458 as reference at your transfer form.

In case you chose credit card as payment method and your payment was not successful, you can restart your credit card payment via the following link:

%resume_link%
Please consider our general terms and conditions, which are attached to this email. To be able to read the document, you need to install Adobe Acrobat Reader, which you can download here: http://get.adobe.com/de/reader

Your eTickets and further information concerning the 38th European Juggling Convention will be delivered in another email after your payment has been confirmed.

We are looking forward to welcoming you in Bruneck!

Best regards,
Your European Juggling Association and the local EJC 2015 organizers

You purchased the following items:

unassigned items

Product	Amount	Price	
week ticket adult	1	120,00 €	
week ticket adult	1	120,00 €	
week ticket adult	1	120,00 €	
week ticket adult	1	120,00 €	
week ticket adult	1	120,00 €	
week ticket adult	1	120,00 €	
week ticket adult	1	120,00 €	
week ticket adult	1	120,00 €	
week ticket adult	1	120,00 €	
week ticket adult	1	120,00 €	
week ticket adult	1	120,00 €	
week ticket adult	1	120,00 €	
week ticket adult	1	120,00 €	
week ticket adult	1	120,00 €	
week ticket adult	1	120,00 €	
week ticket adult	1	120,00 €	
week ticket adult	1	120,00 €	
week ticket adult	1	120,00 €	
week ticket adult	1	120,00 €	
week ticket adult	1	120,00 €	
week ticket adult	1	120,00 €	
week ticket adult	1	120,00 €	
week ticket adult	1	120,00 €	
week ticket adult	1	120,00 €	
week ticket adult	1	120,00 €	
Subtotal:	3.000,00 €	
Order amount:	3.000,00 €
Payment Charge:	0,00 €
Total amount:	3.000,00 €

**Comment by inbaz** [comment]
I thin your week ticket was not personalized in the Admin Panel. Please retest on a recent system with live data. We'll write an email to all testers with the new url the next days.

**Comment by philip-n** [comment]
Just tested on test.ers.inbaz.org (is this still valid?). The browser confirmation page of the order already lists the week ticket as "unassigned":

##Shopping Cart##
*unassigned items*
Product	Amount	Price
week ticket adult 	1	120,00 €

**Comment by philip-n** [comment]
Tested again on 0.2.34.
> Created one person with name, birth date and mail
> Put one product of each available in the shopping cart
> All tickets were assigned to the person, t-shirt was not
> In the shoppin cart, all tickets are listed unter "philip nicolai", t-shirt as unassigned

Contrary to before (see last comment), the orders are not listed on the "pay via bank transfer" page any more that is shown after licking "buy now" (probably intentional change?).

**Important point:** The confirmation mail still lists all items as unassigned (see below). Is this still expected behaviour as per your last comment?

---

```
(snip)

You purchased the following items:
unassigned items
Product 	Amount 	Price 	
t-shirt ( color: red; size: S ) 	1 	15,00 € 	
	Subtotal: 	15,00 € 	
unassigned items
Product 	Amount 	Price 	
week ticket adult 	1 	200,00 € 	
week ticket including gala show (adult) 	1 	23,00 € 	
day ticket youth ( day: August 1 ) 	1 	13,50 € 	
day ticket child ( day: August 1 ) 	1 	9,00 € 	
	Subtotal: 	245,50 € 	
Order amount: 	260,50 €
Payment Charge: 	0,00 €
Total amount: 	260,50 €
```

**Comment by philip-n** [comment]
As per our mail exchange: The problem seems to occur if one person purchases stuff for himself only and if that person has selected "no country".

**Comment by philip-n** [comment]
Correction: I created an account quite some time ago on my mail address. It only has the mail address stored (can't change as the "My Profile" > "Change my user data" is not yet implemented) and no further information (name, country, age).

Seems that if I 
* create a person with the same mail adress (with all information)
* perform an order on this person
, then things go pear-shaped. Same behaviour if I'm logged in or not.

I'd guess that in some step, the existing accounts take precedence over the persons created during orders?

**Comment by jackcaveman** [comment]
I have the same problem when I use the j3.verbree@gmail.com address for which I have an account. The tickets for this address/person shows up "unassigned" in the email.

If I use a different address (jverbree@lumc.nl) the Salutation and tickets are named correctly.
v.0.2.35

**Comment by philip-n** [comment]
I had a mail conversation with Andi to figure this out. In the end, the problem disappeared when he (manually) added my name to the existing account.

So the issue is confirmed and (at least) traced back to its origin; Andi is probably working on a fix.

@inbaz (and all): Would it be an option to leave everything as is, but only give the user the possibility to create an account **after** he has made an order (or at the "Add purchaser" stage)? At that point, all data for the person should be available (at least full name). I guess that there's no big benefit in creating an account just for the sake of it (or is there?).

**Comment by inbaz** [comment]
Did we solve that problem today?

**Comment by philip-n** [comment]
Yes and no... we figured out the cause and how to solve it manually. If I were a new user and created a new account first, the problem would re-occur, I guess.

So up to you to decide if it's solved (as it is not a general problem as I described it in the issue, but rather a special one) or not (as it could occur again). Sorry!

**Comment by smadamit** [comment]
I think it's an open issue. Have to be fixed and depends strongly on: #57

If you are logged in and start an order your account (name of the account) have to be in the my persons list. As far as I understand, that would fix the problem. And in user/register we need the name?

**Comment by smadamit** [comment]
deactivate register function

**Comment by inbaz** [comment]
turned off register function. Keep in mind that if a user is added without any purchase some fields will be missing in an order if they are not filled in correctly.

**Comment by inbaz** [comment]
When activating the registration again the registration form needs to contain all required fields for every user. Maybe include checks before an order is saved if the user to which the order will be assigned to has all needed fields filled.
