### ISSUE TITLE
Blank page after editing an item in shopping cart

### ISSUE THREAD

**Issue by philip-n** [inbaz/ers#150]
Shopping cart > Click "edit" next to an item (tested: shirt) > change some property (e.g. color) > Click "save changes"

==> Blank page appears (http://test.ers.inbaz.org/product/edit/5/0/16)

**Comment by philip-n** [comment]
Change was successful, shopping cart remains intact.

**Comment by philip-n** [comment]
Probably duplicate of #145

**Comment by inbaz** [comment]
Please retest.

**Comment by philip-n** [comment]
Tested with t-shirt and week ticket, both working as intended.

-> Closing.
