### ISSUE TITLE
find another wording for unassigned items

### ISSUE THREAD

**Issue by inbaz** [inbaz/ers#151]
unassigned items sounds a bit negative. Let's find another wording for that. When somebody orders just a t-shirt or GalaShow Tickets in the email you won't read unassigned items. It sound like you have forgotten something.

**Comment by christianbross** [comment]
I have thought about it.
I could propose "Separate items". 
I'm not sure if it's a lot better, but may be a little bit better.

**Comment by smadamit** [comment]
What about:
Products assigned to purchaser (Max Muster)

von unterwegs gesendet
Am 18.03.2015 21:56 schrieb "Christian Bross" <notifications@github.com>:

**Comment by philip-n** [comment]
I'd suggest "Further items". Might look a little weird if someone only orders non-personalized items, but I guess that 99% of the people also order at least one ticket.

**Comment by inbaz** [comment]
changed to further items, I like that.
