### ISSUE TITLE
Please secure the eja Webserver with a password

### ISSUE THREAD

**Issue by inbaz** [inbaz/ers#153]
Hi Staffan,

please secure the webserver with a password, so nobody can find the prereg on the server. I just deployd the newest dev version to the production server.

greetings
Andi

**Comment by staffanu** [comment]
This is now done. Right now only I have a password. Anyone in the group eja (I think everyone that can currently log in to the server) can add themselves to the list of accespted passwords using this command:

htdigest /home/eja/apache-resources/htpasswd.digest EJA <username>

Staffan

**Comment by inbaz** [comment]
I added a test account with which we can let the admins and some testers can easily access preprod, so for me this is fixed.
