### ISSUE TITLE
Direct access of bank transfer confirmation page

### ISSUE THREAD

**Issue by philip-n** [inbaz/ers#154]
If there was no previous payment by bank transfer, directly opening http://test.ers.inbaz.org/payment/banktransfer gives a partial page (without any css or formatting). Otherwise, it shows the last successful payment information.

--> Show a nicer page when http://test.ers.inbaz.org/payment/banktransfer is accessed and no previous bank transfer was performed.

---
Full page source:
```
<h1>Pay via Bank Transfer</h1>
<div>
    <p>Please transfer the amount by SEPA bank transfer to the following account:</p>
    <p>To <strong>make the orgas life easy</strong>, please add the reason for payment: <strong>
```

**Comment by inbaz** [comment]
Please check if this is already fixed in up to date version. If so please close.

**Comment by smadamit** [comment]
0.2.58 -> OK
