### ISSUE TITLE
email text: name of person

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#156]
test 0.2.27

- new session logged out
- product
- week ticket adult
- add person to this list
- tim -> add
- add to card
- popup -> shopping card
- product
- t-shirt: green, L, do not assign
- add to card
- popup -> shopping card
- t-shirt -> edit
- (bug edit t-shirt -> default select values wrong)
- t-shirt: red, S, tim
- popup -> shopping card
- tim -> edit
- change birthdate -> save
- t-shirt edit
- add person to this list
- leonie -> save
- t-shirt: red, S, leonie -> save changes
- popup -> shopping card
- t-shirt -> edit
- not assign -> save
- popup -> product
- day ticket child
- add person
- isabelle -> save
- 2 August, isabelle -> add to card
- popup -> shopping card
- shirt -> edit
- isabelle -> save
- popup -> shopping card
- checkout this card
- tim -> save purchaser
- bank -> save payment
- buy now

-------------------------------------
got Mail (order ID 36PR5M97) with:
-------------------------------------
You purchased the following items:

Tim Adams

Product	Amount	Price	
week ticket adult	1	120,00 €	
Subtotal:	120,00 €	

**Verbree -> should be "Isabelle Adams"**

Product	Amount	Price	
day ticket child ( day: August 2 )	1	5,00 €	
t-shirt ( color: red; size: S )	1	15,00 €	
Subtotal:	20,00 €	
Order amount:	140,00 €
Payment Charge:	0,00 €
Total amount:	140,00 €

**Comment by smadamit** [comment]
maybe same as #149

**Comment by inbaz** [comment]
For this we need the login functional to be able to change my own name in case I already have an account and secondary we need to check if the email address of a person already exists in the system. If so the user needs to login to be able to change these data or additionally purchaser another item.

**Comment by smadamit** [comment]
But is this the reason here? I added Isabelle Adams as a person but without email. So Isabelle Adams wasn't linked to an account (email). So I don't understand where the system takes the name "Verbree" from.

What do you do with persons, which are added without email? How do you store them in the database? And same question for persons with defined email?

**Comment by inbaz** [comment]
Can you reproduce this problem?

**Comment by smadamit** [comment]
0.2.29 retest

yes in test.ers: X2VNV137 -> Verbree instead of Isabelle Adams
in preprod -> no.
So it depends on the database...

**Comment by inbaz** [comment]
Please retest, this was a problem when there is no email given. I needed to explicitly set the email field to null on save. Try if that's working now.

**Comment by smadamit** [comment]
will be fixed with #135

**Comment by smadamit** [comment]
I did some tests to understand the issue in more detail... 0.2.36
