### ISSUE TITLE
destroy session after finishing checkout

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#157]
You did an order and have checked out. You get the last page: payment/banktransfer

Now you do anything, but if you enter into the browser address field "payment/banktransfer" you can see the old buying data again. Maybe we should destroy the old session of the buying to avoid side effects or bugs?

**Comment by philip-n** [comment]
See also #154

**Comment by inbaz** [comment]
Would it be a solution to let the user access this page for maybe 5 minutes after his purchase and then this session container gets destroyed?

**Comment by smadamit** [comment]
that would be fine for me

**Comment by philip-n** [comment]
I'd argue for an immediate destruction of the session. Let's say I just ordered my ticket and for some reason now want to order separately for somebody else. I'd expect to immediately be able to perform the second order and would probbaly regard different behaviour as a bug.

**Comment by inbaz** [comment]
I solved that by deleting this session container in payment and purchaser chooser. So for a new order you need to go through there again. Does that work for us for now?

**Comment by philip-n** [comment]
Can't really test atm (I am at work and need to get things done), but sounds good!

**Comment by jackcaveman** [comment]
Seems fixed like you describe.

After ordering some products. Final page is /payment/banktransfer
When I navigate to /home and /products  and /participant I can still access
the old bankinfo on /payment/banktransfer
When I navigate to /order the bankinfo i get an unadorned error "There is
no order to show bank transfer details for".
v0.2.36 on test

**Comment by smadamit** [comment]
v0.2.36 -> tested and OK
