### ISSUE TITLE
product/edit leave the popup for "save changes"

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#159]
You edit a product which is already in the card. in the edit form you change the values and click "save changes". Now you get a popup to choose the next step: card or products.

I suggest to leave the popup here. Doesn't make sense at this point.

**Comment by inbaz** [comment]
Without this popup you have to verify the changes in the cart by yourself what could be annoying if you have many items in your shopping cart. The system just confirms what you have done and gives you the possibilities what to do next.

**Comment by smadamit** [comment]
I insist on: "The popup doesn't make sense at this point." So I reopen it. I put the issue to milestone: afterEJC since it is not important for now. Let's discuss it later.

**Comment by smadamit** [comment]
I discussed with Christian and we have the following proposal:

## add new product

If you add a new product you get a popup with three buttons:
- product-list
- shopping cart
- add one more "week ticket"/"gala show ticket"/"day ticket"

We don't need the cross of the popup. See also: #303

## edit product

If you come from the shopping cart and edit an existing product you don't get a popup. You get directly back to the cart after saving the changes.

**Comment by smadamit** [comment]
0.3.27

- add new product -> OK
- edit product -> open issue: "You should get directly back to the cart after saving the changes."

**Comment by inbaz** [comment]
This was not that easy, but at least it's implemented.
