### ISSUE TITLE
deadlines and agegroups

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#161]
**deadlines**

We use deadlines to define changes of price and we use deadline to limit the time where the jugglers can buy tickets via a specific payment type. My suggestion is, that we add to new fields to deadlines:
- deadline: DATETIME defines the deadline
- name: VARCHAR describes the deadline
- price: BOOLEAN defines if the deadline change the price

So in the end only deadlines which have price set to TRUE appear in the price matrix of products.

**agegroups**

Similar to deadlines it would be nice to add the filed:
- price: BOOLEAN defines if the deadline change the price

Only if price set to TRUE the agegroup appears in the price matrix of products.

Why do I need it? Maybe adults is defined for juggler from 16 - 99 years. So we need a DATE which defines the change from 15 to 16 years. But we also need the change from 17 to 18 to define the etickets due to the form for protection of minors.

One last issue: for agegroups the type should be DATE not DATETIME

**Comment by inbaz** [comment]
#163 I will track the change of agegroup type in this ticket. Please open separate tickets for separate tasks.

**Comment by inbaz** [comment]
Should I add a seperate field to use a deadline for payment type or should I display all deadlines for payment types?
Should I add a separate field to use a agegroup for formular generation?

**Comment by smadamit** [comment]
At the moment you don't need to add separate fields for payment type and formular generation. Maybe later.

**Comment by smadamit** [comment]
@inbaz You added priceChange to agegroup -> OK. But has no influence to the price matrix yet. Am I right?

**Comment by inbaz** [comment]
Correct

**Comment by smadamit** [comment]
tested in 0.2.36 -> OK
