### ISSUE TITLE
Change type of agegroups from datetime to date

### ISSUE THREAD

**Issue by inbaz** [inbaz/ers#163]
for agegroups the type should be DATE not DATETIME

**Comment by smadamit** [comment]
tested -> not able to edit existing agegroups or to create new ones
- validation error: "The input does not fit the date format 'd.m.Y'"

**Comment by inbaz** [comment]
I changed the type of agegroups to date. Please retest, maybe this has any side effects which I have not already tested.

**Comment by smadamit** [comment]
change
<input type="date" name="agegroup" ...>
to
<input type="text" name="agegroup" ...>

same as for birthdate in add person form. To avoid the Chrome feature (calendar).

**Comment by inbaz** [comment]
Where should I change that? Since html is getting generated I cannot grep for type="date".

**Comment by smadamit** [comment]
sorry. In the view of admin/agegroup/add
Just change the type of the field Agegroup from DATE to TEXT

**Comment by inbaz** [comment]
I think I changed now all these fields. I grepped through the code and were not able to find a field of type Date anymore, they are all DateText now which results in the input type="text" we want.
