### ISSUE TITLE
breadcrumb: admin/product-price/add bug

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#164]
prerpod: 0.2.28

was not able:
- Message: Params is expected to be an array or a Traversable object

**Comment by smadamit** [comment]
second time it was no problem

**Comment by inbaz** [comment]
This is the breadcrumb system. When this bug appears, please write down your clickroute with which you came to this page.

**Comment by smadamit** [comment]
@inbaz the problem of the breadcrumb issues is that they always appear when you are not expecting it. And than you have no idea of the many clicks you did before... If I try to reproduce it there are no problems.

**Comment by smadamit** [comment]
Is it again the breadcrumb system?

Message: Params is expected to be an array or a Traversable object

I came from:
- ???
- admin
- admin/product
- admin/product/view/4
- admin/product
- admin/product/view/4
- admin/product/edit/4
- clicked "edit" -> error

**Comment by smadamit** [comment]
I retested and could not reproduce it:
- admin
- admin/product
- admin/product/view/4
- admin/product
- admin/product/view/4
- admin/product/edit/4
- clicked "edit" -> no error

**Comment by inbaz** [comment]
I think you got that problem when you saved a product. I did a quick fix and redirect you to the list of products if I cannot find another route back. Keep an eye on it and if this error occurs again, please copy the whole file list. Then I'm able to check where the system was unable to redirect you. I need as much information as possible to solve this problem. Maybe I can see a pattern to be able to solve it over the whole system, but at the moment it's like searching the needle in the haystack.

**Comment by smadamit** [comment]
0.2.36: had some test cases and coundn't reproduce

**Comment by smadamit** [comment]
0.2.39

same bug. Again in admin panel:

Message: Params is expected to be an array or a Traversable object

Since it is not crucial and in admin panel I reopen, but for afterEJC
