### ISSUE TITLE
Wording on ticket participant selection

### ISSUE THREAD

**Issue by philip-n** [inbaz/ers#165]
Problem: 
1. Select a ticket
2. Add a participant, mistype the name
==> Wrong name is shown unter the ticket image. User wants to change the incorrect name before buying the ticket!

Now there is no obvious way to edit/change the participant info. Only available buttons are "add person to this list" or "Add to cart" --> both not what the user intends to do.

Solution: Either add an "edit participant" button (preferred) or somehow convince the user that "add person to this list" is what he actually wants to do ;-)

**Comment by smadamit** [comment]
Maybe the solution could be to make a comment that the existing users can be edited under the menu point my persons?

**Comment by inbaz** [comment]
Since the select box does not update the page, yet, I do not know which participant is chosen at the moment. @philip-n do you agree to the comment with a link to the My Person page?

**Comment by philip-n** [comment]
Yes. "Note: You can change information about any person in this list by clicking 'My Persons' from the main menu and then editing the according person."

**Comment by inbaz** [comment]
I added this note only in the edit dialogue. Is that ok?

**Comment by smadamit** [comment]
0.2.39

the note is under person select list in product/add -> OK
