### ISSUE TITLE
agegroup frontend: price matrix

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#167]
first test in preprod 0.2.28:
- select of the right agegroup works
- But prices are all 0 € in product/add
- price OK in card
- product/index maybe list also all prices? And not in grey.

admin panel:
![screen-admin](https://cloud.githubusercontent.com/assets/1533081/6605614/99f2b13c-c831-11e4-8509-d9443a90fc4c.png)

product add:
![screen-frontend](https://cloud.githubusercontent.com/assets/1533081/6605617/a100d378-c831-11e4-97d4-84211fb029ff.png)

card:
![screen-card](https://cloud.githubusercontent.com/assets/1533081/6605621/aade6fd6-c831-11e4-943a-aa6c999bc0a8.png)

**Comment by inbaz** [comment]
Did you change anything what fixed this? I can see all prices. There will not be an agegroup Adults 16 - 99 years, this is no Agegroup.

**Comment by smadamit** [comment]
no I changed nothing, but you did a new update to 2.29. So maybe you fixed?

What do you mean with: "There will not be an agegroup Adults 16 - 99 years, this is no Agegroup." Why is that no agegroup?

**Comment by inbaz** [comment]
Maybe I fixed it, I don't know. There are Agegroups like child and youth and adults are "the others" with simply no Agegroup. No Agegroup is intended to be the highest price at it will be used as fallback of no agegroup can be found that fits.

**Comment by smadamit** [comment]
That's not intuitive for the admin panel and it's a problem because you can not set the name of "no agegroup".

My suggestion is, there are 4 consistent price matrix variants (cross means a defined price):

matrix |          |           |         |             .
---------|--------|---------|--------|-----------
 | child | youth | adult | no agegroup
deadline 1 | x | x | x | -
deadline 2 | x | x | x | -
deadline 3 | x | x | x | -
no deadline | - | - | - | -

deadlines |          |           |         |             .
--------------|--------|---------|--------|-----------
 | child | youth | adult | no agegroup
deadline 1 | - | - | - | x
deadline 2 | - | - | - | x
deadline 3 | - | - | - | x
no deadline | - | - | - | -

agegroups |          |           |         |             .
---------------|--------|---------|--------|-----------
 | child | youth | adult | no agegroup
deadline 1 | - | - | - | -
deadline 2 | - | - | - | -
deadline 3 | - | - | - | -
no deadline | x | x | x | -

one price |          |           |         |             .
-------------|--------|---------|--------|-----------
 | child | youth | adult | no agegroup
deadline 1 | - | - | - | -
deadline 2 | - | - | - | -
deadline 3 | - | - | - | -
no deadline | - | - | - | x

Let's discuss it in Skype...

**Comment by smadamit** [comment]
Why is this product "week ticket child" in test.ers 0.2.31 not listed in the product list:

![screen-price-matrix](https://cloud.githubusercontent.com/assets/1533081/6620188/a40ba95a-c8cf-11e4-8ca4-fc267a6d6512.png)

In my logic it's from type matrix (see post before). We should discuss this point soon. I'm not sure which point of view is the best solution for the interpretation of the price matrix.

**Comment by smadamit** [comment]
decision: the whole price matrix including no deadline and no agegroup have to be valid in admin panel. no  agegroup is the fallback -> adults. no deadline is the fallback -> after last defined deadline.

**Comment by inbaz** [comment]
Is there an open todo in this issue or can we move it to another milestone?

**Comment by smadamit** [comment]
No open todos for now. I added some notes to #162 for the future after EJC2015.
