### ISSUE TITLE
checkout buy now bug

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#168]
test 0.2.29

- added week ticket child isabelle
- purchaser tim
- cehckout
- buy now: error

Message:
An exception occurred while executing 'INSERT INTO Item (Product_id, Package_id, Code_id, `name`, shortDescription, longDescription, price, amount, info, `status`, personalized, updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [4, 105, 25881, "week ticket child", "short", "long\r\nsadsadf", null, 1, null, null, 1, "2015-03-12 11:35:11", "2015-02-12 13:16:32"]:

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'price' cannot be null

**Comment by smadamit** [comment]
maybe because of not well defined price matrix?

**Comment by smadamit** [comment]
in preprod 0.2.29:
- There was no problem

**Comment by inbaz** [comment]
Let's keep that in mind. If you encounter this problem check if  the product has at least a price with no Deadline and no Agegroup. If it does it's a problem of the system if not, add one. :)

**Comment by inbaz** [comment]
Let's close this issue and reopen it when we encounter problems according to that.
