### ISSUE TITLE
not able to assign a t-shirt to a person

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#169]
t-shirt is not personalized -> so to assign to a person is optional, but should be possible. In test.ers 0.2.31 it is not possible anymore. Not in product/edit and not in product/add form. Please fix it.

**Comment by inbaz** [comment]
Uh, that was a quick change which destroyed this functionality. This will be in again in 0.2.32.

**Comment by smadamit** [comment]
test.ers 0.2.32

No, doesn't work.

**Comment by inbaz** [comment]
That was too fast, pleas do a complete retest. I just checked it. If no person is added there will be no select box for non personalized product. If there is a person in this session you will see the select box. I did some more enhancements to 0.2.33 on that.

**Comment by philip-n** [comment]
Works for me.

**Comment by smadamit** [comment]
tested in 0.2.36 -> OK
