### ISSUE TITLE
preregpp.eja update

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#171]
Can you please push the latest update to preregpp.eja.

And one problem. The version is not displayed:

![screen](https://cloud.githubusercontent.com/assets/1533081/6628876/5aa460d8-c909-11e4-98bb-d454726e7002.png)

After that I can start to set up the productive admin configuration.

**Comment by inbaz** [comment]
I do not have rights to setup the correct version.

@staffanu could you provide rights on that directory? Or just do a

```
git pull
git checkout tags/0.2.31
```

**Comment by staffanu** [comment]
I think the problem was that some files were not group writable.  That should be fixed now. If it still doesn't work I can of course update, but I'm not right now so that you can test it again.

Staffan
