### ISSUE TITLE
PHP Timezone setting

### ISSUE THREAD

**Issue by inbaz** [inbaz/ers#172]
Hi Staffan, could you please add the Timezone setting to php.ini to Europe\Berlin or Europe\Amsterdam?

**Comment by staffanu** [comment]
This was already done for when apache runs php, but not from the command
line. It is now set to Europe/Amsterdam in both files
(/etc/php5/apache2/php.ini and /etc/php5/cli/php.ini).

Staffan

**Comment by smadamit** [comment]
@inbaz I guess this is fixed right?
