### ISSUE TITLE
admin/payment-type 404 bug

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#173]
preregpp 0.2.32

It worked a few minutes ago. After I tried to add a payment type it was broken.

Message: Your proxy directory "data/DoctrineORMModule/Proxy" must be writable

**Comment by smadamit** [comment]
exactly the same problem now with admin/product. It worked, now it's broken (after first try to add a product).

![screen](https://cloud.githubusercontent.com/assets/1533081/6645266/51088704-c9bb-11e4-8e9d-05be7de015f0.png)

**Comment by smadamit** [comment]
in test.ers 0.2.32 the problem does not exists. So it depends on the server.

**Comment by inbaz** [comment]
@staffanu can you please set write permission to the directories
* data
* tmp
