### ISSUE TITLE
admin/country/edit/199 unable to delete country sorting

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#174]
preregpp 0.2.32

Please add a delete function to admin/country

**Comment by inbaz** [comment]
Workaround: When you insert 0 as order value it's internally replaced by null. Does that work for you?

**Comment by smadamit** [comment]
no it doesn't. If I set 0 to Spain, it is the first in the list.

**Comment by inbaz** [comment]
I need more precise error descriptions. I just tested that in preprod which has worked. What does it do when you set it to 0?

**Comment by smadamit** [comment]
it works
