### ISSUE TITLE
product/index design: border for product boxes

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#175]
Give the product boxes an border. I think it's a clearer design.

**Comment by inbaz** [comment]
fixed in 0.2.33

**Comment by smadamit** [comment]
no borders in product/index. Tested in preprod 0.2.36

**Comment by inbaz** [comment]
Ah, wrong products. :) I thought you ment the ones in the shopping cart. There is a thin line under each product, can you see it? Does it need to be darker?

**Comment by smadamit** [comment]
yes I can see it. But I would like to have a distinct border around the product boxes. That would be nice. In the moment the product text is kind of disconnected. My opinion...

**Comment by inbaz** [comment]
fixed in 0.2.45

**Comment by smadamit** [comment]
Thanks
