### ISSUE TITLE
allow price add only for can change price agegroups and deadlines

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#176]
You do not show prices to deadlines or agegroups which have no priceChangeFlag set. But you do not avoid to that such values in database: admin/product-price/add I can live with that, but I am afraid, that someone, maybe I, set a value, which could not be seen in the price matrix and have side effects to the functionality of prices... Do yo understand my concerns?

At least we should search for such hidden prices directly in the database before going live.

**Comment by smadamit** [comment]
And there are agegroups in the frontend which should have no price: see preregpp 0.2.32 product/index
U16 and U18 should be without prices.

**Comment by inbaz** [comment]
This should be fixed in 0.2.34.Watch out if there ore other points where this is important and leads to db entries which can't be deleted anymore.

**Comment by smadamit** [comment]
todo for after EJC: validate that all prices are consistent. no duplicates, no prices to deadlines or agegroups which have not priceChangeFlag.

See also: #194
