### ISSUE TITLE
price selection for non personalized products

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#177]
preregpp 0.2.32

If there are products which are not personalized, there is no way to select a youth price. At the moment 
the price selection is automatic and depends on the selected person...

**Comment by inbaz** [comment]
It's possible to add a person and assign this item to this person, or not?

**Comment by smadamit** [comment]
We need the feature to choose the agegroup/price manually. The gala show ticket of the EJC 2015 will be non personalized. And a purchaser have to be possible to order a few tickets (different agegroups) without entering personal data (my persons-list).

**Comment by smadamit** [comment]
not sure how to implement it. Let's discuss it in skype.

**Comment by inbaz** [comment]
added agegroup selection

**Comment by smadamit** [comment]
0.2.50 -> tested OK
