### ISSUE TITLE
implementation of agegroups

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#18]
I think this is really pressing! There are so many dependencies!

We need the agegroup table in the database as it was planned in the beginning. agegroups are connetced to prices, like it is the case for deadlines. So when there are 3 agegroups and 4 deadlines in the database, there can be a matrix of 3 x 4 = 12 prices for one product -> week ticket. At the moment we have different products for different agegroups. This have to be changed.

**Comment by inbaz** [comment]
Started to implement agegroups. Backend is ready frontend needs to be done.

**Comment by smadamit** [comment]
After we have the new table agegroup we should arrange the prices by a matrix deadlines vs agegroups.
This concerns:
- Admin/Product/index
- Product/index

**Comment by smadamit** [comment]
agegroup should be a date, not a datetime

**Comment by inbaz** [comment]
Please open all new issues on that in separate tickets. Implementation itself is done.
