### ISSUE TITLE
Blank page after checkout 

### ISSUE THREAD

**Issue by philip-n** [inbaz/ers#180]
Happened to me twice this evening (1x Firefox, 1x Chrome):
* Added product(s) to shopping cart
* Did all payment steps (added purchaser, selected bank transfer as payment)
* Clicked "Buy now"

==> Resulted in an empty (blank) page

* Pressing F5 got me the browser warning "Your data has already been sent, reloading this page might result in your action being performed twice, yadayadah"
* I confirmed the page reload, then the correct confirmation page appered

Can someone else test? I assumed a hiccup with my internet connection when it happened the first time, but two times in two browsers seems strange.

**Comment by philip-n** [comment]
Just tested again, this time it worked smoothly. Can anybody confirm and close this issue?

**Comment by inbaz** [comment]
There could be many things that causes this issue. A php module was missing to correctly send out the email, there was a small error in the overview page. What I'd like to say is: I fixed some things which could have been the cause for this problem. Please recheck.

**Comment by philip-n** [comment]
Didn't have the problem any more since bug report. Will reopen if it happens again.

P.S.: Nope. Regard it as a warming up for easter-egg hunting :-P
