### ISSUE TITLE
Subsequent purchases not possible

### ISSUE THREAD

**Issue by philip-n** [inbaz/ers#181]
1. I order a ticket for one person, add a purchaser, select bank transfer, do the check out, get the confirmation.
2. The shopping cart is now empty, the list of persons is also empty
3. I create a new person, order a week ticket, add the new person as purchaser, select bank transfer, want to check out
4. Instead of getting to the check out page, I see the confirmation page of the last purchase. There is no possibility to check out the current shopping cart.

Highly likely related to #157, might be fixed if session is destroyed immediately and/or profile functionality is integrated?

**Comment by inbaz** [comment]
Yes, #157 will solve both problems. I will close this one.
