### ISSUE TITLE
No payment option visible

### ISSUE THREAD

**Issue by philip-n** [inbaz/ers#183]
0.2.34: There are no payment options shown.

http://test.ers.inbaz.org/order/payment only says:
"Choose Payment type"
without showing radio buttons or similar.

**Comment by philip-n** [comment]
Maybe there just no payment gateway configured in 0.2.34? But it stops me from testing stuff, so it's a prio1 bug for me ;-)

**Comment by inbaz** [comment]
There are payment types configured, but the activeFrom was set to the first prereg phase from 1.5.2015, therefore they were not available, yet. I added a new deadline the set activeFrom to 1.3.2015. You should see the payment types again.

**Comment by inbaz** [comment]
Please close this issue if that works for you.

**Comment by philip-n** [comment]
Payment works again. Closing.
