### ISSUE TITLE
Show information if no payment types are available

### ISSUE THREAD

**Issue by philip-n** [inbaz/ers#184]
If no payment modality is currently available (see #183), show a small note on the payment selection page saying

"There are currently no payment options available. Please check back at a later date. Sorry!" (or replace later date with starting date of first payment option).

Maybe even have a banner between main menu and page content, visible on all pages, saying "Ordering will be possible starting on xx.xx.xxxx. Until then, feel free to browse and select!"

**Comment by inbaz** [comment]
I fixed that on the first way. I do not have all paymenttypes in there to check out when the next paymenttype starts.
