### ISSUE TITLE
Name of products is confusing in combination with agegroups

### ISSUE THREAD

**Issue by jackcaveman** [inbaz/ers#187]
![image](https://cloud.githubusercontent.com/assets/11071240/6656365/36ec7e52-cb28-11e4-90d2-eaf6068ba545.png)

Just have the products named Weekticket / Dayticket without reference to age (e.g. adult, youth)
Pricing seems not to reflect the agegroup (child is more expensive than adult).

I think this is just something that can be changed in the admin panel and not a bug. 
v0.2.35

**Comment by inbaz** [comment]
I will close that ticket. @smadamit will do a live configuration and if this is ready we'd like to have a larger group of testers on the system to get out all the tiny small bugs.
