### ISSUE TITLE
In product detail (day ticket) the agegroup is not updated 

### ISSUE THREAD

**Issue by jackcaveman** [inbaz/ers#188]
If you select a different already existing participant from the list, the agegroup pricing highlight on the right should also update.

Note: Behind the scenes this is working ok as in the Cart the correct pricing for the agegroup is selected.

v0.2.35

**Comment by smadamit** [comment]
Is it really nice to have? It's an easy fix I guess. Just reload onchange-select-field. But low prio!

**Comment by inbaz** [comment]
I set color to black for all prices. Do we need this feature anymore?

**Comment by smadamit** [comment]
for the moment -> no
