### ISSUE TITLE
link whole container of a product

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#19]
It should be very easy to buy a product, ticket... So why not link the whole container of a product to product detail

**Comment by inbaz** [comment]
Now it is very easy, I like it. Test it!

**Comment by jackcaveman** [comment]
I can't see the improvement on http://test.ers.inbaz.org/product. Are you
guys using a different version of the system?

**Comment by inbaz** [comment]
"You guys" is just me. I do have a separate development system where I break the whole system from time to time. If my dev system and your testing system would be the same I need to implement new features to fast to not disturb you while testing. This is a stress factor I'd like to avoid. We're paying this with issues marked as solved even if it's not solved in the testing system, yet.

**Comment by smadamit** [comment]
Nice. Please make the mouseover-color little bit darker. At many screens you can not/hardly see the light grey color on the white background.

**Comment by smadamit** [comment]
Thanks
