### ISSUE TITLE
Confirmation email text: link to adobe should be english

### ISSUE THREAD

**Issue by jackcaveman** [inbaz/ers#191]
Currently the link to the adobe software links to the German page.

**Comment by inbaz** [comment]
I think the legal will not be attached as pdf but there will only be a link to the online version. If so we do not need this acrobat reader link. We need to wait for an answer of a lawer.

**Comment by smadamit** [comment]
can maybe be solved with #16

**Comment by jackcaveman** [comment]
Under dutch law you have to have
1) Terms and Conditions that the purcharser can save (and print), so link
to PDF should be fine.
2) checkbox "I read and agree to the Terms and Conditions".
not required by law but nice: popup with the Terms in plain html

**Comment by inbaz** [comment]
Adobe is cool! I simply linked to http://get.adobe.com/reader they go and get the setting of the browser and redirect you to the correct language. I'll give this ticket to @smadamit because we need the legal terms to be able to create the pdf.

**Comment by smadamit** [comment]
tested in 0.2.48 -> OK

legal terms have an extra issue
