### ISSUE TITLE
check prices in database

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#194]
before going live:
- let's do some mysql SELECTs to check that all prices are consistent:
 - no duplicates
 - no prices to deadlines or agegroups which have not priceChangeFlag
 - count the prices in database and check if it is divisible by 12
- secure admin panel -> only admin (Tim, ...) can change prices...

**Comment by smadamit** [comment]
duplicate prices can be seen in the price matrix of the admin panel

**Comment by inbaz** [comment]
send you an csv export

**Comment by smadamit** [comment]
consistence check -> OK

@inbaz Just as reminder. If we add any new persons we have to check the access rights! I close the ticket.
