### ISSUE TITLE
participant/add comment to email field

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#199]
the problem:

You can't add multiple participants with the same email address (I have not yet selected a purchaser). I agree with Philip that this is not expected behavior is you are ordering for a family with 5 children.

the solution:

Maybe we need a general explanation for the users, how the order is working.

Short note next to the email field:
- "If you enter an email address to this person all his/her etickets will be sent directly to him/her... All etickets will also be send to purchaser..."
- "E-ticket(s) are send directly to this person's email. To receive the eticket(s) on your own email address, leave it blank".

**Comment by philip-n** [comment]
That's what I have in mind for tomorrow evening :-)

**Comment by smadamit** [comment]
@philip-n maybe you can also have a look to #49

**Comment by inbaz** [comment]
check that first in 0.2.39.
