### ISSUE TITLE
Match a single bank transfer to multiple orders

### ISSUE THREAD

**Issue by inbaz** [inbaz/ers#202]
Make it possible to match a single banktransfer i.e. from Britain to multiple orders.

**Comment by jackcaveman** [comment]
@inbaz Sorry for not commenting on this during the skype call.
In previous years we just left the money in the UK account until we needed
it. As we have enough in the Dutch EJA account to cover that amount.

1) Ron (UK Rep) collects all checks and cashes them.
2) He tells me which orders have been payed.
3) I (?) can then change the order status (or amount payed) in the admin
panel.

I think this is the fastest way for the tickets to reach the participants
for it can take a while for Ron to transfer the money.

**Comment by smadamit** [comment]
@jackcaveman works for me. We will discuss this in detail after going live.

**Comment by inbaz** [comment]
@jackcaveman maybe the database model gives us the possibility to create a "virtual" bankaccount for this case where you can match the paid orders to so we're then able to get the amount of money which needs to be transferred from the real bank account in once without any calculation.

**Comment by inbaz** [comment]
There is the possibility to add virtual bank accounts now. With a dummy bank statement it's possible to add multiple orders to this statement. There it's possible to calculate the minus amount on this account i.e. on a statistics page. Will that solve the initial problem? Can this issue be closed?

**Comment by smadamit** [comment]
I think this is solved with the new version with the matching -> So I close it.
