### ISSUE TITLE
Price needs to change when a person is changed

### ISSUE THREAD

**Issue by inbaz** [inbaz/ers#203]
1. Put a personalized product in the shopping cart
2. go to My Persons
3. Edit the date of birth of the participant to whom the former added product belongs to
4. Go back to shopping cart
-> Price needs to change!

**Comment by jackcaveman** [comment]
duplicate of #188

**Comment by smadamit** [comment]
not really #188 is nice to have, this issue is crucial

**Comment by inbaz** [comment]
fixed that in 0.2.39. on /order and /order/checkout before displaying the cart all items are checked against the product and the user that owns this product. If a price is not correct it's changed.

**Comment by smadamit** [comment]
tested in 0.2.39 -> OK
