### ISSUE TITLE
Raimar's findings

### ISSUE THREAD

**Issue by PiQuer** [inbaz/ers#204]
Hi there to all Devs,

first of all: great job on the prereg site, it looks and feels very polished overall. I found several smaller issues and glitches which I try to describe here. Please excuse if some of the issues are already assigned other bugs, I did not go through all open issues.

# Textual issues #
Some are just simple spelling mistakes, but I will also point out passages which I feel could be worded differently.  As I am not a native speaker, I might very well be wrong and these are only suggestions :) Also I'm not through all pages yet, I will add items as I find them.
## Main page ##
* "... help the orga team by register**ing** your ticket and pay**ing** early."
* "**watch** the product list":  I think "to watch" always involves some period of time ("beobachten"), therefore I would suggest "Take (or Have) a look at the product list." Anyhow, there is a "." missing at the end of the sentence.

## Checkout page ##
The page with the "Buy now" button
* In the "Purchaser" box last word: "aswell" -> "as well"
* In the "Payment SEPA" box: "Please make a SEPA bank **transfer**  to the EJA bank account and don't forget to mention your order **number** in the reference."
* "In this case it is much **cheaper**..." (spelling mistake). However, for me "cheap" has some negative connotation, I would suggest "... it is much less expensive...."
* In the "Payment Credit Card" box: "...you have to pay the fees", this sounds a bit rude to me. I would suggest: "Please note that additional credit card fees are charged:  1.9 % **of** the original total amount plus 0.15 € per payment."

# Minor confusions #
* In the SEPA information: two years ago when I preregistered, I found it confusing that my bank offered two fields, "Verwendungszweck" and "Kundenreferenz". I didn't really know where to put my order number. Does it matter, are both ok? Maybe we could somehow clarify this in the info? Maybe this is just a German thing...
* When adding persons to the list "on the fly" during ticket selection, it is not possible to edit person details, only add new ones. If I made a mistake I could wonder how to correct it. I can not add the corrected person again (at least not with the same email address). Maybe a little hint that later in the shopping cart or in the "My Persons" category it is possible to edit the details?
* When selecting Gala Show tickets one has to choose between "Friday", "Saturday" and "Sunday". Maybe giving the exact date (additionally) would be good to avoid confusion, because there are two weekends.
* (Maybe this is by design) There is no way to setup a password once the order page is closed. The link to sign up an existing email address could be added to the confimation mail.
* When I finish an order without beeing logged in, I am offered the possibility to set a password for my email address. Following this link, it sais "Reset password", maybe "Reset or initially set a password"? Just a thought...

# Bugs #
At least I think they are :)
* Let's say I want to order two Gala Show Tickets, one regular and one reduced price. [Products -> Gala Show Ticket -> Choose date (notice there is no drop-down for person at this stage)
-> add to cart -> <products], now the second Ticket: [Gala Show Ticket -> Choose a date (still no drop-down for person) and price is 25,00 € -> ok, add it anyway -> Shopping Cart ->Checkout this Cart -> add Purchaser (cannot enter Birthday) -> Save purchaser]. Now if I go back to the shopping cart I can edit the tickets and there is a dropdown for person, but the purchaser is greyed out (maybe because of missing Birthday, which could not be entered?) So there is no way to assign persons to tickets this way, nor to buy reduced Gala Show tickets. If I add persons to my person list via "My Persons" first, there is the possibility to assign Gala Show Tickets to the person and I can get the reduced price (although I also stumbled over #188), buth this is not obvious at all.
* I could not sign up to set a password after ordering without registration. After entering my email address in the "Reset password" form, I received an email, but the link to set the new password just brings me to a login page. Actually the complicated password reset link is replaced by https://preregpp.eja.net/user/login when I try to follow it.
* The "Terms and Condition" page is still empty, but you probably know that.

So much for today, I havn't tested all the features yet, but will continue to do so.

Best regards
Raimar

**Comment by smadamit** [comment]
Hi Raimer

Thanks a lot for your very useful feedback. I will split up your issue to some new ones.

cheers

**Comment by inbaz** [comment]
Very very cool! Thanks! I already fixed some minor things:
- main page text
- added My Person link to add Product page

Can you just redirect your password reset mail to andi@inbaz.org? I'd like to see what's happening. This link is valid for only two hours. Maybe I need a separate page with a more precise error message for what happened and not just redirecting to the login page. Maybe redirecting to /reset-password with an according error message would be more clearer.

**Comment by PiQuer** [comment]
I just forwarded the password reset mail, generated a moment ago, so it should be valid for full two hours.

**Comment by smadamit** [comment]
all text changes done apart from:

Main Page:
- There is a "." missing at the end of the sentence: You can take a look at the product list

Last step of checkout:
- In the "Purchaser" box last word: "aswell" -> "as well"

**Comment by smadamit** [comment]
@PiQuer 

Minor confusions
- "Verwendungszweck" is the correct field and "Kundenreferenz" does not work (it's a note for you I guess). I think this is a German issue? I'm not sure.
- It's solved by the Note: "You can edit person details with My Persons from the main menu." Have a look.
- I added the dates to the Gala-Show-Tickets
- profile/login etc. will be implemented after going live with the prereg.

**Comment by smadamit** [comment]
@inbaz  the only open todos in this issue:

## text changes

Main Page:
- There is a "." missing at the end of the sentence: You can take a look at the product list

Last step of checkout:
- In the "Purchaser" box last word: "aswell" -> "as well"

When I finish an order without beeing logged in, I am offered the possibility to set a password for my email address. Following this link, it sais "Reset password", maybe "Reset or initially set a password"? Just a thought...

**Comment by PiQuer** [comment]
Ok so the 403 when trying to log in is expected then...

One more thing, do we need such a fancy Cookie-Information? More and more websites have it, informing the user that cookies are used and why, this seems to be a legal issue in the EU.

**Comment by inbaz** [comment]
Fixed does two typos and added a basic cookie warning. Maybe we need to link that to the legal terms. Is in the legal terms a privacy policy included? Like what are we doing with the user information and when are they deleted?

**Comment by smadamit** [comment]
@inbaz Yes in the legal terms is a privacy policy included. With all we need.

OK, with that I think I close the ticket.
