### ISSUE TITLE
checkout buy now mysql-error

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#206]
tested in preregpp v0.2.38

File:
/var/www/preregpp.eja.net/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:66

Message:
An exception occurred while executing 'INSERT INTO users (username, email, displayName, firstname, surname, Country_id, password, hashKey, active, birthday, updated, created) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [null, "einradfrxxxxxxxxx", null, "ranz", "Hanswurst", 16, null, null, 1, "1977-03-10", "2015-03-17 21:39:34", "2015-03-17 21:39:34"]:

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'einradfrxxxxxxxxx' for key 'UNIQ_1483A5E9E7927C74'

(I censored the email-address)

**Comment by inbaz** [comment]
This may not happen. Can you please try if there is any chance to reproduce this problem?

**Comment by smadamit** [comment]
0.2.45

I reproduced and I think I know when the error occurs. Will be fixed with #135 But nevertheless I would fix the bug.

- put in a product and assign it to Max Müller with the email (test-email@test.de)
- checkout and create a new purchaser David Adams with the same email (test-email@test.de)
- at the last step: buy now you will get the error SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'test-email@test.de' for key 'UNIQ_1483A5E9E7927C74'

**Comment by inbaz** [comment]
What do you mean with fix the bug? The bug can only be fixed when I do not allow purchasing with an existing account when the user is not logged in.

**Comment by smadamit** [comment]
OK, I will retest after we fixed #135

**Comment by smadamit** [comment]
tested in 0.2.71 -> OK
