### ISSUE TITLE
payment/banktransfer enhancement

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#208]
v0.2.38

Two issues:
- feedback from user: numbered list instead of unordered list -> 1) setup password 2) Login 3) etc. Than it is clear that this is an ordered process
- maybe we should deactivate all links to profile, etc. which are currently not implemented

![image](https://cloud.githubusercontent.com/assets/1533081/6712123/3b391e92-cd8b-11e4-8c01-dbc1aa2c5571.png)

**Comment by inbaz** [comment]
I think I'll remove this part completely since there will be no login for purchaser.

**Comment by inbaz** [comment]
Does this version work for you?

**Comment by smadamit** [comment]
works for me
