### ISSUE TITLE
admin/payment-type/editBankTransfer/1 cutoff Explanation

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#210]
v0.2.39

The text of the explanation-field of the paymenttype form is cut off. Please increase the number of allowed characters.

**Comment by inbaz** [comment]
Please give an example that is cut off.

**Comment by smadamit** [comment]
explanation-field of bank transfer is too long:

SEPA Bank Transfer
Please make a SEPA bank transfer to the EJA bank account and don't forget to mention your order number in the reference.

SEPA: The Single Euro Payments Area (or "SEPA" for short) makes secure transfers between bank accounts anywhere in the Euro area possible.

Important note: Bank transfers from USA, Austra... [cut-off]

**Comment by smadamit** [comment]
I made the source code shorter. It works. I will retest later...

**Comment by smadamit** [comment]
v0.3.9
- I need more characters for long desc and explanation of the payment type. I guess it's limited in the database.
- do not just cut-off the text, but give a warning if the text is too long.

**Comment by inbaz** [comment]
check in 0.3.10 on preprod. If it's working I'll transfer it to prod.

**Comment by smadamit** [comment]
is working for "Explanation" but is not working for "Long Description".

**Comment by smadamit** [comment]
0.3.15 -> OK
