### ISSUE TITLE
handle EJA bank transfer fees

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#211]
There can be fees for the recipient which the participant needs to pay onsite. Let's find an easy to handle solution for both sides (seller and purchaser).

**Comment by smadamit** [comment]
@jackcaveman Do we have bank transfers from countries outside EU with fees till now?

**Comment by smadamit** [comment]
maybe related to #536 and #534

**Comment by smadamit** [comment]
@jackcaveman Do we have bank transfers from countries outside EU with fees till now?

**Comment by jackcaveman** [comment]
No fees at the moment. You will know for sure when you do the automatching and a payment comes up short.

**Comment by inbaz** [comment]
There have not been any fees for the recipient bank account at all, or not?

**Comment by jackcaveman** [comment]
We have only one payment fee with 5.00 EUR fee (XVPUY278)
Due to the many transactions we have 183.60 EUR (0.0015 EUR per
transaction) in the period 01-04 to 30-06.
The next period (july to sept I have to calculate)

**Comment by inbaz** [comment]
Hey Jasper,

can you check the fees on the bank account? Do we really need to implement a special function for that?

**Comment by jackcaveman** [comment]
It's not that much. Easier to put in on EJA running costs.

**Comment by inbaz** [comment]
@jackcaveman I would suggest to really put these fees into EJA running costs. Can we close this ticket?

**Comment by jackcaveman** [comment]
Sure
