### ISSUE TITLE
checkout buttons

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#215]
0.2.39

In the checkout steps some users were irritated. The proposal is to make it clearer. instead of:
- Save Purchaser -> continue Checkout
- Save Payment Type -> continue Checkout

I'm not sure if that's the best way...

**Comment by christianbross** [comment]
I like the "Save Purchaser", but if it's not clear enough, then how about:
"Save Purchaser, proceed Checkout", and
"Save Payment Type, proceed Checkout"
I know it's longer, but there is enough space for a long button anyway...

**Comment by smadamit** [comment]
0.2.48 -> I like it
