### ISSUE TITLE
product/add/5 add person link and person select box for non personalized products

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#217]
0.2.39

I think we should add the select box: "you need to assign this ticket to a person" and the link "add person to this list" to all product/add to non personalized products, even if there are no persons in the list.

Otherwise it's confusing for users:
- Rainer said: "Let's say I want to order two Gala Show Tickets, one regular and one reduced price. [Products -> Gala Show Ticket -> Choose date (notice there is no drop-down for person at this stage) -> add to cart -> Choose a date (still no drop-down for person) and price is 25,00 € -> ok, add it anyway -> Shopping Cart ->Checkout this Cart -> add Purchaser (cannot enter Birthday) -> Save purchaser]. Now if I go back to the shopping cart I can edit the tickets and there is a dropdown for person, but the purchaser is greyed out (maybe because of missing Birthday, which could not be entered?) So there is no way to assign persons to tickets this way, nor to buy reduced Gala Show tickets. If I add persons to my person list via "My Persons" first, there is the possibility to assign Gala Show Tickets to the person and I can get the reduced price (although I also stumbled over #188), buth this is not obvious at all."

@PiQuer the price can be selected after fixing issue: #177

**Comment by inbaz** [comment]
I added the select box to all products.

**Comment by smadamit** [comment]
tested in 0.2.44 -> OK
