### ISSUE TITLE
Improve VAT text in product add / edit page

### ISSUE THREAD

**Issue by christianbross** [inbaz/ers#218]
Version 0.2.39
in the product add or edit page (URL), there is the text
"prices do include VAT Italy VAT" 
--> change text
"All prices include VAT (Italy)" or keep it simple (for the future) and use
"All prices include VAT"

**Comment by inbaz** [comment]
The part italy VAT is configured through the admin panel. It's the name of the configured tax.

**Comment by smadamit** [comment]
I changed in admin panel. The text now: "prices do include Italian VAT"
