### ISSUE TITLE
Add "safety" confirmation dialog before resetting shopping cart

### ISSUE THREAD

**Issue by philip-n** [inbaz/ers#219]
When a person shall be deleted on the "My Persons" page, there is a "Do you really want to delete this person" confirmation first.

I'd propose to add a similar one to the "Reset shopping cart and My Persons list" button on the shopping cart page. Can be really simple, just a "This will empty your shopping cart and clear your list of persons. Do you want to continue? [red button Yes] Cancel"

Or really fancy with an additional list showing everthing that will be deleted (persons and items in shopping cart).

I'd say that this is not absolutely necessary, but as there is such a dialog for deleting persons, I kind of expected the same inside the shopping cart.

**Comment by inbaz** [comment]
added in 0.2.64

**Comment by smadamit** [comment]
tested in 0.2.64 -> OK
