### ISSUE TITLE
Blank page when adding a ticket for a non-existing person

### ISSUE THREAD

**Issue by philip-n** [inbaz/ers#220]
Very theoretical case, but hey :-)

1. Create a person and place a personalized ticket in the shopping cart
2. Open the product page of a personalized product (person will be pre-selected)
3. In a new tab, go to "My persons" and delete person
4. In the first tab, click on "add to cart"

Ta-daa! Blank page.

Just adding this here for completeness' sake, don't know if it's currently worth being looked into.

**Comment by inbaz** [comment]
Please recheck. For me the system did simply nothing at the moment.

**Comment by philip-n** [comment]
Now the system shows the product selection screen instead of blank screen. Works for me.
