### ISSUE TITLE
Show real credit card fees in checkout process

### ISSUE THREAD

**Issue by philip-n** [inbaz/ers#223]
On the "select payment type" screen, calculate the credit card fees based on the current shopping cart and directly display them in the credit cart info section.

**Comment by inbaz** [comment]
Where exactly is this credit card info section you mean? I think this can be done relly easy.

**Comment by philip-n** [comment]
With credit card section I mean the short description next to "Credit Card" on the Payment Selection screen in shopping cart (https://preregpp.eja.net/order/payment).

Would be nice if it said something like "Payment by credit card will cost an additional xx€ in credit card fees." where xx has been calculated as 0.0265 * (amount of goods in shopping cart) €.
--> People directly see the costs for their credit card purchase.

**Comment by inbaz** [comment]
done in 0.4.47
