### ISSUE TITLE
Add help page

### ISSUE THREAD

**Issue by philip-n** [inbaz/ers#224]
Write a general help page that gives a short overview of how ordering works.

**Comment by inbaz** [comment]
David mentioned to create a youtube video on how to order a ticket.

**Comment by smadamit** [comment]
David will ask someone to create such a help-page. I suggest to do that after the text-changes from philip-n

**Comment by philip-n** [comment]
Didn't manage to go through the mails today (sorry!), but wrote a short overview on the system. Would propose to add it as a general help section (see above). In addition, I think it would be great to have a step-by-step walkthrough (with screen shots?). E.g. show how one orders week tickets for two persons plus one day ticket and one gala show ticket for a third person who comes visiting for a day.

I prefer such a walkthrough in text and pictures (rather than a video), but maybe I'm old-fashioned that way :-)


## Registration overview

Here is a very short introduction on how to register for EJC 2015. And how to order additional goodies like t-shirts or more gala show tickets, if you want :-)

It's quite easy:
1. Select a product, for example an EJC 2015 week ticket
2. Provide the necessary information for your product (e.g. for the week ticket, we need the name and age of the juggler who will use the ticket)
3. Add it to your shopping cart
4. Repeat the previous steps as often as you like. If you want to buy three more week tickets for three friends, just add them to your shopping cart one after another.
5. When you have added everything to your shopping cart, check it out: First tell us your contact information ("purchaser") and how you want to pay, then confirm your order. That's it!
[6. If you have selected to pay by bank transfer, please make sure that your payment arrives within 14 days. Hint: Best make the transfer right now!]

We will send you a confirmation mail with all information as soon as we receive your order. When we receive the payment, we will send you a second mail that includes PDF documents with e.g. your tickets or a voucher for a t-shirt.
Please note that we will only send you a digital confirmation via mail. You will receive the physical goods, like a badge or a t-shirt, when you arrive and check in at EJC 2015 in Bruneck.

## Personalised items
Personalised items are items that are assigned to a specific person. Many items **must** be personalised, for example each week ticket must belong to a specific juggler. For some other items, you can **choose** to personalise them, so they will be handed out to the right person. For example, if you order five t-shirts, you can assign each one to a specific person to avoid confusion later ("Is this mine or yours?").

## Persons in your order
To make it easy for you to keep track of the persons in your order, we have added the "My Persons" button in the menu. It takes you to an overview of all persons for which you have entered any information. Here you can view and edit their details, e.g. correct a name that you have accidentally misspelled.

**Comment by philip-n** [comment]
Ping @smadamit @inbaz for acception / rejection :-)

**Comment by inbaz** [comment]
Except for the T-Shirts which needs to be completely striked out this is a very cool idea. T-Shirt will be selled through a separate shop system. You make it easy to generate the screenshots to be able to make them again easily because there are some user interface changes right now.

**Comment by philip-n** [comment]
Bonus question: In the old days (TM), when prereg closed 6 weeks before EJC, there was some text by EJA that detailled how and when tickets could be cancelled and which refund was possible.
Out of my head I think it was something like:
* Full refund until prereg closes
* Refund on a case-by-case basis after prereg closes and before EJC begins
* No refund (?) after EJC

Not sure about the exact content and if it was really enforced, but I guess it would be good to have this kind of information somewhere visible.

What do you think? And is there a guideline for how to handle it this year?

@jackcaveman, @inbaz, @smadamit

**Comment by philip-n** [comment]
Anything for @inbaz.T-Shirts are OUT!

Bonus question was answered via mail (information will be included in the terms and agreement).

Also added the last paragraph concerning refunds. Again @jackcaveman , @smadamit : Object if you want!


## Registration overview

Here is a very short introduction on how to register for EJC 2015. And how to order additional goodies like more gala show tickets, if you want :-)

It's quite easy:
1. Select a product, for example an EJC 2015 week ticket
2. Provide the necessary information for your product (e.g. for the week ticket, we need the name and age of the juggler who will use the ticket)
3. Add it to your shopping cart
4. Repeat the previous steps as often as you like. If you want to buy three more week tickets for three friends, just add them to your shopping cart one after another.
5. When you have added everything to your shopping cart, check it out: First tell us your contact information ("purchaser") and how you want to pay, then confirm your order. That's it!
[6. If you have selected to pay by bank transfer, please make sure that your payment arrives within 14 days. Hint: Best make the transfer right now!]

We will send you a confirmation mail with all information as soon as we receive your order. When we receive the payment, we will send you a second mail that includes PDF documents with your e-tickets.
Please note that we will only send you a digital confirmation via mail. You will receive the physical goods like your badge when you arrive and check in at EJC 2015 in Bruneck.

## Personalised items
Personalised items are items that are assigned to a specific person. Many items **must** be personalised, for example each week or day ticket must belong to a specific juggler. For some other items, you can **choose** to personalise them, so they will be handed out to the right person. For example, if you order additional gala-show tickets, you can assign each one to a specific person to avoid confusion later ("Is this mine or yours?").

## Persons in your order
To make it easy for you to keep track of the persons in your order, we have added the "My Persons" button in the menu. It takes you to an overview of all persons for which you have entered any information. Here you can view and edit their details, e.g. correct a name that you have accidentally misspelled. 

## Late payments, cancellation of orders, transfering of tickets
If we don't receive your payment within 14 days after your order, we will have to cancel your order. Sorry. To avoid that, best pay immediately!
If you have already paid your order and received your e-ticket, but for some reasons cannot attend EJC 2015, the best thing to do is find another juggler who can take over your ticket. If you want to transfer your ticket to another person, please let us know at **??? can they do that in "my orders"? shall they write a mail to prereg@eja.net?** .
If there is no-one to take over your order, you can find the guidelines for refunds in our terms and agreement document **TODO: link to document**

**Comment by philip-n** [comment]
See also #198.

**Comment by smadamit** [comment]
If you have already paid your order and received your e-ticket, but for some reasons cannot attend EJC 2015, the best thing to do is find another juggler who can take over your ticket. When you have done that, it is very important that you let us know who the ticket shall be transferred to by ??? can they do that in "my orders"? shall they write a mail to prereg@eja.net? .

-> yes it will be a feature in the login-area of the purchaser -> But as long we have not implemented this feature I would not mention it in the help.

Apart from that, I like it.

**Comment by philip-n** [comment]
## Registration overview

Here is a very short introduction on how to register for EJC 2015. And how to order additional goodies like more gala show tickets, if you want :-)

It's quite easy:
1. Select a product, for example an EJC 2015 week ticket
2. Provide the necessary information for your product (e.g. for the week ticket, we need the name and age of the juggler who will use the ticket)
3. Add it to your shopping cart
4. Repeat the previous steps as often as you like. If you want to buy three more week tickets for three friends, just add them to your shopping cart one after another.
5. When you have added everything to your shopping cart, check it out: First tell us your contact information ("purchaser") and how you want to pay, then confirm your order. That's it!
[6. If you have selected to pay by bank transfer, please make sure that your payment arrives within 14 days. Hint: Best make the transfer right now!]

We will send you a confirmation mail with all information as soon as we receive your order. When we receive the payment, we will send you a second mail that includes PDF documents with your e-tickets.
Please note that we will only send you a digital confirmation via mail. You will receive the physical goods like your badge when you arrive and check in at EJC 2015 in Bruneck.

## Personalised items
Personalised items are items that are assigned to a specific person. Many items **must** be personalised, for example each week or day ticket must belong to a specific juggler. For some other items, you can **choose** to personalise them, so they will be handed out to the right person. For example, if you order additional gala-show tickets, you can assign each one to a specific person to avoid confusion later ("Is this mine or yours?").

## Persons in your order
To make it easy for you to keep track of the persons in your order, we have added the "My Persons" button in the menu. It takes you to an overview of all persons for which you have entered any information. Here you can view and edit their details, e.g. correct a name that you have accidentally misspelled. 

## Late payments, cancellation of orders, transfering of tickets
If we don't receive your payment within 14 days after your order, we will have to cancel your order. Sorry. To avoid that, best pay immediately!
If you have already paid your order and received your e-ticket, but for some reasons cannot attend EJC 2015, the best thing to do is find another juggler who can take over your ticket. When you have done that, it is very important that you let us know who the ticket shall be transferred! Please contact  prereg@eja.net in this case. If there is no-one to take over your order, you can find the guidelines for refunds in our [ERS terms and agreement document](https://preregpp.eja.net/info/terms).

**Comment by philip-n** [comment]
[The above is the currently "final" version, I guess]

**Comment by inbaz** [comment]
Added help page on /info/help in 0.2.67, where should to link to this page be placed?

**Comment by philip-n** [comment]
Suggestion: Replace the "Login" Button by "Help" (as per #287)? Otherwise next to it.

Bonus To Do for @inbaz: Correct the help page title to e.g. "ERS help page".

**Comment by smadamit** [comment]
philips proposal was
- add on the starting page "If you need any help, just click the big ? in the upper right corner!" just after "Please also note that the price of all tickets increases as EJC comes closer. Visit www.ejc2015.org/registration to see all ticket prices at a glance."
- link to /info/help with a big ? in the upper right.

**Comment by inbaz** [comment]
Added the help menu item. Is the Question mark ok or should it be "Help"? 0.2.68

**Comment by philip-n** [comment]
Can't see either? Have [Ctrl] + [F5] refreshed and version says 0.2.68, but no "?" or "help" is visible in the menu.

**Comment by smadamit** [comment]
For me "Help" is better. Change this and close the ticket.

**Comment by inbaz** [comment]
fixed in 0.2.71
