### ISSUE TITLE
product/add/1 alias "Logger" was requested

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#225]
0.2.43:

- index
- product/index
- product/add/1
- participant/index
- product/index
- product/add/1 -> error

File:
/var/www/preregpp.eja.net/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php:544

Message:
An alias "Logger" was requested but no service could be found.

**Comment by inbaz** [comment]
Fixed in one of the last versions.
