### ISSUE TITLE
language selection for emails and etickets

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#226]
0.2.44: At the moment there exists no translation module. We will start going live in English and maybe the site will stay in English till the end. I think that's OK.

But on the etickets and the emails is very important text for the participants. Maybe we should provide translations for them in French, Spain, German, etc. From the coding side it's relatively easy to implement. And the translation is a job we can delegate.

How should the code decide in which language the emails and the etickets are sent? Do we need a language selection for this? What about a resend feature with language selection (just a link in the very beginning of the email -> send the email in another language)? Or should we stay completely in English till the end?

**Comment by inbaz** [comment]
We need to talk to the ejc core team. If they're fine with an english only system I'm too. We do have many tasks to do until the complete EJC registration system is basically fully functional therefore I'm happy for every task which doesn't need to be implemented now.

**Comment by smadamit** [comment]
We discussed via phone... So it's your turn.

**Comment by inbaz** [comment]
Uff, what you please document what was the desicion on that? Maybe I start to implement the translation module for onsite registration. Do we move this ticket into second life?

**Comment by smadamit** [comment]
You have implemented links alla order/view/39K48VKV3KNXM... You use a hash to associate the order overview to the order in the database. The issue here would be. Just put a short note at the very beginning of every email like: "You can request this email in your language: link". The link should be something like request/email/39K48VKV3KNXM... The hash identifies the order in the database. Then we need the new page request/email with the short note: "The request of emails in different languages is not yet implemented. Please come back later."

The implementation of the request/email can be done in milestone:SecondLife. The link in the email would be nice if we have it with going live.

**Comment by inbaz** [comment]
Add the site where the user can insert email and language and add the link to top of confirmation mail.

**Comment by inbaz** [comment]
http://dev.ers.inbaz.org/order/email/7WPWX8CX35RN4PRCP9K1M4X3MF2YCU20 Is this what you think it should be?

**Comment by smadamit** [comment]
Yes!

Two enhancements:
- "Other languages" -> "resend your emails in another language"
- Add some other languages. Here just some Google Translations (fr, es, it):
 - Désolé, cette fonction ne est pas encore mis en œuvre,. Se il vous plaît revenir plus tard.
 - Lo sentimos, esta función no está implementada, aún. Por favor, vuelva más tarde.
 - Siamo spiacenti, questa funzione non è ancora implementata,. Si prega di tornare più tardi.

And don't forget the link in the order confirmation mail at the very beginning of the text.

**Comment by inbaz** [comment]
Please recheck in 0.2.71 and are there some language nerds around who can check the skills of the google translator?

**Comment by smadamit** [comment]
perfect. I close the ticket. And I will ask some people for translations...
