### ISSUE TITLE
credit card validation

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#227]
0.2.44

please validate credit card form:
- secure code -> 3 digits
- date -> in future

**Comment by PiQuer** [comment]
Tested with card holder "Raimar Sandner", secure code 123 and date 01 2016.

  Mastercard 	5105105105105100 -> does not work
  Mastercard 	5555555555554444 -> does not work
  Visa 4111111111111111 -> **works**
  Visa 	4012888888881881 -> does not work
  Visa 	4444333322221111 -> does not work
  American Express 	378282246310005 -> does not work
  American Express 	371449635398431 -> does not work
  Diners Club 	38520000023237 -> does not work
  Diners Club 	30569309025904 -> does not work
  Discover 	6011111111111117 -> does not work
  Discover 	6011000990139424 -> does not work
  JCB 	3530111333300000 -> does not work
  JCB 	3566002020360505 -> does not work
  Maestro 	6400051234567895 -> does not work
  Maestro 	6769271234567894 -> does not work
  Solo 	6767676767676767671 -> does not work
  Solo 	6767622222222222222 -> does not work
  Carte Bleue 	5555555555554444 -> does not work
  Dankort 	5019717010103742 -> does not work

So only Visa 4111111111111111 works :)

**Comment by smadamit** [comment]
validate type of credit card:
- only Mastercard and Visa are accepted

There should be a note that we only accept Mastercard and Visa!

**Comment by inbaz** [comment]
I'm not able to check the form. This form directly sends the data to the ipayment system. Checking the form means I have the credit card data in ers which is a nogo because it's a very big security issue. Therefore there are these two possibilities:
1. the payment works and everything is fine
2. the payment fails and the user needs a useful error message what he/she can do next, i.e. restart the credit card payment or change the payment type or maybe I can get some detailed info from the ipayment system onto this error page.

What do you expect?

**Comment by smadamit** [comment]
You have implemented in 0.2.46:
- user gets back from ipayment the reason of the error after a failed credit card payment. I will test it.

What I suggest:
- set maxlength = 3 and maybe type digit of the secure input field
- give a short hint that we only accept Visa and Mastercard

Note for afterEJC:
- nice to have for future: let's validate all fields with javascript before submit to ipayment-server

**Comment by inbaz** [comment]
added maxlength of 3 for the security code and added a dropdown field to select the credit card type. I can turn off the credit card checking so the selected credit card type needs to match the given credit card number. Should I do that?

**Comment by smadamit** [comment]
Thanks

My opinion: If someone selects Visa and enters a Mastercard number, there should be no error message, as long as the credit card number is valid and the payment is successful. So if I understand you correctly, please turn of the credit card type checking.

**Comment by inbaz** [comment]
I have set this option, please check if this is working. Select MasterCard and insert a valid VISA Card number. The transaction should work correctly.

**Comment by smadamit** [comment]
0.2.48

tested: "Select MasterCard and insert a valid VISA Card number. The transaction should work correctly." -> OK
