### ISSUE TITLE
credit card: we are not able...

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#228]
0.2.44

Tried to pay with credit card. tested two numbers from http://hilfe-center.1und1.de/ipayment-c82678/bedienung-c82775/kreditkartennummern-zum-testen-von-ipayment-a784577.html
- Mastercard: 5105105105105100 -> error: "we were not able to ..."
- Visa: 4111111111111111 -> it works

**Comment by inbaz** [comment]
Just tested, worked. I will have a look at the email what settings were given and what was the error why the payment was not working.

**Comment by inbaz** [comment]
first try: 'The Expdate (0115) is invalid'
second try: 'CVV2-Code for Cardtyp 1 invalid'
third try: 'The given credit card number is not valid.'
on the fourth try it has worked.

You can have a look at the error messages yourself it's already implemented on the order detail page.

**Comment by smadamit** [comment]
@inbaz 

retested 0.2.45:
- Mastervcard 5105105105105100 secure coe 123 expdate 01-2017 -> it works

But why does it recently failed? See also the failed tries of Raimar: https://github.com/inbaz/ers/issues/227#issuecomment-83482809 (2 x Mastercard and 2 x Visa errors)

I will do further retests.

And by the way can you please inform the user of the reason why the credit card payment failed?

**Comment by smadamit** [comment]
I checked the errors in admin panel. Most are clear.

What is about this one? Is it an issue we have to think about or a regular error? I don't know.

```
 stdClass::__set_state(array(
   'trxuser_id' => '12622',
   'trx_amount' => '12243',
   'trx_currency' => 'EUR',
   'trx_paymenttyp' => 'cc',
   'shopper_id' => 'FA48HR97',
   'addr_name' => 'Raimar Sandner',
   'csrf' => '79bea643712058e773f107568fe4136b-f233f87ff01dd49363609f7d8041e038',
   'submit' => 'pay now',
   'trx_typ' => 'auth',
   'ret_errorcode' => '3003',
   'ret_fatalerror' => '0',
   'ret_errormsg' => 'The given transaction already exists in the system. Maybe turn off the strict-id-check.',
   'ret_additionalmsg' => 'Transaction already processed, but data don\'t match with original transaction with this refernce-ids.',
   'ret_ip' => '138.232.67.72',
   'redirect_needed' => '0',
   'trx_paymentmethod' => 'VisaCard',
   'trx_paymentdata_country' => 'US',
   'ret_status' => 'ERROR',
   'ret_url_checksum' => 'e0382722484ea838a20dfc08262dac5b',
))                
```

**Comment by inbaz** [comment]
I think this is a payment which simply was sent twice. I'm giving the iPayment system the order id to match the payment. If there is a second payment after there was a successful payment an error is generated. For this type of error I need to know what has been done before.

**Comment by smadamit** [comment]
So to clarify.

If you implement:
- orders where the credit card payment was successful -> status is set to paid
- the user will not be able to pay again

Then this error could not appear again. Am I right?

**Comment by inbaz** [comment]
Yes for my understanding this will be the way.
