### ISSUE TITLE
email link order details

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#229]
the link in the email to your order details is nice.

If the order status is: paid, please deactivate the link "Start payment with Credit Card" in order/view/R2KUFWYR...

**Comment by inbaz** [comment]
I have already implemented such a function but I need we need to read through the text and maybe add a function to resend the eTicket PDFs.

I set this order from you to paid.

https://preregpp.eja.net/order/view/NK59HWX38K3HN59YKXKA4ANM1UF3U661

**Comment by smadamit** [comment]
OK, nice. Just to understand. I ordered and paid by credit card: 3F947C52

But the link to pay is active in https://preregpp.eja.net/order/view/PWX1W2P8GHXWX1KM9APC65M9YD4P6287

Is it because you do not have implemented yet the function to set the status to "paid" after successful credit card payments?

**Comment by inbaz** [comment]
Yes, I'm working on that, but this issue is solved with that.
