### ISSUE TITLE
403 Forbidden when trying to log in with username/password

### ISSUE THREAD

**Issue by PiQuer** [inbaz/ers#230]
I opened this issue based on this comment from Andi:
> das Einloggen sollte mit diesem gesetzten Passwort auch funktionieren,
> nur die Funktionen nach dem Login sind noch etwas beschränkt.

I ordered with the email "disp.reg.ejc@typename.de" and set the password "ejc2015". When I try to log in, I get a "403 Forbidden", after that no other page is available anymore (always 403). Only way to recover is to delete all preregpp.eja.net cookies.

On the other hand, when I enter a wrong password, I get "Authentication failed. Please try again." and everything still works. So the password seems to be set correctly in the database.

**Comment by smadamit** [comment]
depends on #57

**Comment by inbaz** [comment]
Please recheck, I have in mind that there was a change according to this. Maybe we need to explicitly stop users from accessing some pages.

**Comment by PiQuer** [comment]
Still the same with "disp.reg.ejc@typename.de" and password "ejc2015".

**Comment by smadamit** [comment]
For the moment all profile/login-links are removed. So let's have a look to this ticket again when #57 is implemented.

**Comment by inbaz** [comment]
This is fixed because now the user role is set to "user" when a password is set.
