### ISSUE TITLE
transfer config from preprod to prod

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#232]
please transfer the database (recent admin panel config) of preprod to the prod-server.

**Comment by inbaz** [comment]
I copied the configuration from preprod to prod, please check at prereg.eja.net it's password secured with the same passwords as for preprod.

**Comment by smadamit** [comment]
You copied not the last recent version of the config. Can you retry or should I transfer manually?

**Comment by inbaz** [comment]
Ok, next try. I did a complete cleanup and reimported the configuration of preprod. Can you please check again if you can find any errors in the configuration?

**Comment by smadamit** [comment]
I checked. At a first glance it seems OK.

Question: If I change the config, should I do it from now in preprod and in prod simultaneously, or only in preprod and you transfer it by script to prod? I guess it's not much effort for you to do so?

**Comment by inbaz** [comment]
It is more effort, but with every transfer the transferscript is getting better and better. We need this script to be able to easily transfer prod to preprod if there are any major problems, so if you need the configuration in prod, let me know and I'll transfer the config. It's about a quater hour every time, including script enhancements.

**Comment by smadamit** [comment]
OK, I will do all changes in preprod and will ask you if we need to transfer to prod.

It's pretty sure that there will be no price changes. I would like to set Cent prices in preprod for credit card testing. Is it possible, that you improve your script in a way that everything is transferred, but the prices in prod leave untouched. Would be great.

**Comment by inbaz** [comment]
That should be possible. Just give me this ticket back if a prod update is needed.

**Comment by smadamit** [comment]
I checked again. 2 issues:
- you transferred all users. But we only need me, christian, jasper
- you do not transfer the country-order

**Comment by smadamit** [comment]
And don't forget: exclude prices in your transfer script.

**Comment by inbaz** [comment]
Data was imported. Please check imported data.

Week Ticket without hyphen, but Gala-Show-Ticket with hyphens. Would be better to do it the same way.

**Comment by smadamit** [comment]
@inbaz  low prio, since I could do it manually: country-sorting is not transferred. Apart from that it seems to work.

**Comment by smadamit** [comment]
I had some last changes. I hope that was the last iteration. Can you please transfer again. In best case with the country-order-table.

**Comment by inbaz** [comment]
Please check again.

**Comment by smadamit** [comment]
@inbaz  OK it works.

If there are new changes (I hope not) I will do it from now on https://prereg.eja.net

Can you kick out all users apart from me, jasper, christian, you. Your script should not transfer users. We have to clarify that issue by phone.
