### ISSUE TITLE
payment type text

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#233]
@inbaz and @philip-n

I changed the text of payment type bank transfer and credit card. There are some questions and I need feedback if you agree.

## 1. long description and explanation -> same text

I decided that the "long description" and "explanation" in the admin panel is the same. The "long description" is displayed at the info-site of the paymenttypes info/payment/2 and the explanation at the end of the checkout order/checkout. I think we should display exactly the same text for both cases.

## 2. text for bank transfer

This is my new text for the banktransfer. Do you like it?

![bank-transfer](https://cloud.githubusercontent.com/assets/1533081/6739723/029af72c-ce7b-11e4-9c63-4bb99fe1d723.png)

## 3. text for credit card

Do you like the credit card text:

![credit-card](https://cloud.githubusercontent.com/assets/1533081/6739745/2ade5364-ce7b-11e4-9c28-48d091032361.png)

## 4. suggestion

At the moment if you choose the payment type in the checkout you get the two options with title and short description. With the link "more info..." you get the infopage of the payment type with the long description.

![payment-type-choose](https://cloud.githubusercontent.com/assets/1533081/6739794/880ab8fc-ce7b-11e4-84bb-e3e6c0a4b3c6.png)

I would suggest, that you get:
- instead of title + short description 
- title + long description. And just leave the link to the infopage, we don't need it. And a border around the payment options like it is the case for the purchaser choose.

![payment-type-choose-new](https://cloud.githubusercontent.com/assets/1533081/6740093/aeb34ada-ce7d-11e4-87dd-14edb6f03e38.png)

**Comment by inbaz** [comment]
to 1.: in this case maybe that fits, but my opinion is that the explanation text is too long, nobody will read that much text. I think this should be shorter and the full descriptions fits in the long description
to 2: I don't know if this is 25 Euro fees or maybe 30 Euro so the conclusion up to 25 Euro is maybe wrong. I would just tell the purchaser in clear short words that he/she is responsible for the fees.
to 3: I like the text of the credit card payment it's short and there are all needed information.
to 4: again the argument that less people will read this information because it's too much text.

@smadamit I'll send you the source where I got the idea for the short, more info and long description from.

**Comment by philip-n** [comment]
I don't see the longer texts as too problematic. People who wouldn't have clicked the more info button will probably skip the text; people who would have clicked will also read a slightly longer text.

I'd propose slightly shorter version for bank transfer, though, that highlights that SEPA transfers are free within SEPA countries:

"Payment via SEPA bank transfer to the EJA bank account. Transfers within the [Single Euro Payments Area (SEPA)](https://www.ecb.europa.eu/paym/retpaym/paymint/sepa/html/index.en.html) are free (there are no fees for the transfer).
Important note: Bank transfers from non-SEPA countries such as USA and Australia can become quite expensive. You are responsible for paying the transfer fees, so please check with your bank first. For non-SEPA countries, paying by credit card might be cheaper."

**Comment by inbaz** [comment]
Changed in 0.2.64

**Comment by smadamit** [comment]
tested in 0.2.64 -> OK

**Comment by philip-n** [comment]
Sorry for re-opening, but: I'd strongly advise to include the information that the SEPA transfer is free (see text proposal in my last comment). Currently, the text only says that they are very expensive from outside sepa but doesn't mention their cost inside SEPA area. If you disagree, just close again!

**Comment by smadamit** [comment]
@philip-n Can you verify that's really free. As far as I know it's normally free, but there can be fees. Depends on the bank institute. What about: "mostly free, do not cost more than normal transfers inland, depends on bank institute" -> Have you a new proposal?

**Comment by philip-n** [comment]
Ouch! Banks actually can charge for the transfer, they just can't charge differently for national vs. SEPA-payments:
"(10) This Regulation does not affect the possibility for institutions to offer an all-inclusive fee for different payment services, provided that this does not discriminate between cross-border and national payments.
(http://eur-lex.europa.eu/legal-content/EN/ALL/?uri=CELEX:32001R2560)"

My bad, sorry for the confusion. You learn something new every day...

Proposal: 

**"Payment via SEPA bank transfer to the EJA bank account. Bank transfers within the [Single Euro Payments Area (SEPA)](https://www.ecb.europa.eu/paym/retpaym/paymint/sepa/html/index.en.html) do not cost more than national bank transfers (mosty free, check with your bank for details).
Important note: Bank transfers from non-SEPA countries such as USA and Australia can become quite expensive. You are responsible for paying the transfer fees, so please check with your bank first. For non-SEPA countries, paying by credit card might be cheaper."**

**Comment by smadamit** [comment]
@philip-n  OK, thanks for your text proposal. It's done, see: order/payment
I'm using the wikipedia link: https://en.wikipedia.org/wiki/Single_Euro_Payments_Area
