### ISSUE TITLE
week ticket from 0-6 does not include a gala show ticket

### ISSUE THREAD

**Issue by inbaz** [inbaz/ers#235]
How do we solve that problem?

One way could be to link the agegroup in the database model to the productpackage to be able to set subproducts for either a full product or be able to set subproduction for special agegroups.

Another way would be to strike out tickets which do not cost anything. The information how many people are onsite is nice but not that important. Is there another feature where we could use this info? There is the disclaimer and the u16 formular but for children who do not pay anything we can just provide these formulars online, or not?

**Comment by smadamit** [comment]
week tickets for 0-6 will include gala show. See emails...
