### ISSUE TITLE
Personalised Week tickets end up under "further items"

### ISSUE THREAD

**Issue by jackcaveman** [inbaz/ers#237]
The "Person" dropdown list is missing from the product detail page.
You can still click the "add person" link and enter details, but the ticket will be added to "further items".

**Comment by jackcaveman** [comment]
preregpp v0.2.48

**Comment by inbaz** [comment]
Can you please retest in 0.2.49?

**Comment by smadamit** [comment]
tested in 0.2.50 -> OK

**Comment by jackcaveman** [comment]
tested in prerpegpp v0.2.54 -> NOT OK
When I go the the Cart the Ticket is assigned to a person. When I then proceed checkout and select banktransfer the ticket is "unassigned". Also in the email and the permalink. e.g. https://preregpp.eja.net/order/view/MDGVG6U9AR1RV281N2KPHN86W53AUH44

**Comment by jackcaveman** [comment]
Retested with a different email address -> OK
So I seems the bug is caused by using an email address which has an account in the ERS.

**Comment by inbaz** [comment]
https://preregpp.eja.net/order/view/KVY9C8A1PWRV7VU7WHGKG8XYVDKW7R22 For me this is working.

Please try again, I changed your first and surname in database on preprod. Maybe this solves the problem. If so, this will not be a problem and is fixed, because registration is turned off, therefore we'll only add users with first name and surname.

**Comment by smadamit** [comment]
Have a look to your old order: https://preregpp.eja.net/order/view/MDGVG6U9AR1RV281N2KPHN86W53AUH44

There was the error? Now it is assigned to you Jasper Verbree. I think this is fixed because Andi added your name to your account in the database.

**Comment by inbaz** [comment]
@jackcaveman Can you please have a look at this? Is this fixed?

**Comment by jackcaveman** [comment]
tested preregpp v0.2.63 -> OK
sorry for the delay
