### ISSUE TITLE
status paid/unpaid

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#240]
0.2.48

Two test cases:

order 8N7K2W01 was succesfully paid by credit card:
- in admin/order the status is unpaid
- in order/view/F2567CXGU... the status is paid

order 27RHDP07 with credit card, but invalid number -> status should be unpaid:
- in admin/order the status is unpaid
- in order/view/F2567CXGU... the status is paid

**Comment by inbaz** [comment]
Please recheck, already ordered orders should be displayed correctly, too.

**Comment by smadamit** [comment]
tested in 0.2.57

I have to orders:
- 9R4PVF27 -> not paid, in admin panel staus is: paid and in https://preregpp.eja.net/order/view/Y63P232UAKVFUA7DW4NV3YFW52729N22 -> status is: not paid
- 29AYU599 -> paid, in admin panel staus is: paid and in https://preregpp.eja.net/order/view/39K48VKV3KNXMR2PD645VW8WXNMD5U11 -> status is: not paid

So not fixed yet.

**Comment by inbaz** [comment]
Please recheck again. The iPayment system is currently in test mode again.

**Comment by smadamit** [comment]
tested in 0.2.63, ipayment in testmode -> OK

@inbaz  should I retest with ipayment in productive mode?

**Comment by inbaz** [comment]
Yes, please.

**Comment by smadamit** [comment]
tested in 0.2.63, ipayment in productive mode -> OK
