### ISSUE TITLE
hint: prices will raise at...

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#243]
0.2.48

In product/add you have already implemented the hint: "This prices are valid until xx.xx.2015" Would be nice if you do the same for product/index. Maybe after: "Click on any item to add further information and place it in your shopping cart."

@philip-n  Maybe instead of "This prices are valid until xyz" -> "The prices will raise after xyz"? What do you think about that?

**Comment by philip-n** [comment]
What about "Please note that prices increase at the end of phase one (xx.yy.2015) and again at the end of phase two (xx.yy.2015)"? Otherwise text has to be modified each time a phase closes.

Side-question: What is the real cut-off date for phase one? ejc2015.org says 01.05.15

**Comment by smadamit** [comment]
The text can change automatically with changing deadline. I censored some text -> see my email.

**Comment by philip-n** [comment]
Automagical changes? Nice! 

Then I'd opt for "Please note that prices will increase on xx.yy.2015 when the first preregistration phase has ended!"

**Comment by philip-n** [comment]
@smadamit : I guess that the production system will correctly show "... until 01.05.2015" and that this is just something that will be changed in admin interface, correct?

**Comment by smadamit** [comment]
@philip-n Didn't get your question.

**Comment by philip-n** [comment]
Discrepancy between "01.05.2015" as phase end date (see ejc2015.org) and 06.05.2015 (as per your text above). Imho, ERS should say the same as ejc2015.org.

Question was if you can change that in admin or if it has to be changed by programming (e.g., Andi).

**Comment by smadamit** [comment]
can be set in admin panel yes

**Comment by inbaz** [comment]
I didn't even know that this sentence is above the product list. Do you think anybody is reading that? What exactly should I add?

@philip-n Keep in mind that there can be more than two prereg phases. Therefore sentences like "...when the first preregistration phase has ended!" is hard to generate generious.

I thought about displaying the whole price Matrix and set the active prices to black color an the others to grey. Maybe a smaller font size could help, too.

So, what's the exactly todo here?

**Comment by philip-n** [comment]
1) The sentence is not yet above the product list, but @smadamit proposed to add it ;-)

2) My first suggestion (good for all phases): "Please note that prices increase at the end of phase one (xx.yy.2015) and again at the end of phase two (xx.yy.2015)".

3) I understood @smadamit 's comment to mean that the text can change with the deadlines. If that's the case, the corresponding texts would be
"Please note that prices will increase on 01.05.2015 when the first preregistration phase has ended!" for the first phase and
"Please note that prices will increase on 01.07.2015 when the second preregistration phase has ended!" for the second phase.

4) To Do: Add the according sentence to the text above the product list.

**Comment by smadamit** [comment]
- I agree to philip for product/index Instead of first prereg or second prereg -> current preregistration phase (more generic)
- I like your idea inbaz: "I thought about displaying the whole price Matrix and set the active prices to black color an the others to grey. Maybe a smaller font size could help, too." for product/add/?

**Comment by smadamit** [comment]
Please display the deadline from the database, at the moment it's a fix text in the code. And please display the deadline as datetime: "2015-05-01 00:00:00"

**Comment by inbaz** [comment]
changed text and added time information in 0.2.67

**Comment by smadamit** [comment]
two comments:
- please select the deadline from database: "2015-05-01 00:00:00" At the moment it's a fixed text in the code.
- What do you think about adding the same information above the product list: product/index After "Click on any item to add further information and place it in your shopping cart."

**Comment by philip-n** [comment]
"raise" -> "increase"

Change text to "Prices will increase on %date%".

(Raise ist eher "etwas (anderes) erhöhen", increase kann sich selbst betreffen. Behaupte ich zumindest anhand von sehr eindeutigem Bauchgefühl.)

**Comment by inbaz** [comment]
done in 0.2.68

**Comment by smadamit** [comment]
still two comments:
- please select the deadline from database: "2015-05-01 00:00:00" At the moment it's a fixed text in the code.
- What do you think about adding the same information above the product list: product/index After "Click on any item to add further information and place it in your shopping cart."

**Comment by inbaz** [comment]
Why do you think it's a fixed text? It's:
<p class="small text-right">The prices will increase after <?php echo $deadline->getDeadline()->format('d.m.Y H:i:s'); ?></p>

What do you think about adding this hint on the right side above the product list?

**Comment by smadamit** [comment]
OK, sorted out by phone. One last todo left. Add the remark to product/index

**Comment by inbaz** [comment]
recheck in 0.2.71 .o0(Isn't there a collapse function for unneded comments?)

**Comment by smadamit** [comment]
collapse function for unneded comments -> would be nice. Or better a mark-function for the important ones. But I'm afraid no.

**Comment by smadamit** [comment]
@inbaz  collapse function for unneded comments -> would be nice. Or better a mark-function for the important ones. But I'm afraid no.

**Comment by smadamit** [comment]
0.2.71 -> OK
