### ISSUE TITLE
select productVariant -> default empty option

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#244]
Please add a default empty <option></option> and make the select field a mandatory field. With this we avoid that users select an option, which they don't want.

**Comment by inbaz** [comment]
Just to get it right: You mean i.e. the selection of the show for the gala show ticket, right? Just give the ticket back to me if that's right, then I know what you mean.

**Comment by philip-n** [comment]
If that's what @smadamit meant, then I totally support this. Especially in case of the gala-show-ticket it looks weird to be able to select "no gala-show-ticket".

**Comment by smadamit** [comment]
yes, it's implemented in 0.2.50 -> 2 bugs left: #249
