### ISSUE TITLE
Cookie explanation

### ISSUE THREAD

**Issue by philip-n** [inbaz/ers#245]
Find a nicer explanation page to link to in the title banner that asks for accepting cookies (cookiecuttr is written rather from the pov of the site-owner than user).

**Comment by philip-n** [comment]
Instead of linking to an external page, let's just have our own explanation (e.g. as a pop-up such as the "your item was placed in shopping cart notification"?).

"We use cookies on this site to be able to manage your shopping cart and the items that you want to order. Without cookies, we could not tell apart the (potentially many) jugglers that access this site and we would not be able to keep their shopping carts separated. Think of a cookie as something similar  to a marker that you put onto your nice white clubs: It helps you to find them again in a gym full of almost identical white clubs!

On a more technical note, [wikipedia] (http://en.wikipedia.org/wiki/HTTP_cookie) says about cookies:
"A HTTP cookie (also called web cookie, Internet cookie, browser cookie or simply cookie, the latter which is not to be confused with the literal definition), is a small piece of data sent from a website and stored in a user's web browser while the user is browsing that website. Every time the user loads the website, the browser sends the cookie back to the server to notify the website of the user's previous activity.[1] **Cookies were designed to be a reliable mechanism for websites to remember stateful information (such as items in a shopping cart)** or to record the user's browsing activity (including clicking particular buttons, logging in, or recording which pages were visited by the user as far back as months or years ago)." "

**Comment by inbaz** [comment]
Can you provide a text I can simply copy and paste to a site in the system, i.e. /info/cookie Linking to another cookie info site is very easy with this plugin used.

**Comment by smadamit** [comment]
@inbaz philip proposed a text for copy/paste. What do you need else?

**Comment by inbaz** [comment]
added explanation page and changed link. 0.2.67

**Comment by smadamit** [comment]
0.2.67 -> OK
