### ISSUE TITLE
Gala Show Ticket loses show time during "edit"

### ISSUE THREAD

**Issue by christianbross** [inbaz/ers#248]
preregpp.eja.net / Version: 0.2.50
I select a gala show ticket and a time for the show
I either assign it to a person, or keep it unassigned - it doesn't matter the bug happens in both cases
I go into the shopping cart
I click on "edit"
the drop down "select show" says "select select show" (low prio: why "select select" twice?)
after "save changes" the time for the gala show is lost

**Comment by smadamit** [comment]
it's the same issue as #249 -> I close this one.
