### ISSUE TITLE
Shopping cart text enhancement "select show / select day"

### ISSUE THREAD

**Issue by christianbross** [inbaz/ers#250]
preregpp.eja.net / Version: 0.2.50
in the shopping cart for gala-show-tickets it says "( select show: Saturday 21:00 (August 8) )"
I would recommend to remove the text "select show:" and just keep "(Saturday, 8th August, 21:00)"
similar for the day ticket is says "( select day: August 2 (Sunday) )"
I would recommend to remove "select day:" and just keep "(Sunday, August 2nd)"

**Comment by smadamit** [comment]
@christianbross a part of the text is from admin panel -> the productVariantValues -> select fields of gala show or day tickets. Should I change it to:
- gala: Saturday, 8th August, 21:00
- day ticket: Sunday, August 2nd

**Comment by christianbross** [comment]
@smadamit 
yes please: change "your part" of the text, please

**Comment by smadamit** [comment]
@christianbross Please recheck.

@inbaz please remove in the code "select show: " and "select day: " respectively -> email, order/index

**Comment by christianbross** [comment]
@smadamit I don't see any change. testing in https://preregpp.eja.net/order, version 0.2.53

**Comment by smadamit** [comment]
@christianbross 

it was "( select show: Saturday 21:00 (August 8) )"

now it should be "( select show: Saturday, August 8th, 21:00 )"

removing "select show: " have to be done by inbaz.

**Comment by christianbross** [comment]
ah - sorry - missed that - then it's indeed "half way finished" :-)

**Comment by inbaz** [comment]
So, this is only working for the week ticket. Why not just set the name of this variant to Show, then it will be:

( Show: Saturday, August 8th, 21:00 )

What do you think?

**Comment by smadamit** [comment]
OK, I can change it. But we will have "show"/"day" here instead of "select show"/"select day":

![screen](https://cloud.githubusercontent.com/assets/1533081/6789194/d8999ef2-d19e-11e4-9539-8fda14d399c6.png)

OK for you?

**Comment by christianbross** [comment]
sounds OK for me. Let's do it.

**Comment by smadamit** [comment]
0.2.56

now we have:
- Day Ticket ( day: Wednesday, August 5th )
- Gala-Show-Ticket ( show: Saturday, August 8th, 21:00 )
