### ISSUE TITLE
question to price change in admin panel

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#256]
I changed the prices in admin panel. As you can see the changes affect the items of Tim, but not the further items:

![question](https://cloud.githubusercontent.com/assets/1533081/6783506/4c1a0012-d17a-11e4-8dfe-687cc7588706.png)

That's strange. But not a real problem. But it seems you handle the item of personalized ones and the rest in a different way.

**Comment by inbaz** [comment]
Yep, on displaying the order index I recheck the prices and if they are not correct according the person, I correct them. For the further items I do not have the information in the item, which agegroup was used, therefore I'm not able to recheck this price at the moment.

**Comment by smadamit** [comment]
OK very good!
