### ISSUE TITLE
user have to choose selections explicitly

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#258]
0.2.53

Nice to have, but I think it is a good idea that the user has to choose any selection of the products explicitly. So if you go to gala show ticket the behavior should be:
- This ticket belongs to -> empty selection is preselected
- select show -> empty selection is preselected
- Agegroup -> no price agegroup is selected

If the user clicks "Add to card" the system should give a validation error like:
- you have to select a person or select an agegroup
- you have to select a show date

**Comment by inbaz** [comment]
Please recheck in 0.2.55

**Comment by smadamit** [comment]
first step works -> all select fields are empty by default. But there is no validation. I can add a galshow into the card with no agegroup selected and no show date selected.

**Comment by inbaz** [comment]
added warning message when not all data are present

**Comment by smadamit** [comment]
tested in 0.2.64

two minor comments
- edit item -> the yellow warning is missing "Please complete the whole form to put this product into the cart."
- if you do not select a productVariant you get the yellow warning -> OK. It would be even better if there is a red validation error like you have implemented for agegroup "Value is required and can't be empty"

Very nice: With this issue the crucial part from #251 is fixed :-)

**Comment by inbaz** [comment]
Creating separate warnings for the variant values is not possible due to the way of implementation. I changed the color of the error to red and added the box to edit form.

Please check again.

**Comment by smadamit** [comment]
0.2.65 -> OK

**Comment by smadamit** [comment]
0.2.69

last case:
- product/add/1 -> product page of a personalized product. If there are some persons in the my person list, these persons are in the select field. The first person is preselected. My suggestion would be: first option of the person list is an empty option -> you have to choose the person explicitly.

**Comment by inbaz** [comment]
I added a disabled value "select a person" to the select box.
