### ISSUE TITLE
test sending of emails

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#27]
Payment/banktransfer/email: for some cases I got the email, in some cases not. 2 out of 5.

**Comment by inbaz** [comment]
Could you please retest and tell me what you're doing? I think you are accessing a page which sends the email but on the second time the needed session container is deleted. Therefore the needed data for the email is not there anymore.

**Comment by smadamit** [comment]
test v0.2.7:
was logged out. put in a week ticket. checkout. bank transfer. all right, no error. match-code: MP1GR209
second test the same, but logged in.

In both cases: no email!

**Comment by inbaz** [comment]
Please have a look at your spam folder. The mails where correctly sent out from the system. If you find the mail in your spam folder (subject: EJC Registration System: Payment Information), please redirect to whole mail to me to analyse the problems.

**Comment by smadamit** [comment]
No. Got 3 Mails, all in inbox. No mail in spam. But I made much more orders!

**Comment by smadamit** [comment]
Tested with new email: ARW6HD28
got no mail!

**Comment by inbaz** [comment]
Yes, this was a server issue. I fixed it. Maybe it takes 24h to take effect. I set the rDNS entry for the servers ip. GMX told me: refused to talk to me: 554-gmx.net (mxgmx002) Nemesis ESMTP Service not available 554-No SMTP service 554 invalid DNS PTR resource record

**Comment by inbaz** [comment]
I already get the new rDNS record. Could you please retest with your gmx address?

**Comment by smadamit** [comment]
G9PR5899	06.03.2015 10:28:56	
tim.adams@ejc2011.de	5,00 €	unpaid	Detail

-> no email

**Comment by smadamit** [comment]
7AUFGK21	06.03.2015 11:04:38	Tim Adams test 
tim.adams@gmx.de	135,00 €	unpaid	Detail

-> yes email

**Comment by smadamit** [comment]
Test different provider:
- gmail -> test 0.2.15 no email!
- web.de
- GMX -> test 0.2.15 OK
- yahoo

**Comment by smadamit** [comment]
6156PN68	06.03.2015 11:15:49	Tim Adams 
timbo.adams@gmail.com	120,00 €	unpaid

-> no email!

**Comment by smadamit** [comment]
XVU6RN73	06.03.2015 11:18:56	Tim Adams 
tim-adams@web.de	120,00 €	unpaid

-> got an email: OK

**Comment by inbaz** [comment]
I read a bit through the spam tactics of the different email providers. We're not able to get our mails all in the inboxes of the participants.Nowadays it's hard work to get good reputation on the ip address of the server, the domain where the mails are sent from and in case of yahoo even the "From" field from which the mail is sent. We need to explain that to the participants in short nicely understandable sentences that they should have look at their spam folder.

E-Mail addresse like noreply@ or 123asd@ are nogos for the isps. It needs to be a understandable email which has a mailbox to be able to get bounce messages, like prereg@eja.net, this mailbox already exists - but the spf "problem"...

For a subdomain a complete email setup including a, mx and spf records needs to be setup and we need the mailbox from which the emails will be sent.

**Comment by smadamit** [comment]
VY2W8N46	07.03.2015 21:53:20	
tim.adams@ejc2011.de	23,00 €	unpaid

-> got an email: OK

**Comment by inbaz** [comment]
Is there any todo left?

**Comment by smadamit** [comment]
No todo for you. But keep it open, I will retest this issue on the new server and for different eMail Provider.

**Comment by smadamit** [comment]
retest with credit card. two cases:
- C7R1A167 with invalid input -> no email
- 81URV107 with valid input -> no email

**Comment by smadamit** [comment]
Let's do a lot of retesting with the new mail-system

**Comment by PiQuer** [comment]
After paying by credit card with Visa 4111111111111111, no confirmation mail for the payment (I did get a confirmation for the order). I would have expected two mails for the two ticket holders I enlisted.

Email is disp.reg.ejc@typename.de, I operate my own mail server for this domain, but never got a connection from s15441766.onlinehome-server.info for the payment confirmation mail.

**Comment by smadamit** [comment]
@PiQuer "After paying by credit card with Visa 4111111111111111, no confirmation mail for the payment (I did get a confirmation for the order). I would have expected two mails for the two ticket holders I enlisted." -> At the moment the system only sends order confirmations. But this will be one of the first implementations after going live.
