### ISSUE TITLE
delete email address from purchaser causes runtimeexception

### ISSUE THREAD

**Issue by christianbross** [inbaz/ers#271]
preregpp.eja.net / 0.2.56
I select a purchaser (this is only possible after adding an email address --> good!)
I abort the checkout process and go back to my persons, I edit the purchaser and delete the email address
now I perform the checkout - the system allows me to checkout with a purchase that doesn't have an email address any more

error details
_____________
Additional Information
Zend\Mail\Exception\RuntimeException
File:
/var/www/preregpp.eja.net/vendor/zendframework/zendframework/library/Zend/Mail/Transport/Sendmail.php:291
Message:
Unable to send mail: Unknown error
Stack trace:
#0 [internal function]: Zend\Mail\Transport\Sendmail->mailHandler('', '=?utf-8?Q?EJC=2...', 'This is a messa...', 'Date: Mon, 23 M...', ' -fprereg@eja.n...')
#1 /var/www/preregpp.eja.net/vendor/zendframework/zendframework/library/Zend/Mail/Transport/Sendmail.php(139): call_user_func(Array, '', '=?utf-8?Q?EJC=2...', 'This is a messa...', 'Date: Mon, 23 M...', ' -fprereg@eja.n...')
#2 /var/www/preregpp.eja.net/module/PreReg/src/PreReg/Service/EmailFactory.php(219): Zend\Mail\Transport\Sendmail->send(Object(Zend\Mail\Message))
#3 /var/www/preregpp.eja.net/module/PreReg/src/PreReg/Controller/OrderController.php(513): PreReg\Service\EmailFactory->send()
#4 /var/www/preregpp.eja.net/module/PreReg/src/PreReg/Controller/OrderController.php(454): PreReg\Controller\OrderController->sendConfirmationEmail()
#5 /var/www/preregpp.eja.net/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractActionController.php(83): PreReg\Controller\OrderController->checkoutAction()
#6 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#7 /var/www/preregpp.eja.net/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#8 /var/www/preregpp.eja.net/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#9 /var/www/preregpp.eja.net/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractController.php(116): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#10 /var/www/preregpp.eja.net/vendor/zendframework/zendframework/library/Zend/Mvc/DispatchListener.php(113): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#11 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#12 /var/www/preregpp.eja.net/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#13 /var/www/preregpp.eja.net/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#14 /var/www/preregpp.eja.net/vendor/zendframework/zendframework/library/Zend/Mvc/Application.php(313): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#15 /var/www/preregpp.eja.net/public/index.php(18): Zend\Mvc\Application->run()
#16 {main}

**Comment by inbaz** [comment]
I added an additional validation within the checkout page. If the email address is not valid I delete the user as purchaser from the order which causes an error message to add a purchaser with a valid email address. The packages of this persons keep untouched. 0.2.57

**Comment by inbaz** [comment]
P.S.: @christianbross The KickOff Milestone should only contain tasks which needs to be done at the day of goLive.

**Comment by christianbross** [comment]
Ok, then it Must be golive.

Sent from my mobile device
________________________________
Christian Broß
Organisationsteam
EJC 2011 e.V.

christian.bross@ejc2011.de
Mobil: +49 175 5768237
www.ejc2011.org

**Comment by christianbross** [comment]
Very good. That solves it. 

Sent from my mobile device
________________________________
Christian Broß
Organisationsteam
EJC 2011 e.V.

christian.bross@ejc2011.de
Mobil: +49 175 5768237
www.ejc2011.org

**Comment by smadamit** [comment]
tested in 0.2.57 -> OK
