### ISSUE TITLE
credit card payment short remark to 3-D Secure

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#277]
0.2.58

@christianbross Do you have text proposals for that:
- add a short note to the CVV2: "Also known as card verification value (CVV2). The value is a three-digit number imprinted on the signature panel on the back of the credit card." see: https://en.wikipedia.org/wiki/Card_security_code
- and a note to 3-D-Secure: https://en.wikipedia.org/wiki/3-D_Secure -> We have to think about the text.

Both issues were concerns from testers of the real credit card payment.

**Comment by smadamit** [comment]
ToDo: verfied by visa -> logo have to be shown

**Comment by smadamit** [comment]
for cvv2 explanation: add the credit card picture from ipayment, which is dedicated for this case.

**Comment by smadamit** [comment]
@christianbross Maybe we turn off the 3d-secure. So your issue expires.

**Comment by inbaz** [comment]
Added cvv info in 0.2.68

**Comment by smadamit** [comment]
fixed for going live 2015.

for 2016:
- and a note to 3-D-Secure: https://en.wikipedia.org/wiki/3-D_Secure -> We have to think about the text.
