### ISSUE TITLE
Unexpected behaviour when editing Person, starting from ticket

### ISSUE THREAD

**Issue by PiQuer** [inbaz/ers#278]
I select a Gala Show ticket, select show date, add a person, then realize I made a mistake with the name. I follow the hint to edit a person and click on the "My persons" link below the drop box. Then I edit the person and click on "Save". I would expect to be taken back to my ticket with the corrected person selected. Instead I'm back at the "My Persons" list.

The "correct" way to proceed from there is to click on "Products" and start over with a new ticket, which is not intuitive, the user might wonder what happened to the other ticket and if he will end up with two. The user might also be tempted to try the browser's "back" button, indeed going back in history three times takes you to the ticket with the corrected person (via the edit form and persons list). But relying on the browser to go back is risky, one can easily encounter non-existing pages, for example: first edit, then delete a person. Going back from there gives you this stack trace:

![stacktrace](https://cloud.githubusercontent.com/assets/1511250/6802422/9b4f9abe-d230-11e4-8e9b-2a636627a34d.png)

I think the best solution would be to provide an "edit" link on the ticket which takes you directly to the currently selected person's edit form, "Save" takes you back to the ticket. Very similar to how it works  when editing a person from the shopping cart, which is very good.

**Comment by smadamit** [comment]
nice test case

**Comment by christianbross** [comment]
Hi @smadamit 
are you sure this is "prio 1"?
doesn't look like a show-stopper to me..(!)

**Comment by smadamit** [comment]
You are right, no show stopper -> prio 2. But I guess this issue will happen quite often.

**Comment by christianbross** [comment]
Solution for now: deactivate link, replace with "My Persons", change text "menu" into "menu bar".
This way we avoid fixes that have a risk of creating new bugs.

**Comment by PiQuer** [comment]
good idea
