### ISSUE TITLE
Product/edit: Edit Product doesn't work in frontent

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#28]
Product/edit: If I edit the VariantValues I can see, that the VariantValues seem not not be saved in the database? I get always the default selection red, S for tshirts.

**Comment by inbaz** [comment]
I fixed that in 0.2.20. You are able to choose productvariants in the fronend and see them in the shopping cart, they're save in db and you can see them in order detail of the admin panel. What's not fixed yet is the edit function in the frontend. I did not yet find a valuable way to carry these information back to the product page.

**Comment by smadamit** [comment]
admin/order/index: it works

**Comment by smadamit** [comment]
open issue: edit function in the frontend

**Comment by inbaz** [comment]
Even if it's duplicated, we'll close this one, because in the other one are more information.
