### ISSUE TITLE
credit card error-messages

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#285]
0.2.63

I did a credit card payment. I entered the wrong ccv2 and got this error message:

![screen2](https://cloud.githubusercontent.com/assets/1533081/6807737/9fdc918e-d250-11e4-9398-431d3b4db8a1.png)

Maybe there is a certain sense why not altering: "card secure check is wrong"

**Comment by smadamit** [comment]
This is the error message for wrong Cardholder name :-(

![screen](https://cloud.githubusercontent.com/assets/1533081/6808322/b54256dc-d253-11e4-9968-82212b733c8d.png)

**Comment by smadamit** [comment]
So I think the todos are:
- systematically test with invalid credit card data -> log the error messages and think about better ones.
- implement the improved error messages

**Comment by smadamit** [comment]
Maybe the last error-message has another reason:

mail from ipayment:
-------------------------------------
Sehr geehrter ipayment-Kunde,


über Ihren ipayment-Account (mit der Account-ID 34725167) wurde in den
letzten Minuten versucht, mehrere Transaktionen von der gleichen IP-Adresse
(129.187.179.187) aus abzuwickeln. Für einen Online-Shop oder eine andere Online-
Anwendung ist dies untypisch. Deshalb blockiert das ipayment-
Betrugserkennungssystem aktuell Transaktionen von dieser IP-Adresse.

Die gesperrte IP-Adresse wird nach einiger Zeit wieder freigeschaltet.

**Comment by inbaz** [comment]
Just had a look at the pool with issues for testing. Do we really need better error messages for credit card fails? Let's do them when we really get feedback due to missleading error messages. In my opinion we don't need this ticket anymore, what do you think?
