### ISSUE TITLE
Product/edit: duplication of produts

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#29]
Product/edit: If I edit an unassigned tshirt and assign it to a new person I have in the end 2 tshirts, one unassigned and one assigned to the new person.

**Comment by inbaz** [comment]
fixed

**Comment by smadamit** [comment]
same bug, does not work

**Comment by smadamit** [comment]
in which version fixed?

**Comment by smadamit** [comment]
fixed and tested
