### ISSUE TITLE
email: links & legal terms

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#291]
0.2.64
- I guess the links preregpp.eja.net in the emails are dynamically inserted -> So for prod it will be prereg.eja.net
- the attached legal terms are empty -> just update to the current version

**Comment by inbaz** [comment]
please check in 0.2.66

**Comment by smadamit** [comment]
checked -> attached legal terms -> OK

@inbaz Please answer the question: "I guess the links preregpp.eja.net in the emails are dynamically inserted -> So for prod it will be prereg.eja.net"

**Comment by inbaz** [comment]
Yes, alls links are generated dynamically.
