### ISSUE TITLE
Change texts that state date when e-Tickets will be sent

### ISSUE THREAD

**Issue by philip-n** [inbaz/ers#297]
Currently the system says that e-Tickets will be sent as soon as payment is received. This will not be the case as e-Tickets are not yet implemented. Texts should be changed until eTickets are implemented:

## Help page https://preregpp.eja.net/info/help:
Replace

**We will send you a confirmation mail with all information as soon as we receive your order. When we receive the payment, we will send you a second mail that includes PDF documents with your e-tickets.**

with

**We will send you a confirmation mail with all information as soon as we receive your order. You will 
receive a payment confirmation mail with your eTickets at a later date (not immediately after payment has been received).**

## Confirmation mail
Replace

**Your eTickets and further information concerning the 38th European Juggling Convention will be delivered in another email as soon as your payment has been confirmed.**

with

**Your eTickets and further information concerning the 38th European Juggling Convention will be delivered in another email (not immediately after your payment has been received).**

I would then keep this issue open for the next milestone in order to change the text back when e-Tickets are implemented.

@Tim: Short confirmation that this is correct?

**Comment by smadamit** [comment]
correct

**Comment by inbaz** [comment]
fixed in 0.2.71, please check and place thicket after successful check in milestone secondlife

**Comment by smadamit** [comment]
0.2.71 -> OK

After implementation of #58 we have do replace the text back to the old version.

**Comment by smadamit** [comment]
Please change the following text in the version, which will go live with the matching features:

## Help page https://preregpp.eja.net/info/help:
Replace

**We will send you a confirmation mail with all information as soon as we receive your order. You will 
receive a payment confirmation mail with your eTickets at a later date (not immediately after payment has been received).**

with

**We will send you a confirmation mail with all information as soon as we receive your order. When we receive the payment, we will send you a second mail that includes PDF documents with your eTickets.**

## Confirmation mail
Replace

**Your eTickets and further information concerning the 38th European Juggling Convention will be delivered in another email (not immediately after your payment has been received).**

with

**Your eTickets and further information concerning the 38th European Juggling Convention will be delivered in another email as soon as your payment has been confirmed.**

**Comment by inbaz** [comment]
Changed in dev.
