### ISSUE TITLE
Text on checkout page (minor correction)

### ISSUE THREAD

**Issue by philip-n** [inbaz/ers#298]
Under the name of the purchaser on page https://preregpp.eja.net/order/checkout:

"The purchaser will receive all eTickets for all registered participants. If you have provided an email address for a participant this participant will be informed once the ticket is payed and will be able to download the eTicket on his own as well."

==>

"The purchaser will receive all eTickets for all registered participants. If you have provided an email address for a participant**,** this participant will be informed once the ticket is pa**id** and will be able to download the eTicket on his own as well."

(added comma, payed -> paid)

@christianbross  @smadamit Just dumping it here with milestone goLive0.3, please reassign as you see fit!

**Comment by inbaz** [comment]
done in 0.2.71
