### ISSUE TITLE
add gala unassigned and after that assign it to a new created person

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#299]
0.2.69

low prio bug:
- add gala unassigned to cart
- edit gala
- go to tab person and click on "add a new person"
- enter new person data -> save
- go to tab person and select the new person and select show date
- save changes and go to cart
- now you have duplicated the show ticket. The old unassigned one and the new assigned to the new person

Don't touch if it's complicate! In that case we postpone to SecondLife.

**Comment by inbaz** [comment]
The change would be easy but this will reopen other already fixed tickets.

**Comment by inbaz** [comment]
Test if this is solve with the database changes I've made.

**Comment by inbaz** [comment]
The agegroup tab is kicked out for Almere -> after EJC.
