### ISSUE TITLE
Product/delete: function missing

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#30]
Product/delete: we need this function

**Comment by inbaz** [comment]
Deleting product exists on /admin/product the outer right link.

**Comment by smadamit** [comment]
No I mean in the frontend. If I do not set the prefix Admin I mean the prefix PreReg

So this issue means: PreReg/Product/delete -> delete a product in an order

**Comment by inbaz** [comment]
Did just not work for unassigned items, fixed.

**Comment by jackcaveman** [comment]
Still not working in the My Shopping Cart page (/order)
Clicking the link on the right of the unassigned product does NOT remove the unassigned product.
productproduct/delete/5/0/1

It does work for assigned products.

**Comment by inbaz** [comment]
This was a classic race condition. :) You were to fast. The fixed version was not yet online. See my mail for further testing.
