### ISSUE TITLE
order list in the email -> crucial bug

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#301]
0.2.69

Have a look to order YK85RN33 in preprod:
- I send you my confirmation email I got
- look into the admin panel: admin/order/detail/137
- compare the item lists:
 - in the admin panel Isabelle & Leonie have a gala without a defined date -> is this OK. What is in the database?
 - apart from that the admin panel seems OK
 - in the email Tim has a week ticket, but no gala show selected. Should be: Saturday, August 8th, 21:00
 - rest seems to be OK

**Comment by smadamit** [comment]
one more comment, but it's an extra issue:
- maybe we should add the date of birth to the person in all item lists: admin panel, email, ...

**Comment by smadamit** [comment]
# new test case

## order/index

Tim -> OK, has a show date

![order-list](https://cloud.githubusercontent.com/assets/1533081/6837933/bd817fc6-d352-11e4-8217-2d4117bd111e.png)

## order/checkout

**Tim has no show date!**

![checkout-list](https://cloud.githubusercontent.com/assets/1533081/6837940/df273b20-d352-11e4-8f80-a1864a60cce4.png)

## order/view/HXDM8...

**Tim has no show date!**
Tim: Müller -> Adams see #135 -> OK

![orderview-list](https://cloud.githubusercontent.com/assets/1533081/6837955/f1b9622c-d352-11e4-83cc-5091d3d3dafd.png)

## admin/order/detail/...

Tim -> OK, has a show date
Tim: Müller -> Adams see #135 -> OK

![admin-list](https://cloud.githubusercontent.com/assets/1533081/6837958/06684e90-d353-11e4-9292-057fabee5574.png)

## email

**Tim has no show date!**
Tim: Müller -> Adams see #135 -> OK

![email-list](https://cloud.githubusercontent.com/assets/1533081/6837964/118997ac-d353-11e4-8471-6e2285546bf2.png)

I have also send the email to you inbaz.

**Comment by inbaz** [comment]
I changed the displaying of the variant values in 0.2.70, so it should be a bit clearer what exactly happens. I was not able to find the correct galashow for leonie, your first test case. Please recheck this issue as often as possible maybe with the exact same data as before. This error may not happen. I was not able to see it in the logs.

**Comment by smadamit** [comment]
In both 2 test  cases Tim has a gala ticket and Leonie and Isabelle not. I will retest.

**Comment by smadamit** [comment]
new test case
----------------------

Nearly the same as the last case. But not exactly (order oft he persons). Now there is no problem.

## cart

![cart-list](https://cloud.githubusercontent.com/assets/1533081/6843726/cbce219e-d3a5-11e4-9d49-2c7413c05b46.png)

## checkout

![checkout-list](https://cloud.githubusercontent.com/assets/1533081/6843729/d1959652-d3a5-11e4-92f6-65e7dd1c3299.png)

## admin

![admin-list](https://cloud.githubusercontent.com/assets/1533081/6843733/d632de68-d3a5-11e4-961b-31658f0c2779.png)

## email

![email-list](https://cloud.githubusercontent.com/assets/1533081/6843742/daadaa22-d3a5-11e4-8b71-0ac3cef0836e.png)

**Comment by smadamit** [comment]
@inbaz See my third test case above.

-> remove the gala tickets without variant in admin panel.

Should I do further retests?

**Comment by smadamit** [comment]
v0.3.9: new test case with 8 persons: DNUCWG56

- cart -> OK
- ceckout list -> OK
- email -> OK
- admin -> OK

-> OK
