### ISSUE TITLE
change day and click the cross of the popup

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#303]
0.2.69

low prio bug:
- edit a day ticket
- change the day of the ticket
- the popup appears
- click on the cross of the popup (close it)
- change the day another time
- now you have duplicated the day ticket in the cart

easy workaround: just remove the cross of the popup. Maybe there are some similar bugs with the cross of the popup.

**Comment by inbaz** [comment]
It's not a bug, it's a feature. You clicked "add to cart" in the meanwhile. So if you have let's say 10 persons, you can easily add week tickets for all of them by easily clicking the cross when added a ticket.

**Comment by smadamit** [comment]
@inbaz  yes it's a feature if you add products, but not if you edit. But maybe your right, it's not really a problem. You can see if I report such cases, the system is quite stable now :-) Should I close it?

**Comment by smadamit** [comment]
Close it or push it to SecondLife?

**Comment by inbaz** [comment]
I see what you mean, remove the cross from edit dialogue.

**Comment by smadamit** [comment]
I reopen -> there is still the cross in the popup. See also #159

**Comment by smadamit** [comment]
0.3.32 -> OK
