### ISSUE TITLE
any changes? Go back to shopping cart!

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#304]
0.2.69

If you are at the end of the checkout, just before clicking "buy now". You get a list of your items. If the user find an error he can easily go back to the cart by clicking to cart in the menu. But maybe some users are not sure if that affects their order and are afraid to do that. So what about a short remark just before the "buy now" -> Do you need any changes? Go back to shopping <a href=...>cart</a>!

**Comment by smadamit** [comment]
**proposal:** Add a new button just right from the "buy now" button: "change order" -> with this you jump back to order/overview and you can edit the shopping cart.

**Comment by inbaz** [comment]
added this button in 0.3.40

**Comment by smadamit** [comment]
tested in dev0.3.40 -> nice
