### ISSUE TITLE
missing hr-tag in person list

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#305]
0.2.69

There is a missing hr-tag in the my-persons-list (after Mumpfi Schlumpfi):

![personenliste](https://cloud.githubusercontent.com/assets/1533081/6841403/2c02002e-d38a-11e4-8c30-64eeb23a2b40.jpg)

**Comment by inbaz** [comment]
Tried to reproduce this problem, was not able to do it -> wontfix
