### ISSUE TITLE
Admin/PaymentType/addBankTransfer: bug with 2 deadlines

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#31]
Admin/PaymentType/addBankTransfer: error: does not work, if I create new with deadline_from and deadline_until.

There is exactly the same bug for: PaymentType/addCreditCard

workaround: Does work if I create with deadline_from without deadline_until. Then I can edit and add a deadline_until.

**Comment by inbaz** [comment]
Upsi, there was a "typo", fixed it.
