### ISSUE TITLE
order confirmation email: payment within 14 days

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#315]
0.3.4

at the moment:
- To complete your order, we need to receive your bank transfer within 14 days. If you ordered a discounted ticket (phase 1 or phase 2), please make sure that your payment is processed within 14 days after the end of this phase (i.e. 14th of May / 14th of July).

corrections:
- the 14 days rule is a general rule. not only for period 1 and 2. Same for cheque and credit card.

**Comment by inbaz** [comment]
I think yout -> your is already fixed in 0.3.5
Do we need to rewrite this 14 day rule?

**Comment by smadamit** [comment]
- right first issue is fixed
- yes we have to rewrite. But not for going live -> next week. SecondLife

**Comment by philip-n** [comment]
This actually came from the original confirmation mail template. I thought it was kind of duplicated, but guessed that there was a reason to it :-)

**Comment by smadamit** [comment]
Very easy fix...

Please change the text in the order confirmation mail from:
- To complete your order, we need to receive your bank transfer within 14 days. If you ordered a discounted ticket (phase 1 or phase 2), please make sure that your payment is processed within 14 days after the end of this phase (i.e. 14th of May / 14th of July).

to:
- To complete your order, we need to receive your bank transfer within 14 days. If you ordered a discounted ticket, please make sure that your payment is processed within 14 days after the end of the current discount period.

**Comment by inbaz** [comment]
I would not give them a date. The payment needs to be processed within 14 days after the purchase. The EJC core needs wants the money as fast as possible and not all 14 days after the prereg phases, or not?

**Comment by smadamit** [comment]
I had 7.1 of https://prereg.eja.net/Terms-and-Conditions-ERS-EN-v4.pdf in mind. But maybe you are right. So just skip the second sentence....

**Comment by inbaz** [comment]
So is this issue fixed?

**Comment by smadamit** [comment]
Couldn't test it on dev. Please change the text in the order confirmation mail from:

-To complete your order, we need to receive your bank transfer within 14 days. If you ordered a discounted ticket (phase 1 or phase 2), please make sure that your payment is processed within 14 days after the end of this phase (i.e. 14th of May / 14th of July).

to:

-To complete your order, we need to receive your bank transfer within 14 days.

After that close the ticket.

**Comment by inbaz** [comment]
done
