### ISSUE TITLE
What to do with participants with wrong date of birth?

### ISSUE THREAD

**Issue by inbaz** [inbaz/ers#320]
It's possible to give the birth date with 2015 and get a week ticket for free. Do we need to email them what their correct date of birth is and fix the settings?

**Comment by smadamit** [comment]
@inbaz  In the form participant/add we have the note:
- Note for personal data: Please enter your first name, surname and **date of birth like they appear on your passport ID card** (they will be checked at EJC onsite registration to validate that this eTicket belongs to you).

If someone is cheating in the order its his own problem. At the onsite registration he will not get his badge, since the date of birth is wrong. In best case it's a kind of extra service of the prereg coordinator to indicate this issue to the juggler.

@christianbross @jackcaveman What do you think?

**Comment by inbaz** [comment]
We should work together and if we can omit such problems by easily change the initial date, why not doing that?

**Comment by smadamit** [comment]
OK that was a misunderstanding. You mean if someone does this by accident. I thought someone does it   to cheat.

But don't forget participants which are really born in 2015! They have to be able to register (by their parents).

**Comment by christianbross** [comment]
what about a database extract? if we find tickets with only one purchaser and one ticket in birthday = 2015 we can send them a manual email
if the 2015-tickets are only for families (i.e. multiple tickets, parents + kids), then it should be ok
only disadvantage: it's more work to check manually , but I think it's good enough

**Comment by inbaz** [comment]
There is no hack. I'm just defaulting the value of date of birth to a date which is not today to wake up the user to choose not only the correct day and month of the date of birth but even the correct year. So maybe there will be some participants who insert the wrong date of birth. This needs to be discussed at the onsite registration and maybe the need to pay later. Let's see if we could make a list of possible wrong date of birth and add a notice to explicitly check their id cards.

**Comment by smadamit** [comment]
If you really validate this issue in the code: Why setting an arbitrary birth of date (date of first EJC)? Why not make a confirmation question to the purchaser: "Are you sure the this person is born in 2015? Please notice, that we need the correct date of birth, since we will validate this onsite by the id-card of all participants."

**Comment by smadamit** [comment]
**proposal:** After submitting a new person, the system validates if the birth of date is strange. If that is the case, the system ask the buyer if he/she can confirm his input.

What is a strange birth of date:
- date with the current year (2015)
- birth of date which falls into the agegroup U6 -> free price

**Comment by inbaz** [comment]
I don't think this will be a problem and I think I'm faster writing some emails to a list of persons where only one single week ticket was ordered and the participant is less than let's say 16 years to remember them that there needs to be a person in charge. I think this reminder would be a cool feature and solved this problem as well. Let's put this into a lower priority.

**Comment by smadamit** [comment]
OK, low prio...

**Comment by inbaz** [comment]
It will be possible to change userdata in 0.3.21. I think we need a button to recalculate the prices of items in a single order. So if somebody changes a participants details, this person needs to push the recalculate button as well. I do not want to do that automatically because I will break other things.

**Comment by inbaz** [comment]
Use date of order creation to find the correct deadline.
If somebody changes a user the status paid of this order will be deleted and the next auto matching run will rematch this order.

**Comment by smadamit** [comment]
do the following steps automatically after any change of the birth of date field of a person in an order:
- Use date of order creation to find the correct deadline. Use the new birth of date field of the person to find agegroup. select the corresponding price.
- the status paid of this order will be deleted and the next auto matching run will rematch this order.

**Comment by smadamit** [comment]
we decided in Skype:

The date of birth to a person is wrong. We can change the birth of date to the person in the admin panel. Now there are two cases:
- the agegroup dose not change -> nothing to do
- the agegroup was wrong -> all items of the person get canceled. The buyer of the order and the person itself (if there is the email in the system) get informed about the cancellation of the items/eTickets. We have to create new items in the system (the buyer or/and the prereg-coorinator). The status of the order have to be set to unpaid!

**Comment by inbaz** [comment]
This is implemented but I need to calculate the package price correct. I'm not excluding cancelled items, yet.

**Comment by inbaz** [comment]
Recalculation of a package is implemented in backend and needs to be tested.

**Comment by smadamit** [comment]
first test -> nice. But we need more tests to this...

**Comment by smadamit** [comment]
0.3.53

- 1. bug: the new items are created without the productVariant. See admin/order/detail/2171 in preprod.
- 2. bug: the price which is calculated does not fit with the one of the discount period of the order, but with the current price. See admin/order/detail/22 in preprod. Should be 90,00 not 135,00.
- 1. enhancement: You are avoiding the recalculation of items which are cancelled. You should also avoid for items which are in status refund.
- 2. enhancement (we can solve this later -> afterEJC?): If you change the price of an item which is in status paid, this status should switch to unpaid. And maybe even the status of the order? See admin/order/detail/22 in preprod

**Comment by inbaz** [comment]
Please retest in 0.3.59. I'm using the date of the order as base for the price calculation. I tried it and it worked with correct prices. Can you please redo your test to see if there's anything special? Your data is lost with the prod database transfer.

- ProductVariants are transferred to the new item
- recalculation of items in status refund is avoided
- status of the order is adjusted when the price changes

**Comment by smadamit** [comment]
- 1. bug: fixed -> see bug-report #505
- 2. bug: have to be tested
- 1. enhancement: have to be tested
- 2. enhancement: have to be tested

**Comment by smadamit** [comment]
0.3.65 -> all OK
