### ISSUE TITLE
translations of emails and etickets

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#321]
- translators have to translate all etickets and emails -> we have to wait till we are sure that there will be no changes anymore.
- implementation of order/email/7WPW...

**Comment by smadamit** [comment]
@jackcaveman I guess the EJA / you have some native speaker willing to do this translations. Important languages we need: fr, es, it, de. Can you give me contacts to translators.

**Comment by smadamit** [comment]
some comments:
- would be nice to have the possibility to resend emails/etickets in a certain language to a certain buyer in the admin panel
- proposal: New field for persons -> preferred language for receiving emails -> After that we have a valid choice for the language to send the emails...
- we have to think carefully about the different status (confirmed, paid, refunded, canceled, etc.) of the orders. Depending on the status of an order the system have to send different/several emails (maybe with etickets). This is an extra todo/issue.

**Comment by smadamit** [comment]
@inbaz FYI: status of the translations of the etickets:
- English -> original version done
- Italian -> done
- French -> in progress
- Spain -> in progress
- German -> do we have a German version?
- other languages -> imho we do not need more

I also think we do not need translations for the emails this year. Do you agree?

**Comment by smadamit** [comment]
status:
- English -> original version done
- Italian -> done
- French -> in progress
- Spain -> done
- German -> do we have a German version?
- other languages -> imho we do not need more

**Comment by inbaz** [comment]
Maybe Julie can do the german version?

**Comment by smadamit** [comment]
So we have no German version at the moment? I will take care of that.

**Comment by smadamit** [comment]
# Italian Translation

### Disclaimer

Scarico di responsabilità

Partecipando alla EJC, in nessun caso l'organizzatore il padrone di casa o i suoi rappresentanti o i suoi assistenti saranno responsabili per qualsiasi perdita o infortunio o danni, a meno che non si fondano su causa di negligenza grave o atto deliberato di violazione del dovere da parte dell'organizzatore o dei suoi rappresentanti o dei suoi assistenti. I partecipanti frequentano per scelta, a loro rischio e pericolo; assumono la responsabilità per la propria salute e prestano attenzione ad essa. Si segnala in particolare che l'EJC è un evento sportivo in cui giocolieri e acrobati professionisti si alleneranno insieme con i non - professionisti di tutti i livelli di abilità. Ci saranno laboratori a tutti i tipi di discipline circensi aperti (ma forse non di livello appropriato!) per tutti; saranno resi accessibili strutture e attrezzi, sia perché l'organizzatore li fornisce sia perché qualsiasi partecipante li mette semplicemente a disposizione degli altri. E' vostra responsabilità, e non degli organizzatori, né dei conduttori dei laboratori, i loro rappresentanti o assistenti, assicurarsi che in qualsiasi momento la vostra salute e condizione fisica è sufficiente per prendere parte al workshop in questione o l'utilizzo di strutture e attrezzi menzionati precedentemente sia sicuro.

### Adult (over 18 years old)

U18 (sotto i 18 anni)

Istruzioni brevi

Stampa questo biglietto e non darlo ad altri. Un genitore o tutore legale deve firmare le informazioni riguardanti la supervisione obbligatoria e lo scarico di responsabilità. Porta questo biglietto alla EJC e presentalo al banco di registrazione. Se frequenti la EJC da solo, abbiamo anche bisogno di una copia della carta d'identità del tuo tutore legale.


Supervisione obbligatoria: fai firmare ad un tuo genitore / tutore legale l'opzione A o B

Opzione A:

Acconsento che mio figlio / figlia (come indicato sulla destra) partecipi alla EJC Brunico dal 1 agosto al 9 agosto 2015. Parteciperò alla EJC io stesso e quindi fornirò la supervisione obbligatoria. Accetto lo scarico di responsabilità.


Opzione B:
Acconsento che mio figlio / figlia (come indicato sulla destra) partecipi alla EJC Brunico dal 1 agosto al 9 agosto 2015. Non parteciperò alla EJC. Allego una copia della mia carta d'identità a questo E-Ticket. Senza entrambi i documenti la partecipazione di mio figlio alla EJC è impossibile. Accetto lo scarico di responsabilità.

### U16 (under 16 years old)

U16 (sotto i 16 anni)


Brevi istruzioni

Caro accompagnatore, per favore stampa questo biglietto e non darlo ad altri. Un genitore o tutore legale deve aggiungere e firmare le informazioni riguardanti la supervisione obbligatoria e lo scarico di responsabilità. Portare questo biglietto alla EJC e presentarlo al banco di registrazione. Se non sei un genitore o tutore legale del bambino, ma una chaperon, abbiamo anche bisogno di una copia di un documento di identità del tutore legale del bambino.

Supervisione obbligatoria: fai firmare ad un genitore / tutore legale l'opzione A o B

Opzione A:

Acconsento che mio figlio / figlia (come indicato sulla destra) partecipi alla EJC Brunico dal 1 agosto al 9 agosto 2015. Parteciperò alla EJC io stesso e quindi fornirò la supervisione obbligatoria. Accetto lo scarico di responsabilità.


Opzione B

Acconsento che mio figlio / figlia (come indicato sulla destra) partecipi alla EJC Brunico dal 1 agosto  al 9 agosto 2015. Affido il seguente accompagnatore con la funzione di tutore legale e la supervisione obbligatoria. Garantisco che questo accompagnatore è un adulto (18 anni di età o superiore) e ha la capacità di prendersi cura di mio figlio / figlia. L'organizzatore non verificherà questo. Aggiungo una copia di un documento di identità di me stesso (come detto sopra). In caso contrario la partecipazione alla EJC non sarà possibile per mio figlio / figlia. Accetto lo scarico di responsabilità.

### and

- date and place   /  data e luogo
- signature of legal guardian  / firma del tutore legale
- name of chaperon   /  nome dell'accompagnatore 
- chaperon's date of Birth   / data di nascita dell'accompagnatore

**Comment by smadamit** [comment]
# Spanish

### Disclaimer

Descargo de responsabilidad

Durante la EJC, el anfitrión, sus representantes o ayudantes en ningún caso serán responsables de accidentes, lesiones o cualquier daño, excepto en crasa negligencia o acto deliberado de infracción del deber por parte del anfitrión, sus representantes o ayudantes. Los participantes asisten por su propia voluntad y riesgo; son responsables de su propia salud y velarán por ello. Remarcamos especialmente que éste se trata de un evento deportivo donde artistas circenses profesionales entrenarán con aficionados de todos los niveles. Habrá talleres de todo tipo de disciplinas circenses donde todos podrán participar (pero habrá talleres no aptos para cualquier nivel); los materiales y aparatos a los que se tendrá acceso será gracias a que el anfitrión o participantes simplemente los prestan. Es tu responsabilidad, y nunca del anfitrión, profesores de los talleres, sus representantes o asistentes, estar seguro en todo momento de que tu salud y condición física son los apropiados para participar en el taller en cuestión y que usarás los materiales y aparatos antes mencionados, de forma segura.

### Adult (over 18 years old)

Adulto (a partir de 18 años)

**Procedimiento:**

**Imprime** este tique y nunca se lo des a una tercera persona. **Firma** la cláusula de descargo de responsabilidad. **Entrega** este tique, mostrando tu **documento de identidad válido** (D.N.I. o pasaporte), en el mostrador de inscripción de la EJC.

### U18 (under 18 years old)

<18 (menores de 18 años pero mayores de 16 años)

**Procedimiento:**

**Imprime** este tique y nunca se lo des a una tercera persona. **Tu(s) padre(s), madre(s) o tutor(es) debe(n) firmar el documento de consentimiento legal**. **Entrega** este tique en el mostrador de inscripción de la EJC. Si asistes por tus propios medios, entonces necesitaremos una **fotocopia del documento de identidad de tu(s) padre(s), madre(s) o tutor(es) legal(es)**.

**Consentimiento legal: tu(s) padre(s), madre(s) o tutor(es) legal(es) debe(n) firmar la opción A o la B.**

Opción A:
Por la presente estoy conforme con que mi (nuestros/a) hijo(a) (como se nombra a la derecha) participe en la "EJC 2015 Brunico" desde el 1 de agosto de 2015 hasta el 9 de agosto de 2015. Asistiré (asistiremos) a la EJC y por lo tanto realizaré (realizaremos) la supervisión pertinente. Acepto (Aceptamos) el consentimiento legal.


Opción B:
Por la presente estoy conforme con que mi hijo(a) (como se nombra a la derecha) participe en la "EJC 2015 Brunico" desde el 1 de agosto de 2015 hasta el 9 de agosto de 2015. No asistiré (asistiremos) a la EJC. Adjunto (Adjuntamos) con el tique una fotocopia de mi (nuestro) documento(s) de identidad. Sin ambos documentos, la participación de mi (nuestro/a) hijo(a) a la EJC es imposible. Acepto (Aceptamos) el consentimiento legal.

### U16 (under 16 years old)

<16 (menores de 16 años)

**Procedimiento:**

**Querido responsable del menor, imprime** este tique y nunca se lo des a una tercera persona, por favor. El (las, los) padre(s), madre(s) o tutor(es) debe(n) firmar el documento de consentimiento legal y de descargo de responsabilidad. **Entrega** este tique en el mostrador de inscripción de la EJC. Si tú no eres el padre (madre) o tutor(a) legal, entonces necesitaremos una **fotocopia del documento de identidad de su(s) padre(s), madre(s) o tutor(es) legal(es)**.

**Consentimiento legal: tu(s) padre(s), madre(s) o tutor(es) legal(es) debe(n) firmar la opción A o la B.**

Opción A:
Por la presente estoy conforme con que mi (nuestros/a) hijo(a) (como se nombra a la derecha) participará en la "EJC 2015 Brunico" desde el 1 de agosto de 2015 hasta el 9 de agosto de 2015. Asistiré (Asistiremos) a la EJC y por lo tanto realizaré (realizaremos) la supervisión pertinente. Acepto (Aceptamos) el consentimiento legal.


Opción B:
Por la presente estoy conforme con que mi hijo(a) (como se nombra a la derecha) participará en la "EJC 2015 Brunico" desde el 1 de agosto de 2015 hasta el 9 de agosto de 2015. Confio (confiamos) en el siguiente supervisor(a). Tengo (tenemos) la garantía de que este(a) supervisor(a) es mayor de edad y posee las habilidades requeridas para cuidar a mi (nuestro) hijo(a). El anfitrión no lo verificará. Adjunto (Adjuntamos) con el tique una fotocopia de mi (nuestro) documento(s) de identidad. Sin ambos documentos, la participación de mi (nuestro/a) hijo(a) a la EJC es imposible. Acepto (Aceptamos) el consentimiento legal.

### and

- date and place: Fecha y lugar.
- signature of legal guardian: Firma del (de los) tutor(es) legal(es).
- name of chaperon: Nombre del adulto responsable.
- chaperon's date of birth: Fecha de nacimiento del adulto responsable.

**Comment by smadamit** [comment]
missing:
- French
- German

**Comment by smadamit** [comment]
skype -> OK
