### ISSUE TITLE
impressum

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#322]
http://de.wikipedia.org/wiki/Impressumspflicht#EU

**Comment by inbaz** [comment]
I thought about that, too. @jackcaveman what do you think? Should we just add the address of eja and an english default law text? We can let a lawer read through and check if it's correct.

**Comment by christianbross** [comment]
Warum nicht einfach hier hin verlinken, oder es von hier kopieren:
http://www.eja.net/de/imprint.html
http://www.eja.net/en/imprint.html

**Comment by inbaz** [comment]
That's perfect, but I'd like to have the ok from @jackcaveman.

**Comment by jackcaveman** [comment]
The address is already on the Legal Terms, I am happy to have it somewhere else as well.

**Comment by inbaz** [comment]
Added impressum link to footer. Do we need the impressum anywhere else?

**Comment by smadamit** [comment]
no that's fine -> 0.3.23
