### ISSUE TITLE
credit card data -> security

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#323]
You do a credit card payment. After finishing you can go back in history with the browser back-button. In the same way someone else could steal your credit card data. Not sure if that can/should be fixed. Was a feedback from a tester.

**Comment by inbaz** [comment]
On browsers who accept and interpret the autocomplete off attribute credit card data are not saved anymore in 0.3.9

**Comment by smadamit** [comment]
0.3.23 -> OK
