### ISSUE TITLE
validation email of person -> remark: is optional

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#325]
If you try to add a person with an email address which is already in use you get the validation error:
- "There is already a person with this email address in your order"

Just add a short note:
- "There is already a person with this email address in your order. Note: the email field is optional."

I got several times feedback, that testers were confused by this issue.

**Comment by inbaz** [comment]
Added this note in 0.3.21

**Comment by smadamit** [comment]
0.3.23 -> OK
