### ISSUE TITLE
make purchaser to participant

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#326]
a tester reported: Created a purchaser. Later I was not able to select the purchaser to a week ticket.

The purchaser needs a birthdate to get a week ticket. We know that. How can we enhance the usability that the tester from above does not fail.

**Comment by smadamit** [comment]
**proposal:** We allow to select a person without date of birth for e.g. a week ticket. In the last step of the checkout process the system validates whether all participants have a date of birth. If not you can not buy, get a validation error and have to fix it.

**Comment by philip-n** [comment]
**Question:** Can we just make the birth date field mandatory for the purchaser? To me, the drawbacks would be nil (purchaser will probably order a ticket for himself in 99% of the time) and it would prevent the additional checks and validations.

**Comment by inbaz** [comment]
We need to think about the buyer topic in general. With the profile function we really should set the logged in person automatically as buyer. 

In addition I would think about the optional email field. It is cool to send every participant their own eTickets, but I think this makes more problems than the feature is worth. We not not change it this year, but it's easier without this optional email field for the next years.

I do not need the birthdate for a buyer only for a participant. So a last check on the checkout page would be ok. For me, but let's think about solving this problem in a more general way.

**Comment by inbaz** [comment]
Just add the date of birth field to the buyer in next Version.

**Comment by smadamit** [comment]
date of birth as a mandatory field for buyer

**Comment by smadamit** [comment]
new bug report to this issue: #426

**Comment by inbaz** [comment]
Use participant forms for buyer as well.

**Comment by inbaz** [comment]
I implemented that.
