### ISSUE TITLE
transfer tickets to another person

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#328]
new feature: the purchaser can transfer paid tickets from one person to another one. In a first step this feature can be implemented in the admin panel. Later also in the login for the end-user.

**Comment by inbaz** [comment]
The thoughts on this topic were:
1. The ticket owner can transfer tickets to an email address
2. the receiver gets an email with a link to the registration form if he's not yet a user in the system, then he only gets a message that somebody wants to transfer a ticket to him.
2. The receiver needs to register at the system with firstname, surname, birthdate and the given email address and of course a password or login if he already has credentials.
3. The receivers accepts the ticket by accepting the terms and services and accept that the sender and receiver organize the money transfer themself
4. If the receivers has accepted one or more tickets of the sender the sender gets a notification by mail and can organize the money transfer. Once the money was transfered the sender can login to his profile again and can release the ticket to the receiver.
5. At this point the ticket is fully moved to another person.

There are many open issues in this process but I think that would be a great way to be able to move a ticket from a participant to another one.

To keep the information complete I'd like to keep the item which was "moved" in the senders package, but in state "moved". On the receiving site I'll generate a new item in state unpaid. For the Admin Panel that means there will be a "move Item" function where you will be able to search for a participant and can move this item to a new user (email address, first name, surname, birthdate).

**Comment by inbaz** [comment]
duplicate #394
