### ISSUE TITLE
question: transfer tickets from one person to another one

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#329]
depends on #328

- a purchaser buys tickets for the jugglers Alice and Bob. For example to save bank transfer fees (UK -> SEPA)
- purchaser collects the money for the tickets from the two jugglers
- purchaser pays the tickets
- after that he's able to transfer the paid tickets to new persons
- he collects money from two other jugglers (Peter and Tony) and transfer the tickets to the new jugglers
- Alice and Bob are pissed

questions:
- Do we have to think about such a scenario?
- Or is it just an issue between Alice, Bob and the purchaser?

ideas how to handle it:
- After the transfer Alice and Bob get an info email that the purchaser transferred the tickets. If Alice and Bob are fine with that -> OK. Otherwise: They can contact prereg@eja.net -> I'm not sure if that makes it better. What will happen after that?
- purchaser can only transfer tickets, where the participant has no email-address set. If the email-address is set, the participant will get the etickets by email and will be able to create an account.

**Comment by christianbross** [comment]
my opinion: let's not worry about that - it's a problem between the guys that pay together
we should not put technical restrictions in between ticket transfers and we should not get in between any fights between people ordering together - that's their business, not ours

**Comment by smadamit** [comment]
**decision:** After the transfer of the tickets Alice and Bob (old owner of the tickets) get an info email that the purchaser transferred the tickets to a new person. If Alice and Bob are fine with that -> OK. Otherwise: They can contact prereg@eja.net

In the end: it's a problem between the guys that pay together

**Comment by philip-n** [comment]
I agree.

From my perspective: Person that paid is the person that should be responsible for the tickets.
From the legal perspective (lucky guess): We sell tickets to one person ("Purchaser" / "buyer") and therefore have a contract (?) with that person. Other people should not be able to influence that.
From experience: For the past n years, there was only a miniscule percentage of tickets swapping that was actually announced beforehand (e.g. per mail in advance).

In general, I'd try to make the basic functionality (existing system, upcoming features such as profile) as comprehensive as possible and not worry to much about possible cases for XYZ. If there are enough incidents of a special use case XYZ, we can then think of an optimized way for handling it.
