### ISSUE TITLE
admin/product-price/view: order price-matrix by deadlines and agegroups

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#33]
Admin/Product/index: order prices by deadline

**Comment by inbaz** [comment]
Do we still need this? I would delete the prices from the overview and just have the Prices link in the product line.

**Comment by smadamit** [comment]
Yes we can kick out the prices out of admin/product/index.
But we need the ordering in admin/product-price/view. I change the issue.

**Comment by inbaz** [comment]
What ordering is ment here? Is this already fixed? Then only kick out of the way to large price list is an open task in this issue, right?

**Comment by smadamit** [comment]
I think: just remove the column "Base Price" in admin/product

**Comment by inbaz** [comment]
removed the column. This is a better overview.
