### ISSUE TITLE
cheque payment long description: preprod -> prod

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#334]
cheque payment long description: preprod -> prod

"UK Jugglers if you choose SEPA, most banks in the UK will charge you a fee of around £10 for this type of transfer. Choose this option and you can send a cheque to the UK Rep. The conversation rate Euro to Pounds for cheques is set to 0.8 - this means that you need to multiply the price with 0.8, i.e. 120 EUR​ ​--> 96 GBP. We know that this exchange rate is more expensive than market price, but we have to minimize the risk of fluctuations of the exchange rate. If you have an alternative payment method (e.g. credit card, or friends in other countries) we suggest to ​do so. You could also gather as a group of jugglers and buy many tickets in one single order - that way you could pay with bank transfer (SEPA) and divide the cost within the group. You may have a look to <a href="http://www.paymentscouncil.org.uk/files/payments_council/what_we_do/european_developments/sepa_regulation_-_information_for_consumers_2013_v3.pdf" target="_blank">leaflet to SEPA of the Payments Council</a>. <b>This option is for jugglers from UK only!</b>"

**Comment by smadamit** [comment]
wait for #210

**Comment by inbaz** [comment]
#210 is ready, please check and copy the data by hand.

**Comment by smadamit** [comment]
done
