### ISSUE TITLE
admin panel login -> checkbox: "remember me"

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#336]
Give the opportunity to check: "remember me". That you don't have to re-login every hour.

**Comment by inbaz** [comment]
added this function in next version 0.3.21

**Comment by smadamit** [comment]
tested in 0.3.23. Had to login again after a few hours, in spite of the checkbox "remember me"

**Comment by inbaz** [comment]
Please check if this is fixed in 0.3.39

**Comment by smadamit** [comment]
tested in 0.3.39:

@inbaz your bug-report:
- logged in with checkbox "remember me"
- clicked around in admin panel -> all OK
- waited for 2 hours
- https://preregpp.eja.net/ -> now I get a blank page. Visiting in "Inkognito-Modus" -> It works (new session).

**Comment by inbaz** [comment]
This is working now, but it would be nicer to immediately regocnize if a user is login and not with a click on the login link. I'll keep that open in nice to have.

**Comment by smadamit** [comment]
tested in dev:
- log in without remember me -> don't work. I am still not logged in.
- log in with remember me -> blank page. Can not do anything.

**Comment by smadamit** [comment]
bug is solved.

test of the remember me function will follow....

**Comment by smadamit** [comment]
seems to work
