### ISSUE TITLE
server: backup database of prod

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#342]
@staffanu is this done daily?

**Comment by inbaz** [comment]
I'm doing db backups every two hours and collect the data to another server every day. Should I own this ticket or @staffanu?

**Comment by smadamit** [comment]
If that's the case we can close this ticket.

**Comment by staffanu** [comment]
Yes, it is done daily and it seems to have worked for the past week. I
assume backups will remain relatively small so I can increase frequency.

Staffan

**Comment by staffanu** [comment]
Frequency increased to 8 backups per day (every 3 hours).

Staffan
