### ISSUE TITLE
Change "purchaser" to "buyer"

### ISSUE THREAD

**Issue by philip-n** [inbaz/ers#344]
Suggestion by Ron: Change "purchaser" to "buyer" ("purchaser" is not usually used). Would require text changes in a lot of places, though.

@smadamit @inbaz Comments?

**Comment by smadamit** [comment]
If a native speaker gives us the advice we should change it. @christianbross Do you agree?

**Comment by christianbross** [comment]
Yes.

Sent from my mobile device
________________________________
Christian Broß
Organisationsteam
EJC 2011 e.V.

christian.bross@ejc2011.de
Mobil: +49 175 5768237
www.ejc2011.org

**Comment by smadamit** [comment]
decision: let's change all text and replace "purchaser" to "buyer". Risk of side effects should be low.

**Comment by inbaz** [comment]
So, just changing the text but not the routing. /order/pruchaser will be still in place, right?

**Comment by smadamit** [comment]
yes, only text changes in the html-pages and emails

**Comment by inbaz** [comment]
Changed all purchaser to buyer in version 0.3.22.

**Comment by smadamit** [comment]
0.3.23 -> OK
