### ISSUE TITLE
Hide "This ticket belongs to:" dropdown until a person has been added

### ISSUE THREAD

**Issue by philip-n** [inbaz/ers#345]
Some people struggle with the "This ticket belongs to:" field on the product page. After clicking onto it a couple of times (in vain), they read the description and click "add person" link.

Proposal: Conditionally hide the "This ticket belongs to:" field until at least one person has been added.

**Comment by inbaz** [comment]
Where exactly is this "select person" field? I can only find the select box "This ticket belongs to:".

**Comment by philip-n** [comment]
Sorry, you are correct. The select box "This ticket belongs to:" is what I meant (I was entering tickets in between registrations at BJC on a mac with UK layout. Triple annoyance!).

Oh, and you'd be surprised on how many times people can click on the select box (which doesn't give any reaction on a mac, not even dropping down an empty box) before they read what's written above and below...

**Comment by inbaz** [comment]
To save unneeded click: what are you thinking about redirecting the user to the add Person page if

1. there is no person for this order, yet
2. the user chooses a personalized ticket

I think most of the users who are just clicking around are also users which order tickets for only themselfs, correct?

**Comment by smadamit** [comment]
decision via Skype:
- if there is no person for this order, yet -> warning "you have to create persons..." & no select box
- if there is at least one person -> no warning, but the select box to choose a person for the week ticket

**Comment by smadamit** [comment]
0.3.27 -> OK
