### ISSUE TITLE
403 Forbidden -> login form

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#347]
If you get:

```
403 Forbidden
You are not authorized to access Admin\Controller\Admin ::indexAction() .
```

Just display the login form after the access-error-message (If you are not logged in).

**Comment by inbaz** [comment]
Is this solved with the hidden Sign up?

**Comment by smadamit** [comment]
for the moment yes it is. It's an issue after implementation of #57

**Comment by smadamit** [comment]
Still an open issue for the release with the profile features

**Comment by inbaz** [comment]
please retest in 0.3.42
