### ISSUE TITLE
remove https from preprod

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#354]
I think we don't need it anymore right? It's tested. 2 clicks shorter to test anything would be nice.

**Comment by inbaz** [comment]
Nope, we're providing passwords and we are going to have productive data in preprod. We won't disable this security layer.

**Comment by staffanu** [comment]
Just to say I did try StartCom some time ago (see https://madeye.org/ for
an example). I could of course do that for preregpp.eja.net as well, but
does it really matter what certificate we have for that? I realize that if
it is used for demonstrating the system for BJC, for example, it could be
good. I will set it up if you acknowledge that it has a purpose...

Staffan

**Comment by smadamit** [comment]
@staffan Would be nice if you implement StartCom for the preprod-server. https://madeye.org/ is working for me.

**Comment by staffanu** [comment]
A StartCom certificate is now installed. I do not know if some intermediary
certificate is needed for some browsers. For me it seems to work in Firefox
and IE. Chrome complains that there are some outdated security settings and
that future versions might be unable to access the site. I do not currently
understand why but I haven't spend time on it.

Staffan

**Comment by inbaz** [comment]
Looks good on my site. Thanks!
