### ISSUE TITLE
eTickets: enough space for the product list?

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#36]
Please keep in mind that an order can include many products. e.g. day tickets for 4 differnet days plus a tshirt. I'm not sure if Julia considered this in her design of the eTickets. Is there enough space for the product list?

And to clarify: My understanding is, that one eTicket represents one package of one person.

**Comment by inbaz** [comment]
No, there will be one eTicket which represents a personalized ticket and another eticket (non-personalized, but even connected to a user) which represents the rest. The personalized on contains the disclaimer which needs to be signed. The registration desk onsite collects this ticket and if there is another plan for non-personalized ticket like another day or another place to give the things out the participant needs to have a second sheet with these infos on it.

**Comment by smadamit** [comment]
OK, but day tickets are personal right? Which means that we need the personalized eticket with a few different day tickets on it.

**Comment by inbaz** [comment]
Yes, I think so. Therefore we should be able to have space for a list with maximum 10 days including weekday and date.

**Comment by inbaz** [comment]
Please have a look at one of the eTickets and check if all the issues mentioned here are solved.

**Comment by smadamit** [comment]
fine
