### ISSUE TITLE
Mail transfer errors due to missing PTR records

### ISSUE THREAD

**Issue by inbaz** [inbaz/ers#363]
For the IPv6 IP of the prereg server the PTR records for rDNS are missing. Please contact the 1und1 support to add this PTR record. The IPv4 PTR is set to the original servers name, that's enough.

The problem came up for a freenet email address. The email was delivered via IPv6 because freenets mailserver are accessible via IPv6. After the first checking of the remote mailserver we got this message:

R=dnslookup T=remote_smtp: SMTP error from remote mail server after RCPT TO:<example@freenet.de>: host emig.freenet.de [2001:748:100:40::8:115]: 550-inconsistent or no DNS PTR record for 2001:8d8:849:9800::aa:ef7d (see RFC\n550 1912 2.1)

**Comment by smadamit** [comment]
Just had a case where a person ordered with a freenet-email and didn't receive an email. Even not in spam.

**Comment by philip-n** [comment]
Just for information (and not necessarily for this issue): Denis, Enrico et al. work at 1und1. If something technical has to be dealt with urgently, it might be worth to directly approach them and see if they can help somehow.

**Comment by smadamit** [comment]
@staffanu Can you have a look to this issue please

**Comment by staffanu** [comment]
There is now a PTR record for the ipv6m address as well.

**Comment by smadamit** [comment]
@staffanu Thanks for the fast fix!

@inbaz Can you please retest and close the issue if it works

**Comment by inbaz** [comment]
works, thank you.
