### ISSUE TITLE
popup

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#369]
0.3.27

You add a product and get this popup:

![screen](https://cloud.githubusercontent.com/assets/1533081/7204038/7f345188-e51f-11e4-8d9b-175ca0a5f63d.png)

Please:

- leave the cross, see also: #303 and #159
- change "add this product for another person" to "add this product again". E.g. you add one day ticket and after that one more for another day but the same person.

**Comment by inbaz** [comment]
fixed in 0.2.28
