### ISSUE TITLE
Generate eTicket PDFs and send emails

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#37]
Order/generatepdf: function missing

generate eTickets and append to the email after status paid

**Comment by inbaz** [comment]
Not missing but just not in place, yet.

**Comment by smadamit** [comment]
We have 3 kinds of etickets:
- normal
- U18
- U16

I have created two agegroups in the admin panel to implement this (both do not change the price):
- U18: 01.08.1997
- U16: 01.08.1999

**Comment by smadamit** [comment]
We will soon have the translations in English, German, Italian, French and Spanish: See #321

As decided we offer the option to resend the eTickets in another language. For the eTickets, which are not in English we should translate the most important parts of the etickets in English. So that the person at the registration onsite can understand all important information on the French eticket.

**Comment by smadamit** [comment]
# text of the emails with the eTickets

## version for the buyer

---------------------------------------------

### EJC 2015: Your e-Ticket(s) for order %matching_hash%

Dear %firstname% %lastname%,

thank you again for registering for EJC 2015. We received the payment for your order with ID %matching_hash% from %date%. The payment to your order is now confirmed!

Attached to this email, you can find your e-ticket(s).

If you ordered for other participants and entered their email addresses, they will receive their eTickets directly via email so they can print them themselves. If you ordered for other participants but didn't enter their email addresses, you will receive their eTickets and you will need to forward them to the respective participants.

Please print and sign the e-ticket(s), read it/them carefully and bring it/them with you to EJC. To check in at EJC, you will need to  present the e-ticket(s) together with your passport or identity card at the onsite registration. To be able to read the documents, you need to install Adobe Acrobat Reader, which you can download here: http://get.adobe.com/en/reader.

For the latest information about EJC 2015, stay tuned to www.ejc2015.org. If you have any further questions concerning your EJC 2015 ticket, please contact the prereg-coordinator via prereg@eja.net.

We wish you a pleasant journey and we are looking forward to a great convention.

Best regards,
Your European Juggling Association and the EJC 2015 organisers


## version for a participant

---------------------------------------------

### EJC 2015: Your e-Ticket(s) for order %matching_hash%

Dear %firstname% %lastname%,

thank you again for registering for EJC 2015.

Attached to this email, you can find your e-ticket.

Please print and sign the e-ticket, read it carefully and bring it with you to EJC. To check in at EJC, you will need to  present the e-ticket together with your passport or identity card at the onsite registration. To be able to read the documents, you need to install Adobe Acrobat Reader, which you can download here: http://get.adobe.com/en/reader.

For the latest information about EJC 2015, stay tuned to www.ejc2015.org. If you have any further questions concerning your EJC 2015 ticket, please contact the prereg-coordinator via prereg@eja.net.

We wish you a pleasant journey and we are looking forward to a great convention.

Best regards,
Your European Juggling Association and the EJC 2015 organisers

**Comment by smadamit** [comment]
some tests to the etickets:

1) Looks good!

2) One comment to etickets with more than one tickets of one kind.

## eticket with more than one week tickets on it:

![screen3](https://cloud.githubusercontent.com/assets/1533081/8253803/83e9a89a-1693-11e5-8b28-e6a0b817d96f.png)

Should not be the case, but if: Should we show all of them like it's implemented now, or should we show only one of the week tickets?

## eticket with more day tickets for one day

here we have an order with 2 day tickets of Monday. But on the eticket you can't see the second one.

![screen2](https://cloud.githubusercontent.com/assets/1533081/8253732/c220ef8e-1692-11e5-8a9c-494b406debc2.png)

![screen1](https://cloud.githubusercontent.com/assets/1533081/8253735/c509b99c-1692-11e5-80d9-930706203a59.png)

**Comment by smadamit** [comment]
If you have a very long list of tickets you may get problems. But the ERS of the onsiteReg knows the tickets to be handed out. So it's not really a problem.

**Comment by inbaz** [comment]
We should find and solve these issues before sending out the etickets.

**Comment by smadamit** [comment]
the email to the etickets are updated (check your birthdate on the etickets) -> see my post from 13th June.

**Comment by inbaz** [comment]
Julia will recheck the email texts. I'd like to have some minor changes. An initial version is already implemented.

**Comment by smadamit** [comment]
0.3.71 -> OK
