### ISSUE TITLE
after logging in I am not able to buy a new week ticket for myself

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#379]
0.3.32

- register
- create a password
- log in
- try to order a week ticket -> does not work -> see screenshot

![screen](https://cloud.githubusercontent.com/assets/1533081/7299990/79ef7054-e9d9-11e4-82fb-c3cf733164a8.png)

**Comment by inbaz** [comment]
pleas recheck in actual dev.

**Comment by smadamit** [comment]
tested in dev: does not work

I am logged in but don't appear in the my persons list. So I can't buy a week ticket for myself. But postpone this issue to after matching...

**Comment by smadamit** [comment]
see also: #380, #402

**Comment by smadamit** [comment]
0.3.43 -> OK
