### ISSUE TITLE
Payment/creditcard: secure this action

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#38]
Payment/creditcard: function missing

**Comment by smadamit** [comment]
for Andi:

Search for an example for 1und1 ipayment implementation.
We need to create a form which can hold all necessary data for credit card payment. With the data of this form we have two possibilities:
Just set in the URL of the iPayment processor in this form
do the payment via some soap requests to the ipayment api
The second possibility would be nice because we know immediately if the money transfer was successful.

**Comment by jackcaveman** [comment]
In case you haven't found this already:
http://hosting.1und1.de/downloads/1und1-ipayment-TechnikHandbuch.pdf
http://hilfe-center.1und1.de/ipayment-c82678/bedienung-c82775/kreditkartennummern-zum-testen-von-ipayment-a784577.html

**Comment by inbaz** [comment]
Hmm, haven't you tested the credit card form yet? It's already possible to create a credit card payment type which leads the user to the credit card form after a purchase. It's WIP, because not all security features of iPayment are implemented, yet, but the mainpart is already working and you can use the card numbers of @jackcaveman s link. The payment is done against the example account of iPayment 99999.

**Comment by smadamit** [comment]
Since this feature has the status 2 in the testingmatrix...

Tested with this output page:
------------------------------------------------------------
$_GET
array ( 'trxuser_id' => '99999', 'trx_amount' => '6119', 'trx_currency' => 'EUR', 'trx_paymenttyp' => 'cc', 'shopper_id' => 'H3HRDC12', 'addr_name' => 'Tim Adams', 'csrf' => 'f2a670c226391ff078d7e7120d546326-009b846293feb485e032ee27cd72869c', 'submit' => 'pay now', 'trx_typ' => 'auth', 'ret_errorcode' => '5003', 'ret_fatalerror' => '0', 'ret_errormsg' => 'Das angegebene Verfallsdatum der Kreditkarte ist fehlerhaft.', 'ret_additionalmsg' => 'The Expdate (0115) is invalid', 'ret_ip' => '80.187.97.51', 'redirect_needed' => '0', 'ret_status' => 'ERROR', )
$_POST
array ( )

**Comment by smadamit** [comment]
Second Test:
------------------------
$_GET
array ( 'trxuser_id' => '99999', 'trx_amount' => '1556', 'trx_currency' => 'EUR', 'trx_paymenttyp' => 'cc', 'shopper_id' => '7NYXPD58', 'addr_name' => 'Tim Adams', 'csrf' => '9e0160539df0d1eefbd1d19507347d2e-2d3f870eac5b1540af583410e147d45d', 'submit' => 'pay now', 'trx_typ' => 'auth', 'ret_errorcode' => '5003', 'ret_fatalerror' => '0', 'ret_errormsg' => 'Das angegebene Verfallsdatum der Kreditkarte ist fehlerhaft.', 'ret_additionalmsg' => 'The Expdate (0115) is invalid', 'ret_ip' => '80.187.97.51', 'redirect_needed' => '0', 'ret_status' => 'ERROR', )
$_POST
array ( )

**Comment by smadamit** [comment]
For me is missing:
- validate length of Card Check Code -> 3 digits I guess
- which card check code I have to type in during the testing?
- is the expire date an important field in ipayment? I think so, so same question, which date to type in during testing?

**Comment by inbaz** [comment]
Use a valid expiration date which is not in history. I think for testing it doesn't matter which check code and which expiry date you're setting but 01/2015 is in the past, therefore it's not valid.

**Comment by smadamit** [comment]
test was OK. v0.2.8

debug
------------------------
$_GET
array (
  'trxuser_id' => '99999',
  'trx_amount' => '1556',
  'trx_currency' => 'EUR',
  'trx_paymenttyp' => 'cc',
  'shopper_id' => 'Y8DG6187',
  'addr_name' => 'Tim Adams',
  'csrf' => 'b9441caa923b7e2e738c2370617c11b9-fe3a7ff0dfc31beff26bef0dae784126',
  'submit' => 'pay now',
  'trx_typ' => 'auth',
  'ret_transdate' => '05.03.15',
  'ret_transtime' => '15:50:44',
  'ret_errorcode' => '0',
  'ret_authcode' => '',
  'ret_ip' => '129.187.179.187',
  'ret_mandate_ref' => '',
  'ret_mandate_dueDate' => '',
  'ret_booknr' => '1-109486123',
  'ret_trx_number' => '1-109486123',
  'redirect_needed' => '0',
  'trx_paymentmethod' => 'MasterCard',
  'trx_paymentdata_country' => 'US',
  'trx_remoteip_country' => 'DE',
  'ret_status' => 'SUCCESS',
)
$_POST
array (
)

**Comment by inbaz** [comment]
TODO: 
1. I need to go through the security things of iPayment and implement them
2. We should have some valid test cases which cover most of our needs.

**Comment by inbaz** [comment]
I will save an order by pressing the "buy now" button (maybe we rename this button for credit cart payment). After that the order is in state pending. The user gets redirected to the credit card form. When this form is completed the order state changed to unpaid (here the session of the cart gets deleted). After successful response of the iPayment system the order will directly get into the state paid.

**Comment by inbaz** [comment]
When is a creditcard transaction really paid and the eTickets can be send out?

**Comment by smadamit** [comment]
I thought you get the status paid/pending directly by the ipayment API? Let's discuss it in skype...

**Comment by smadamit** [comment]
to sub-issues:
- set status paid/unpaid
- low-prio: 3-D-Secure

**Comment by smadamit** [comment]
@inbaz I have a very important question. In the end the credit card payment should work like this: An order is successfully paid by credit card. The status of the order is set to "paid" and the purchaser gets the next email with the eTickets. Am I right?

But if that is the case we would need the etickt feature and the eticket email ready for going live. My assumption till now was, that we can wait with that and implement it in milestone:SecondLife. I am afraid that's not true?

**Comment by smadamit** [comment]
A very simple workaround could be to activate credit card payment a little bit later.

**Comment by inbaz** [comment]
I can't see any problem. The order status paid has nothing to do with the email status "eTickets sent". We can add a notice that the eTickets will be sent not before the first PreReg Phase ends or not before June.

Set status paid is still open in this issue, 3D security can be activated through the iPayment backend, like I read the documentation this will simply work with this implementation, but maybe some testing would be nice. Like I understood to test a verified by VISA enabled credit card is needed AND the card issuer needs to have a system for this identification running, not VISA or MasterCard. So we can try that but if there are many problems it's easier to keep this feature off for now.

**Comment by inbaz** [comment]
Setting the payment status to paid is implemented now. Please test.

**Comment by smadamit** [comment]
tested in 0.2.48:
- 3-d-secure -> OK
- status paid -> pending, I open an issue / bug report
