### ISSUE TITLE
after logging in I am not able to buy with the logged in person as buyer

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#380]
0.3.32

- register
- request password
- log in
- make new order
- now I am not able to select the person of the log in (me) as buyer. I am not listed.

**Comment by inbaz** [comment]
In 0.3.40 you're listed as buyer, preselected and you cannot change the buyer in case you are logged in. Is that ok?

**Comment by smadamit** [comment]
yes that would be fine. test will follow...

**Comment by smadamit** [comment]
tested in dev: no does not work

**Comment by inbaz** [comment]
Argh, you're special. You are a user who has no order for yourself. :) Fixed that in case somebody registers without purchase anything once a time.

**Comment by smadamit** [comment]
tested in dev:
- logged in as ti...@ej.....de
- go to my persons list
- no one in there

Sorry, does not work :-(

**Comment by smadamit** [comment]
0.3.43 -> OK
