### ISSUE TITLE
Test deadlines

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#39]
I am not sure how to test the deadlines: prices and paymenttypes...

But we have to test it...

**Comment by smadamit** [comment]
Test of the change of prices depending on the deadlines succeeded. Behave like it should behave.

Will restart a test after the implementation of the agegroups. Then I will also test the payment-type behavior.

**Comment by smadamit** [comment]
for test.ers 0.2.29:
from_deadline don't work for payment types. further tests will follow.

**Comment by inbaz** [comment]
I added deadline support for the payment type frontend.

**Comment by smadamit** [comment]
@inbaz I always assign tickets to you if I need an action from you. And I set prio1 if it is urgent and prio3/4 if I can wait for it. In this case I decided, that it is not important yet.

**Comment by smadamit** [comment]
tested in preprod 0.2.36: from_deadline for payment_type works in frontend

further testing will follow... to_deadline...

**Comment by smadamit** [comment]
Retest:
- deadlines for payment types
- deadlines for prices

**Comment by smadamit** [comment]
0.2.45: tested deadline support for the payment type frontend -> OK
