### ISSUE TITLE
admin-panel list of 0€-week-tickets

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#395]
We need for the prereg-coordinator a list of all week tickets which have a price of 0€. The prereg-coordinator can then check weather this is correct or a mistake. Maybe as a part of admin/statistic ?

we need the following information to all 0€-cases:
- order-number
- buyer + buyer email
- concerned 0€ tickets with the names of the persons

**Comment by smadamit** [comment]
see also #376 and #320.

**Comment by inbaz** [comment]
Can you please think about a good place in the AdminPanel menu for this list?

**Comment by smadamit** [comment]
"Order" -> "0 € tickets" as last point in the submenu

**Comment by inbaz** [comment]
List is implemented. Check and close.

**Comment by smadamit** [comment]
tested in dev -> OK
