### ISSUE TITLE
admin/matching/manual add datetime of the transfer

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#397]
tested in dev with Browser chrome in Linux

in the manual matching: admin/matching/manual

- click on a bank-account -> expand all bank account statements
- click on one of the bank account statements to see the details -> bug: bank-account collapses

**Comment by inbaz** [comment]
fixed, you can have multiple open now.

**Comment by smadamit** [comment]
OK is working.

But new issue: is loading, loading, loading... -> show details of the bank account statement does not work

**Comment by inbaz** [comment]
check again. I provide name amount and the column with the code now. Is that enough information for manual matching?

**Comment by smadamit** [comment]
tested -> OK

I think the datetime of the transfer would be also an useful info.

**Comment by inbaz** [comment]
added date of payments.

**Comment by smadamit** [comment]
OK in dev
