### ISSUE TITLE
admin/matching/manual cancel match -> routing

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#398]
tested in dev

- admin/matching/manual
- click on the disable button of one of the bank account statements -> admin/matching/disable/81
- click on cancel -> bug: instead of getting back to admin/matching/manual I was directed to admin/order/detail/60

**Comment by smadamit** [comment]
same issue for cancellation of enabling of a bank account statement: admin/matching/enable/42

**Comment by inbaz** [comment]
same cause for both, fixed.

**Comment by smadamit** [comment]
tested -> OK
