### ISSUE TITLE
[fix before test] Buy Now button results in a blank page

### ISSUE THREAD

**Issue by jackcaveman** [inbaz/ers#4]
At the end of checkout you have to press the [buy now] button twice to get a blank page.

**Comment by inbaz** [comment]
At the moment I'm working on that. The real payment at the end is not implemented, yet. By pressing the buy now button you will be redirected to the correct payment page with either the bank transfer info, credit card form or (paypal form).

**Comment by inbaz** [comment]
You get lead to the payment page now with further information.
