### ISSUE TITLE
legal terms

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#40]
EJA (Jasper) and EJC (Andi A.) should answer all open questions.
Then we can finalize the legal terms.

**Comment by smadamit** [comment]
see also: #191

**Comment by smadamit** [comment]
status: 99% finished

**Comment by jackcaveman** [comment]
@smadamit,
I have asked Fredrik to also read through the Legal terms as a final check.

**Comment by smadamit** [comment]
@inbaz please see my email and implement info/terms Just put the 2 pdf-docs on the page.

**Comment by smadamit** [comment]
The "Back" of the legal terms site routes you to the home-site. What about "javascript: window.history.back();"

**Comment by inbaz** [comment]
added in 0.2.56

I'd like to add as less special javascript code as possible, because this is making thing complicated afterwards. I thin this is nice to have.

**Comment by smadamit** [comment]
OK -> workaround: what do you think about: link for legal terms with target="_blank" -> new window. That the user does not loose the current state of the order process -> in the first window.

**Comment by inbaz** [comment]
fixed in next version
