### ISSUE TITLE
Testing done by Raimar

### ISSUE THREAD

**Issue by PiQuer** [inbaz/ers#400]
Hi there! Feel free to split this up.

I did not test anything regarding the e-tickets yet, please let me know if this is possible and necessary at this stage.

These were my test cases for now. I hope to be able to do more testing tomorrow or on Friday.

# Regular panel #
## Order new items, as logged in user or as new user ##
This does not work anymore. 
### Week ticket ###
I could not buy a week ticket, logged in or not. The drop-down with the Galashow date is gone, if I try to "add to cart", it says "Please complete the whole form to put this product into the cart."
### Day ticket ###
If I am logged in:
Day ticket -> Choose me as person, select date -> add to cart -> select buyer. Now I am selected as buyer, but I cannot proceed: Save & continue -> "Value is required and can't be empty"

If I am not logged in, everything goes well, but no matter which payment method I choose, I get the error: "Please add missing information for checkout. To purchase this order choose a payment type." The payment method is empty.

### Gala Show ticket ###
There are now two drop downs to select the date, it seems the one from the week ticket ended up here, too. It seems the value from the right drop down is taken. After that, same problem as with the day ticket.

# Admin panel #
## Create new bank, edit bank ##
Works. I created the new bank "Big Bucks". When editing a bank, the checkbox could default to the current value, otherwise one might accidentally change the "virtual" flag without intention. 
## Upload csv with some transfers ##
Works, uploaded to "Big Bucks"
## Match columns to data in csv ##
Works by editing the format.
## Check auto-match ##
There was no auto-match performed with the transfers from "Big Bucks". Don't know if this should work upon upload, or how auto-matching is triggered.
## Display orders overview, matching overview, search orders ##
Works. Displaying orders or matches is already quite slow, there could be a scalability problem with several thousand more orders. 
## unlink a match ##
First encountered #396, but works now
## perform manual match ##
Works. In the right column, after expanding a bank, expanding a transfer does not work (just spinning wheel). After a manual match, the corresponding transaction on the right side is not shown anymore. But if I upload the same csv file again, all transactions are there again, including those manually matched.
## disable transfers ##
First directed me to an error page, but works now.
## Display disabled transfers ##
Works, but clicking on any of the eyes gives an error page.
## Minor things ##
The link "My Profile" directs to /profile in the registration system, which displays my profile data. In the Admin Panel, "My Profile" links to /user, which only displays "Hello mail!" (probably because my email address is mail@...)

**Comment by inbaz** [comment]
@PiQuer thank you for testing. Please split up the issues immediately. It's less work to have an issue which can be simply closed if it's already fixed than splitting up this bunch of issues. I fixed most of the issues. Please test all the things and create single issues for each thing you recognize. If you're done, close this issue.

**Comment by PiQuer** [comment]
Will do.

**Comment by PiQuer** [comment]
Done.
