### ISSUE TITLE
crucial bug frontend: Cannot choose payment method

### ISSUE THREAD

**Issue by PiQuer** [inbaz/ers#401]
To reproduce, choose any product and any payment method. At the checkout page, this error message is displayed

Please add missing information for checkout

To purchase this order choose a payment type.

**Comment by smadamit** [comment]
crucial bug in current dev version!

**Comment by inbaz** [comment]
Yep, the payment type was saved the wrong way. :) fixed.

**Comment by smadamit** [comment]
tested in dev:
- payment type is saved now
- BUT: if you have saved the payment type and go back to order/payment the type is not preselected

Why do we have this new bug? You changed code, which generates side effects in the frontend. Do we have to retest the whole system before going live with the next version? Or have you an idea where can be new side effects and where side effects are very unlikely?

**Comment by inbaz** [comment]
I fixed the new bug with pre selection. Like discussed on the phone I found a function to validate the entity schema. We were lucky that nobody hits a bug caused of these errors.

I would do a diff of the old entities to the new ones to see where exactly were changes made. But nevertheless a system check is needed before going live, so the main function will work correctly.

**Comment by smadamit** [comment]
tested in dev -> OK
