### ISSUE TITLE
Logged in user gets deleted from "My Persons" when deleting an item from shopping cart

### ISSUE THREAD

**Issue by PiQuer** [inbaz/ers#403]
To reproduce: log in and check "My Persons", logged in user is displayed. Put something into the shopping cart, delete it, "My Persons" is empty. Log out and log in again, the user is there again.

**Comment by inbaz** [comment]
Can't reproduce it. Can you describe in detail which product you're putting into the shopping cart?

**Comment by PiQuer** [comment]
Found it, my mistake :) I pressed delete next to the name, not next to the product item. Of course the person is deleted then.

This is still an issue though, opened #410.
