### ISSUE TITLE
auto-match not working

### ISSUE THREAD

**Issue by PiQuer** [inbaz/ers#405]
I uploaded a test.csv to the bank "Big Bucks" which I created, it contains an entry for Lisa Kollmer which is not automatically matched. Not sure whether this is a bug, maybe something else is needed to trigger auto-matching.

This is the file:

    ,,,
    ,,,
    Datum,Name,Betrag,Verwendungszweck
    2015-05-01,Lisa Kollmer,120,AVYDN741
    2015-05-15,Magdalena Jund,120,932W8U86

**Comment by smadamit** [comment]
not implemented yet...
