### ISSUE TITLE
Statistic: inconsistency between "overview" and "bank accounts" 

### ISSUE THREAD

**Issue by PiQuer** [inbaz/ers#408]
The numbers are different.

Overview:

EJC NL 	321 €
Credit Card 	123 €
Volunteers 	0,00 €
UK Cheque 	0,00 €
test 	0,00 €
Big Bucks 	360,00 €

Bank accounts:

EJC NL 	432 €
Credit Card 	234 €
Volunteers 	0,00 €
Big Bucks 	240,00 €
total sum 	xxx €

**Comment by smadamit** [comment]
first are all orders, second only the ones which are matched with a payment. Am I right? Maybe we should rename the menu text?

**Comment by PiQuer** [comment]
Is the "Overview" supposed to be cumulative with respect to uploaded csv files? I uploaded a file to "Big Bucks" with only two transfers, 120 each, but Overview shows 360. Maybe some other transfer from an earlier upload?

**Comment by smadamit** [comment]
@inbaz Please answer, I have no clue about that...

**Comment by inbaz** [comment]
On the one hand you have the amount of money which is calculated over all purchased items. Since we know that people participating an ejc are kind of chaotic there is the possibility to cancel or even refund tickets within the prereg phases. On the other hand there is the amount of money which is calculated through all amounts of the bank accounts csv export. If not all orders have been transferred yet these amounts are different. On a third hand there is the real amount on the bank account which contains money that's not intended for this ejc, so maybe the treasurer should be able to disable these bank statements to be not visible in this statistic. Is this the same invisible switch we already have? So counting only the amount of enabled bank statement should be correct.

@PiQuer does this answer your question? Could you please think of a better description for these fields in the statistic, so it's clearer what these numbers are saying?

**Comment by smadamit** [comment]
@inbaz "Is this the same invisible switch we already have? So counting only the amount of enabled bank statement should be correct." -> yes

**Comment by PiQuer** [comment]
Thanks for the clarification.

For the overview section I would suggest: "Bank account balances (including disabled statements)" or "Bank account balances (excluding disabled statements)", whatever the intended number is. At the moment, as far as I can tell, disabled statements are included in this number.

For the Bankaccount menu item I would suggest something like "Total amount matched to orders".

**Comment by inbaz** [comment]
There is the orders panel which shows the whole amount of all orders
There is the bank account panel which shows the whole amount of statements loaded into the bank account (will be excluding disabled)
There is the Orders site where you can see how many orders are paid and how many are unpaid. I think this will even show if there are orders cancelled.

Where do you mean the title of the panel should be changed?

**Comment by PiQuer** [comment]
At the moment I cannot log in (c.f. my mail)

**Comment by PiQuer** [comment]
This has changed a bit since creation of the issue. I think the Orders panel and the Orders site is fine. At the moment there are no bank accounts, I will look at these items again after you have matched some orders.

**Comment by PiQuer** [comment]
What is not immediately clear at the moment is the difference between Stats->Overview->Bankaccounts and Stats->Bankaccounts

This is why I would suggest:

"Bank account balances (excluding disabled statements)" for Stats->Overview->Bankaccounts
"Total amount matched to orders" for Stats->Bankaccounts

**Comment by inbaz** [comment]
The Stats->Overview->Bankaccount is the former statistic where all stats were put on a single page. This should be spread up into several pages to not have that much db queries on a single page load. Stats->Bankaccount will replace Stats->Overview->Bankaccount.

**Comment by inbaz** [comment]
@Bone008 can you split these pages up correctly to have all data needed on the new page and all data not needed deleted from the overview page?

**Comment by Bone008** [comment]
I completed the transition from the "Overview" to the "Bank accounts" page, which shows both summaries now (all statements & matched statements).

Results are in the iss392 branch.

**Comment by smadamit** [comment]
@Bone008 should we do some tests on it? Then reopen and add the label test.

**Comment by Bone008** [comment]
@smadamit The new Bank accounts page is still missing two things: ignoring disabled statements and handling virtual accounts. I don't think testing makes too much sense before that.

I will create a new ticket for the rest of the changes and will mark that for testing once I have done that.

**Comment by jackcaveman** [comment]
My thoughts on the stats page as treasurer:
There is no coherence between totals reported on statistic/orders and statistic/bankaccounts. Is is possible to add in between" numbers so you can see how these pages are connected. The "magic amount" is missing: bank total + some magic amount = orders total

2nd is a feature request. As treasurer I keep track of refunds per modality, so if you can add a table than it's easier for me to compare.
![image](https://cloud.githubusercontent.com/assets/11071240/10176314/414f7648-66f4-11e5-9184-0debcb23c99f.png)
