### ISSUE TITLE
order/buyer: add a new buyer -> button is inactive

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#409]
tested in dev

- no person in my persons
- logged in
- go to order/buyer
- not able to add a new buyer -> button is inactive

**Comment by inbaz** [comment]
This is your special account. Can you please change your password to something you can send over to me?

**Comment by smadamit** [comment]
I sent you my new password by email...

**Comment by inbaz** [comment]
That's ok. It is really you, because you're logged in, so you're the buyer of this order. Try to login at ebay and purchase something for another buyer. That will not work since you're logged in, or not? Do you expect another behavior?

**Comment by smadamit** [comment]
0.3.43 -> Now it's OK, because my logged in account is set as buyer...
