### ISSUE TITLE
Import of csv: statement is excluded if present in other bank account

### ISSUE THREAD

**Issue by PiQuer** [inbaz/ers#411]
When importing a csv all statements are ignored which are already present in the system. Apparently this includes identical statements which are present in *other* bank accounts as well.

Just a heads up. Is this the intended behavior?

**Comment by inbaz** [comment]
Like described in the other issue, every bank statement gets a hash. So if you have two banks with exactly the same bank statement line: name, date, amount, "Verwendungszweck", IBAN, BIC and so on, then this will be a problem. :)
