### ISSUE TITLE
Import of csv: recovering from accidental upload

### ISSUE THREAD

**Issue by PiQuer** [inbaz/ers#412]
At the moment there is now way to recover from an accidental csv upload. 

For example, have a look at the Small Bucks bank. I was able to upload a csv file where column 2 and 3 are switched, these were imported as new statements. Also adding a column and uploading again increased the number of imported statements every time.

This lets me believe one can seriously mess up the system if one accidentally uploads the csv of a wrong account, or a csv where the internal structure has changed a bit. Additionally I see no way at the moment to recover from that. One cannot delete the erroneous transactions (only disable them, which is not feasible for many thousands).

I don't know how to solve this. One possibility is to allow an "override" upload, which resets the bank statements to exactly the ones given in the upload. But this of course has serious implications to existing matches.

Another way I could think of is to add a sanity check before actually importing, something like "I would import XX new statements, is that what you want?".

The third possibility is to allow mass deletion of statements which are not yet matched.

**Comment by inbaz** [comment]
Yes that's a problem. I had some thoughts on that and the best one was to save uploads in a separate table. This makes me able to delete all statements of a specific csv upload.

In general uploading a csv works with a hash algorithm which created a hash over all columns. If the hash can be found in the database this csv line was already uploaded. This makes it possible to upload an updated csv file without deleting former uploaded lines. Changing the csv format is a problem in the system. If that happens there needs to be a cut, a new bank account needs to be opened where the new format can be entered. But hopefully the banks do not change their csv formats that often. :)

Will this idea solve your problem?

**Comment by PiQuer** [comment]
Yes, more likely than a changed format is a user uploading the wrong file :) 

Just trying to point out potential trouble from an end-user perspective, and I didn't know if you or others will be the ones uploading csv files. If the database sysadmin can easily recover, than that's a good thing of course.

**Comment by smadamit** [comment]
"more likely than a changed format is a user uploading the wrong file :)"
-> I think this can really happen even if only Jasper is doing it -> people make mistakes

Maybe check the number of columns and stop if there is a problem?

**Comment by inbaz** [comment]
added the functionality to delete bank statements which were imported from a file in 0.3.41

**Comment by smadamit** [comment]
@PiQuer Can you please test this. You were more involved into it...

**Comment by PiQuer** [comment]
Generally looks good, works if none of the statements is matched. Otherwise there is a SQL error, #437.

**Comment by PiQuer** [comment]
Can be closed from my point of view.
