### ISSUE TITLE
short retest of the frontend before going live with milestone matching

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#414]
A system check is needed before going live, so the main function will work correctly.

**Comment by PiQuer** [comment]
This is what I can test automatically at the moment:
All products in combinations with all age groups, (one of the days for day ticket and one of the shows for gala/week ticket, and for Gala I have chosen "add buyer" instead of "add person"), for not logged in user paying with SEPA. This takes about nine minutes.
Next I will extend this to credit card payment and to logged in users.
Please let me know if you want other functions tested automatically.

**Comment by PiQuer** [comment]
This is the code repository for the [automatic tests](https://github.com/PiQuer/ERSTestSuite).
At the moment it is still largely undocumented and only tested on Linux.

**Comment by inbaz** [comment]
Ist this testing suite free and can be setup on any server or pc? What are the system requirements?

**Comment by PiQuer** [comment]
Yes it is free and open-source. The system requirements are Python 2.7 with the following modules:
* [pyautogui](https://github.com/asweigart/pyautogui)
* [numpy](www.numpy.org/)
* [opencv2](http://opencv.org/), which comes with python bindings. This dependency could be made optional. I use it for fast image matching. Pyautogui comes with that functionality but is much slower. Maybe I find a native numpy solution which is sufficiently fast.

In principle all this (including pyautogui) is cross-platform. I have no possibility to test on Windows, and I have not coded with cross-platform in mind, so probably a few things have to be adapted, but nothing major. Also, all the image templates which I use for matching are from my Chrome Browser, and I noticed that on a different system the elements are rendered differently (maybe slightly different fonts), so that the tests fail. This is "only" a matter of taking the screenshots of the elements again and save them to the config directory. 

I could set the system up and maintain it on my own server. This saves the trouble of regenerating all the screenshots.

**Comment by smadamit** [comment]
really great, @PiQuer -> can you do the testing. Your ticket...

**Comment by smadamit** [comment]
I tested the script. After some adjustments and new screenshots it's working also on my laptop.

**Comment by PiQuer** [comment]
I have added tests for credit card payments, and one order is done with a logged in user. I don't think it is necessary to buy all products again as logged in user with both payment methods. Also I have not included UK cheques.

In total these are 16 tests now in 19 minutes on my laptop. I can add whatever tests you want, just let me know.

I have also added a small README file to the project with very basic installation and usage instructions. I leave this issue open for now, as a reminder to retest before going live.

**Comment by PiQuer** [comment]
Added three new test cases as @inbaz suggested on the phone:

* 2 week tickets for two different persons
* 1 week ticket and 1 day ticket for two different persons
* 2 day tickets on different days for one person

All tests fail at the moment because of #437.

**Comment by smadamit** [comment]
@PiQuer You can run you test script, #435 and #438 is fixed now...

**Comment by PiQuer** [comment]
Great, I let it run this afternoon.

**Comment by PiQuer** [comment]
All green :)

**Comment by PiQuer** [comment]
@smadamit Sorry forgot to report.... the tests were successful

**Comment by smadamit** [comment]
@PiQuer Can you please do a new test run on the upcoming release 0.3.51. It is not on preprod yet. And can you please always write here the version number which you have tested successfully, when you are doing it.

**Comment by PiQuer** [comment]
@smadamit  Test run of 0.3.52 on the way.

**Comment by PiQuer** [comment]
Test run of 0.3.52 complete, all successful apart from #492 and #491.

**Comment by PiQuer** [comment]
Test run of 0.3.53 on its way.

**Comment by PiQuer** [comment]
All successful in 0.3.53.

**Comment by PiQuer** [comment]
All successful in 0.3.54.

**Comment by smadamit** [comment]
Hi @PiQuer 

Have you any idea why my first try to order day tickets fails and the second time it was OK. See my code and outputs. The second time I skipped the orders of week and gala tickets... Can you do a test with your test script for the new version 0.3.62. This version will go live - I hope...

# first try:

code

```
class OrderTestCase(unittest.TestCase):
  def setUp(self):
    CI.empty_shopping_cart()
    CI.go_home()
  def test_ticket_order_week_normal_sepa(self):
    self.assertTrue(CI.order_ticket(ticket='week', age='normal', payment='sepa'))
  def test_ticket_order_week_reduced_sepa(self):
    self.assertTrue(CI.order_ticket(ticket='week', age='reduced', payment='sepa'))
  def test_ticket_order_week_free_sepa(self):
    self.assertTrue(CI.order_ticket(ticket='week', age='free', payment='sepa'))
  def test_ticket_order_day_normal_sepa(self):
    self.assertTrue(CI.order_ticket(ticket='day', age='normal', payment='sepa'))
  def test_ticket_order_day_reduced_sepa(self):
    self.assertTrue(CI.order_ticket(ticket='day', age='reduced', payment='sepa'))
  def test_ticket_order_day_free_sepa(self):
    self.assertTrue(CI.order_ticket(ticket='day', age='free', payment='sepa'))
  def test_ticket_order_gala_normal_sepa(self):
    self.assertTrue(CI.order_ticket(ticket='gala', age='normal', payment='sepa'))
  def test_ticket_order_gala_free_sepa(self):
    self.assertTrue(CI.order_ticket(ticket='gala', age='free', payment='sepa'))
  def test_ticket_order_gala_reduced_sepa(self):
    self.assertTrue(CI.order_ticket(ticket='gala', age='reduced', payment='sepa'))
```

output
```
2015-06-15 18:44:39,113 INFO: Sleeping 0 seconds, please bring the browser with the ERS site loaded to the front.
2015-06-15 18:44:39,113 INFO: 
2015-06-15 18:44:39,113 INFO: - CHANGE TO US-KEYBOARD-LAYOUT -
EEE......
======================================================================
ERROR: test_ticket_order_day_free_sepa (__main__.OrderTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "main.py", line 38, in test_ticket_order_day_free_sepa
    self.assertTrue(CI.order_ticket(ticket='day', age='free', payment='sepa'))
  File "/home/tim/Downloads/ERSTestSuite-master/ERSClientInterface.py", line 195, in order_ticket
    elif ticket == 'day' : self.select_day_ticket(name=name, email=email, age=age)
  File "/home/tim/Downloads/ERSTestSuite-master/ERSClientInterface.py", line 141, in select_day_ticket
    self.clickto('day')
  File "/home/tim/Downloads/ERSTestSuite-master/ERSClientInterface.py", line 71, in clickto
    return super(ERSClientInterface, self).clickto(*args, **kwargs)
  File "/home/tim/Downloads/ERSTestSuite-master/ClientInterface.py", line 232, in clickto
    point = self.locate(point)
  File "/home/tim/Downloads/ERSTestSuite-master/ClientInterface.py", line 347, in locate
    raise ElementError(im)
ElementError: day

======================================================================
ERROR: test_ticket_order_day_normal_sepa (__main__.OrderTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "main.py", line 34, in test_ticket_order_day_normal_sepa
    self.assertTrue(CI.order_ticket(ticket='day', age='normal', payment='sepa'))
  File "/home/tim/Downloads/ERSTestSuite-master/ERSClientInterface.py", line 195, in order_ticket
    elif ticket == 'day' : self.select_day_ticket(name=name, email=email, age=age)
  File "/home/tim/Downloads/ERSTestSuite-master/ERSClientInterface.py", line 141, in select_day_ticket
    self.clickto('day')
  File "/home/tim/Downloads/ERSTestSuite-master/ERSClientInterface.py", line 71, in clickto
    return super(ERSClientInterface, self).clickto(*args, **kwargs)
  File "/home/tim/Downloads/ERSTestSuite-master/ClientInterface.py", line 232, in clickto
    point = self.locate(point)
  File "/home/tim/Downloads/ERSTestSuite-master/ClientInterface.py", line 347, in locate
    raise ElementError(im)
ElementError: day

======================================================================
ERROR: test_ticket_order_day_reduced_sepa (__main__.OrderTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "main.py", line 36, in test_ticket_order_day_reduced_sepa
    self.assertTrue(CI.order_ticket(ticket='day', age='reduced', payment='sepa'))
  File "/home/tim/Downloads/ERSTestSuite-master/ERSClientInterface.py", line 195, in order_ticket
    elif ticket == 'day' : self.select_day_ticket(name=name, email=email, age=age)
  File "/home/tim/Downloads/ERSTestSuite-master/ERSClientInterface.py", line 141, in select_day_ticket
    self.clickto('day')
  File "/home/tim/Downloads/ERSTestSuite-master/ERSClientInterface.py", line 71, in clickto
    return super(ERSClientInterface, self).clickto(*args, **kwargs)
  File "/home/tim/Downloads/ERSTestSuite-master/ClientInterface.py", line 232, in clickto
    point = self.locate(point)
  File "/home/tim/Downloads/ERSTestSuite-master/ClientInterface.py", line 347, in locate
    raise ElementError(im)
ElementError: day

----------------------------------------------------------------------
Ran 9 tests in 491.139s

FAILED (errors=3)

```

# second try:

code

```
class OrderTestCase(unittest.TestCase):
  def setUp(self):
    CI.empty_shopping_cart()
    CI.go_home()
  def test_ticket_order_day_normal_sepa(self):
    self.assertTrue(CI.order_ticket(ticket='day', age='normal', payment='sepa'))
  def test_ticket_order_day_reduced_sepa(self):
    self.assertTrue(CI.order_ticket(ticket='day', age='reduced', payment='sepa'))
  def test_ticket_order_day_free_sepa(self):
    self.assertTrue(CI.order_ticket(ticket='day', age='free', payment='sepa'))
```

output
```
2015-06-15 18:56:55,982 INFO: Sleeping 0 seconds, please bring the browser with the ERS site loaded to the front.
2015-06-15 18:56:55,982 INFO: 
2015-06-15 18:56:55,982 INFO: - CHANGE TO US-KEYBOARD-LAYOUT -
...
----------------------------------------------------------------------
Ran 3 tests in 223.758s

OK
```

**Comment by PiQuer** [comment]
@smadamit I'm not sure... this is the element that is not found:
![day](https://cloud.githubusercontent.com/assets/1511250/8165947/c9e30e9c-1394-11e5-97f4-483b69370281.png)
Does this checkbox look different on the first vs the second try?

I'm on the tests now of 0.3.62. Sometimes I have an error on a credit card payment because the test system somehow skips the first '4' of the credit card number... I will try to find out why this happens.

**Comment by smadamit** [comment]
Very strange that the day-screenshot is found in the second but not in the first test. But I think it's no bug of the ERS.

**Comment by PiQuer** [comment]
I have this problem too, sometimes an element is not found which lets the test fail. Sometimes it happens because I am not careful and interfere with the mouse, but I'm not sure if this is always the cause. I think some key presses are lost, maybe a pyautogui bug. When I have time I will try to debug this.

Anyway, all tests successful in 0.3.62.

**Comment by smadamit** [comment]
perfect, thanks

**Comment by smadamit** [comment]
I put this issue to the next milestone. We have to retest from time to time...

**Comment by PiQuer** [comment]
In your config file in ~/.ersTestSuite/config.txt, seciton [Config], you could try to experiment with the confidence level, e.g. confidence=0.7 instead of 0.8, maybe then it works on the first try...

**Comment by PiQuer** [comment]
@inbaz All ok in 0.3.66.

**Comment by smadamit** [comment]
0.3.72 -> OK
