### ISSUE TITLE
What happens if somebody scans the QR-Code on a eTicket?

### ISSUE THREAD

**Issue by inbaz** [inbaz/ers#418]
1. not logged in
2. logged in
a) onsite rights
b) admin rights
c) prereg coordinator rights

add a redirectController to be able to manage urls of the form /redirect/<Code>. Inside of the Controller it should be checked wheather the code belongs to an order, package or item. According to this decision we need to be able to redirect to different sites. This decision should only be made if the user already has rights to access the redirect, otherwise there will be a default redirect for users not logged in.

**Comment by inbaz** [comment]
1. redirect to a special page
2. redirect to ERS login page

**Comment by smadamit** [comment]
I pushed this issue to the milestone onsiteReg. I hope you agree...

**Comment by inbaz** [comment]
Nope, this is one of the issue which needs to work at least one single time before I'm ok with putting Matching to live. Afterwards we see problems with this issue which should have been tested while implementing the matching.

**Comment by inbaz** [comment]
@Bone008 can you take care of this as part of the OnsiteReg?

**Comment by Bone008** [comment]
Yes, I will look into it.

**Comment by Bone008** [comment]
Implementation done with the above commit.
- logged in users with onsite rights are redirected to the onsite page
- everyone else is redirected to the EJC homepage (volunteers)

**Comment by inbaz** [comment]
@Bone008 Can you please change the redirect if the user has no rights to the login page?

**Comment by Bone008** [comment]
@inbaz Done. However, the UX could be improved by redirecting back to onsite after the login.
#586 would also improve this.

**Comment by inbaz** [comment]
@Bone008 good idea. I don't know if there is an easy way to append a redirect url to the login route. But that would be nice in many cases.
