### ISSUE TITLE
bug: blank page at order/buyer

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#419]
tested in dev:
- go to home / -> already logged in as tim... (account without orders) -> old session
- put in a gala ticket /product -> product/add/5
- go to cart -> /order
- Continue -> /order/buyer
- bug: blank page

-> Maybe it's the same bug as in #380, #379, #409 This has something to do with my special account! Without being logged in there is no bug.

**Comment by inbaz** [comment]
I need to get deeper into this. I thought I already fixed it with the last change but that seems not so. I did a little change. Maybe this is working already and I added some more debugging output. Please try again.
