### ISSUE TITLE
test server switch to EJA-productive-server

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#42]
We have to switch the test server to the EJA-productive-server well before going live to do some tests at the new server!!!

**Comment by inbaz** [comment]
This is a push for the preprod VirtualHost. :) Would be nice to test on the productive server as early as possible, but take your time to setup all the stuff. Needed:

- VirtualHost
- database
- rights for directory and logs

**Comment by smadamit** [comment]
@staffanu on the subdomain s05 is now the recent version of ers. But I have two problems:
- if you click on a link in the menu your request is handled over https. That's fine for me, but it doesn't work
- the https certificate dosn't work

**Comment by staffanu** [comment]
I believe that the problem might have been that the certificate was for prereg.eja.net, but I set the server name s05.eja.net to protect it from being access by poeple. Protecting by password (as is done now) is of course better.

Anyway, I didn't test a lot, and probably the browser could be convinced to accept the certificate for the incorrect domain, but maybe the javascript engine couldn't.  Hope this is working now.

Staffan

**Comment by inbaz** [comment]
Is there an open todo in this issue? I think all tasks are fixed in issue #42! That's a good sign!

**Comment by smadamit** [comment]
I close it. If there is something new like #173 I will open a new one.
