### ISSUE TITLE
Unable to select buyer in dropdown menu

### ISSUE THREAD

**Issue by philip-n** [inbaz/ers#426]
Got this via mail:

"Ich habe gerade vergeblich versucht, mich auf legale Weise für die EJC anzumelden.
Ich habe:
- Cookies akzeptiert
- einen Buyer angelegt (den die Prereg sich auch gemerkt hat)
- SEPA ausgewählt (was sich die Prereg ebenfalls gemerkt hat)
- Bei den Produkten das Week Ticket angeklickt
- Das Galashow-Ticket für Samstag, 18:00 ausgewählt

Dann habe ich unter "Person" vergeblich versucht, bei der Selectbox meinen Namen auszuwählen. Er war zwar vorhanden, aber das <option>-Tag hatte das Attribut disabled="disabled", also nicht auswählbar.

Also Firebug angeschmissen und von Hand das Attribut gelöscht, dann gings."

Unfortunately, I don't have further information. Will send the mail adress of the registrant to @inbaz for possible further questions.

**Comment by inbaz** [comment]
added an error message which tells the user that it's not possible to add a personalized ticket to a person who has no birthdate set (birthdate can be added in my person list). I answered the mail of him, too.

**Comment by smadamit** [comment]
I am quite sure that's a duplicate ticket to #326

**Comment by inbaz** [comment]
Yes it is, but why should be the date of birth be mandatory for buyers? If a father purchases tickets for his kids and does not attend the EJC himself we do not need his date of birth. Maybe the workflow will change in the future. I think for this years system we can work with what we have.

**Comment by smadamit** [comment]
A feature which leads to confusion ;-) Not the first time...

**Comment by smadamit** [comment]
date of birth as mandatory field = easiest solution

**Comment by inbaz** [comment]
retest this issue

**Comment by inbaz** [comment]
I will solve it in #326
