### ISSUE TITLE
Change 'My Persons' to 'People attending'

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#427]
Feedback from native speaker: "Change 'My Persons' to 'People attending' or something similar - My persons doesn’t really make sense."

**Comment by inbaz** [comment]
Changed it but people attending looks like a menu item where I can see who else will attend the EJC.

**Comment by smadamit** [comment]
as discussed, please change back. We will discuss it after the EJC...

**Comment by inbaz** [comment]
This was already changed back yesterday. Will be on preprod with the next version.

**Comment by inbaz** [comment]
@hattom Can you have a look at this issue. What's the correct english expression when I want to say "jo man, this is my gang"? :)

**Comment by hattom** [comment]
"My Group" could work, but that of course has disadvantages: a) it's not the obvious place to look (group can mean anything, right and b) if there's only one person, then it doesn't look like it applies.

My currect suggestion is "My Attendees", if that makes sense. Q: this will only apply to attendees, right?
"Subtitle" could be "List of attendees I'm managing", or something similar.

Comments?

**Comment by inbaz** [comment]
I didn't change that last year because with My Persons even those who cannot understand english that well know what they find on this menu point. When we change it to My Attendees it's needed to have a synonym in the explanation to get the chance the users understand what they find here. Would "List of persons I'm managing" ok here?

**Comment by hattom** [comment]
persons -> people and then yes.

**Comment by inbaz** [comment]
did that.

**Comment by jolieno** [comment]
To me the sentence 'List of people I'm managing' is a bit strange when i only buy one ticket.

maybe make it in to 'List of people i'm booking a EJC ticket for?

**Comment by jolieno** [comment]
Ok, new option: lets change 'my attendees" in 'personal details'. 
This is what it is and it makes more sence this way. And than we can add the subtitle line 'list of people i'm booking EJC products for'.

Are you guys oke with this?

**Comment by inbaz** [comment]
I implemented that change in 0.4.33 with a small change, but see yourself.

**Comment by inbaz** [comment]
Ah, I didn't see your last comment. I just read mails. @hattom What do you think of "Person Details" for this menu item?

**Comment by hattom** [comment]
Sure.

**Comment by hattom** [comment]
In the subtitle: "i'm" -> "I'm"

**Comment by inbaz** [comment]
done
