### ISSUE TITLE
add the package code on the eTickets

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#429]
We have the order matching code as:
- QR-code -> not for human
- Barcode -> not for human
- little text, as part of the Barcode-Image -> for human hard to read with a bad printer

Please add the order matching code as clear text above the name of the buyer. In same font-size as the name of the buyer.

**Comment by inbaz** [comment]
Set Code of package to top of listing and removed the text under the barcode if it's useless.

**Comment by smadamit** [comment]
please change the color of the code to black -> why? If you print it on a sw-Laserprinter you get light grey which can be due to the interpolation technique of the printer hard to read.

**Comment by inbaz** [comment]
changed the color to black. In the title of this issue is the order matching code mentioned. This is wrong, it's the package code which is printed on the etickets.

**Comment by smadamit** [comment]
You are right!

tested in dev -> OK
