### ISSUE TITLE
implementation of counter

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#43]
missing feature

Make it possible to count all week tickets.
Make it possible to limit all Women T-Shirt with size S.

counters are used to limit the amount of products in the shop and for statistical analysis. Counter can be complex and depend on SQL-queries over several tables in DB. For example:
counter over all selled tshirts
counter over all selled tshirts in red and XL
counter over all weektickets
counter over gala tickets on Friday
etc.
Now you can limit the amount of gala tickets of Friday to 1200 because there are only 1200 seats in the gym...

**Comment by smadamit** [comment]
Andi you wrote: stock keeping with price connection
Why price connection? Let's talk about the implementation soon.

**Comment by smadamit** [comment]
simple workaround for the first step:
- counter in the stats to monitor the gala-show-tickets manually
- un/visible checkbox for ProductVariantValues to deactivate a gala show date manually if necessary

**Comment by inbaz** [comment]
#480 most of this is already implemented, right?

**Comment by inbaz** [comment]
The first throw is done in #480 let's check what's already there and what's really needed for EJC 2016.
