### ISSUE TITLE
bug -> order/checkout

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#435]
0.3.43 -> 
- select payment type in order/payment
- save and continue
- bug see screenshot

![screen](https://cloud.githubusercontent.com/assets/1533081/7961130/beb37d60-0a05-11e5-89be-cbad85e1cdac.png)

--------------------------

maybe fixed in 0.3.44 with #430 ?

**Comment by inbaz** [comment]
fixed in 0.3.44 it was not #430.

**Comment by inbaz** [comment]
fixed in 0.3.45

**Comment by smadamit** [comment]
0.3.45 -> OK
