### ISSUE TITLE
After unlink: redirect to disabled statements

### ISSUE THREAD

**Issue by PiQuer** [inbaz/ers#436]
After unlinking a matched order, one is automatically redirected to the "Disabled Statements" page. In the previous version, one was redirected to the "Manual Matching" page, which makes more sense.

**Comment by inbaz** [comment]
Please add the whole clickroute you did. Since there is the hensel & gretel tool in place, there are breadcrumbs spread out to follow them back to the origin. This is done on a session basis, therefore multiple tabs will break this system at the moment. Please retest again.

**Comment by PiQuer** [comment]
Tested with single session, cannot reproduce. I think this can be closed.

**Comment by smadamit** [comment]
I guess it has something to do with multi-tab-browsing -> #193

We can think about that after the EJC -> #348
