### ISSUE TITLE
SQL error when deleting a csv with matched statements

### ISSUE THREAD

**Issue by PiQuer** [inbaz/ers#437]
On preprod, I have created the bank Big Bucks, uploaded a csv and manually matched my own order to one of the payments. If you try to delete the csv upload, this error appears:

    An exception occurred while executing 'DELETE FROM BankStatement WHERE id = ?' with params [831]:

    SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`erspp`.`Match`, CONSTRAINT `FK_BB9AEA01F7A4125F` FOREIGN KEY (`BankStatement_id`) REFERENCES `BankStatement` (`id`))

**Comment by inbaz** [comment]
Added a warning if there are already matches. So the csv cannot be deleted anymore.

**Comment by PiQuer** [comment]
Preprod is still on 0.3.45. Should I test on dev?

**Comment by inbaz** [comment]
Just wait for the next version on preprod. Dev could be already broken again because I develop another issue. Therefore you never know in which state this system is at the moment.

**Comment by inbaz** [comment]
0.3.47 is on preprod now.

**Comment by PiQuer** [comment]
Works well with EJC bank account, I will test again once #448 is resolved.

**Comment by PiQuer** [comment]
Works.

**Comment by inbaz** [comment]
You solved #448 yourself, right? :)

**Comment by PiQuer** [comment]
Yes :-)
