### ISSUE TITLE
Stats->Overview->Participants: agegroups missing

### ISSUE THREAD

**Issue by PiQuer** [inbaz/ers#439]
In Stats->Overview->Participants, only "adult" and "U6" is shown, even though also the agegroup 6-13 has the flag "can change price" set in Shop->Agegroup.

**Comment by inbaz** [comment]
@Bone008 Can you please have a look at this issue if this has anything to do with your changes?

**Comment by Bone008** [comment]
Not sure on which server to test this, settings for agegroups seem to differ greatly and I don't have access to preregpp.

What exactly does "can change price" and "can change ticket" do? Which should be displayed in Stats->Overview->Participants?

Currently only agegroups with "can change price" set are shown on the stats page, but __only if the count if > 0__. I just fixed that so 0 counts are shown as well, but will leave it open until I know if that was the problem.

**Comment by inbaz** [comment]
Agegroups are used in two cases:
1. change the price for tickets accordin how old they are. I think a 14 year old teeny already pays the adult price.
2. change the ticket is used to set the agegroup at the top of an eTicket. Here there is the need to use agegroups added by the law U16, U18 and adult. Maybe we add U6 as agegroup here to make the onsiteReg volunteers able to fastly recognize 0 € Tickets.

Agegroups are interesting in both cases, so please add two panels with the according information to a new site Stats->Participants. The ticket agegroup showing just the participant count and the price agegroups showing the count and the amount of money.

Please get the agegroups from preprod, these are still the ones which are live. And maybe add the U6 agegroup.

**Comment by Bone008** [comment]
New statistics page is now on live and have been discussed in last week's group call. The remaining minor changes are not relevant to this ticket and will be tracked in #392.
