### ISSUE TITLE
Check MySQL entities

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#45]
Write a test which creates a functional dataset for each available MySQL entity in this system. The goal of this test should be to test all getter and setter methods of the entity classes. And this test should check if the according Table class is working and the MySQL database is setup correctly.
Item
ItemVariant?
Order
Package
PaymentType?
Product
ProductPrice?
ProductVariant?
ProductVariantValue?
User

**Comment by inbaz** [comment]
I don't think this will happen. Do we really need that or is this a nice to have?

**Comment by smadamit** [comment]
nice to have
