### ISSUE TITLE
order paid but status of items is unclear?

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#452]
tested in 0.3.48

This order is in status paid: admin/order/detail/2015

But why is the status of the week ticket in there "?" -> should be paid to right?

**Comment by inbaz** [comment]
The status unknown is set when the system was not able to find the correct status. I need to go through all orders and set the items to paid, because this was not implemented with the initial setup.

**Comment by inbaz** [comment]
fixed that for auto-matching and manual matching.

**Comment by smadamit** [comment]
test in dev -> OK
