### ISSUE TITLE
logging for matches

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#453]
tested in 0.3.48

This order:
- admin/order/detail/29

was matched with the matching-id 1394. Than I did an unmatch/unlink. And after that did a new match with the id 1396.

Would be nice if you can follow this history in the admin panel. I guess you do not delete the matches in the db when there is an unlink, but deactivate the matches. So you could list all matches, first of all the active one, and after that all old/inactive ones chronology in a table (match-id, who, when, comment) in the order details: admin/order/detail/29

Not a high prio task!

**Comment by smadamit** [comment]
I guess it's much more important than I thought first. This solves also #464

**Comment by inbaz** [comment]
No, I'm really deleting all matches. I don't know if there needs to be anything unique in the matching so it's not possible to just disable them instead of really delete them. But I like the idea.

**Comment by inbaz** [comment]
Matches aren't deleted anymore and in the overview only the active matches are displayed. A page with the disabled matches will be part of the next release.

**Comment by smadamit** [comment]
I can only test it if the history is implemented too. I push it to the next milestone.
