### ISSUE TITLE
why was it not matched by the auto-matching?

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#454]
tested in 0.3.48

see: admin/matching/unlink/1401

**Comment by inbaz** [comment]
Was this a single example or are there multiple not matched orders like this?

**Comment by smadamit** [comment]
I didn't searched for more examples. So I don't know yet...

**Comment by inbaz** [comment]
In the last run really all of the iPayment statements were matched. Therefore this is no issue anymore.
