### ISSUE TITLE
cancelled order in matching-modul

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#455]
0.3.48

Why is the canceled order YR4P9816 shown in the matching-modul: admin/matching/manual I think you can filter orders like this put of the list.

**Comment by inbaz** [comment]
filter for status of order instead of existence of a matching entry.

**Comment by inbaz** [comment]
filtered cancelled and refund orders out of this list.

**Comment by smadamit** [comment]
0.3.50

order YR4P9816 is in status cancelled, but in the left list in admin/matching/manual
Please have another look to this.

**Comment by smadamit** [comment]
retest in dev -> OK
