### ISSUE TITLE
add a pagenator for admin/matching

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#457]
0.3.48

To limit the time of loading for admin/matching just show the last 50 matches. Normally you only need the last few matches. Add a paginator to jump to older matches. To find one special match you need the possibility to "show all matches in one page" -> than you can search with the search-function of the web-browser.

low prio task.

**Comment by smadamit** [comment]
Now it's a high prio because of #485

**Comment by smadamit** [comment]
and we need the search feature #463 because loading all matches fails due to the memory limit

**Comment by inbaz** [comment]
I needed something to get warm with. Therefore the paginator on this page is there. :) Can you please explain the search function in a new issue? What do you want to search for?

**Comment by smadamit** [comment]
0.3.54 -> OK

paginator is perfect!

search issue is here #463 -> I will give more details there later...
