### ISSUE TITLE
payment method in admin/matching and admin/matching/unlink/1405

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#458]
0.3.48

just delete the first row "bank transfer". It's hard coded text, no var and sometimes wrong. Makes no sense... Please change it in:
- admin/matching
- admin/matching/unlink/1405

![screen](https://cloud.githubusercontent.com/assets/1533081/8146101/c52792ac-1226-11e5-96b4-fee4202df253.png)

**Comment by inbaz** [comment]
removed the line on both sites.
