### ISSUE TITLE
enhancement of the order / item / package codes

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#459]
I think we tried to produce odes which do not include chars which can be confusing. So there should be e.g. no "0" or "O". As it is implemented now I guess you check this only for the first 6 chars, but forgot to check it also for the 2 validation-chars at the end of the codes. So there is e.g. the order-code: U53Y2H00

**Comment by inbaz** [comment]
Even if it's after EJC. I checked the function and it normalizes the whole code. Normalization goes everytime into the digit direction so if there's a letter which looks like a digits it's converted into the digit. Can you tell me which error you see with this code?

**Comment by inbaz** [comment]
I checked that the normalisation is done over the whole code, even the checksum.
