### ISSUE TITLE
warning for Bank transfer fees

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#46]
put in a big warning when people in UK, USA & AUS select Banktransfer, as the transfer fees can get up to 30 eu.

-> find a good point for this message

**Comment by inbaz** [comment]
Can this already be solved with payment type short description and payment type explanation?

**Comment by smadamit** [comment]
Yes I think so, but we have to keep it in mind!

**Comment by smadamit** [comment]
@jackcaveman Do you think this is OK?

you have to choose the payment type:

![screen1](https://cloud.githubusercontent.com/assets/1533081/6671060/03885d98-cc03-11e4-8ecb-e62f1d70329b.png)

There is no warning for USA, ...

You are in the checkout and have to click buy now. And you have the red warning.

![screen2](https://cloud.githubusercontent.com/assets/1533081/6671070/1de0761c-cc03-11e4-8407-f53c53e2e319.png)

Is this for you enough? Can I close the issue?

**Comment by jackcaveman** [comment]
@smadamit From your text I gather that the 25 euro is added as a fee to the
order amount. If that is the case, I am happy with this.

**Comment by jackcaveman** [comment]
I have run through the bank statements and the one that is a bit odd is Georgia (next to Turkey). 
There is 5 euro deducted from EJA account by OUR bank to receive the transactions. 
In some case THEIR bank also charges a fee when transferring to foreign country so the amount we receive is lower than expected.
This is just 3 cases, i suggest to add the warning and fee also the Georgia. We can provide refund onsite if they paid too much in the end.

**Comment by inbaz** [comment]
Aren't there bank accounts in other countries, too? So we could add other bank accounts to let the user transfer the money to an account in their own country.

**Comment by jackcaveman** [comment]
There were 10-15 bank accounts all over Europe. These are all closed now
with the coming of SEPA. Georgia does not have enough jugglers coming to
the EJC to open up a bank account there.

**Comment by smadamit** [comment]
let's discuss it in skype.

**Comment by jackcaveman** [comment]
Appearently UK is a SEPA-member, but not many UK people use bank transfers and prefer to send checks my snail mail. (or they are forced by Ron the Rep to buy a ticket on the spot at the BJC).
I have checked with the  bank statement and the UK payments are coming through without any fees deducted.

@smadamit suggestion:
Important note: Bank transfers from USA, Australia and other <a href="http://www.abnamro.com/en/clients/sepa/countries/index.html">non-SEPA countries</a> are really expensive and fees can rise up to 25 euro! You are responsible for paying the fees for the transfer. Check with your bank for the current fees. Paying with credit card or transferwise might be cheaper.

**Comment by inbaz** [comment]
On the discussion yesterday @jackcaveman said that there are even fees for the recipient which maybe the participant needs to pay onsite. Let's find an easy to handle solution for both sides (seller and purchaser)

**Comment by smadamit** [comment]
@jackcaveman can you please add one more sentence and mention that EJA-bank-fees of such a transfer have to be paid onsite.

@inbaz I opened a new issue on that #211

**Comment by smadamit** [comment]
@jackcaveman have a look to: #233

**Comment by smadamit** [comment]
I close it. All further comments to this: do it in #233
