### ISSUE TITLE
do half-matches in the auto-matches

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#461]
0.3.48

If the match is not 100% in the auto-matching there should be a half-match which have to be proven manually. E.g. the code is correct, but not the amount of money. This is a new feature.

**Comment by inbaz** [comment]
You mean do the match but leave the order in status unpaid?

**Comment by smadamit** [comment]
yes

**Comment by inbaz** [comment]
That is done now AND the code search was enhanced.

**Comment by smadamit** [comment]
you tested it? I am asking, because there are no auto-matches with status unpaid in dev -> admin/matching Just close it if you are sure it's working...
