### ISSUE TITLE
bug in admin/matching/manual

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#462]
0.3.48

From time to time I try to match one order and one payment but it does not work. I do not land on the page where I have to confirm the match but on admin/matching/manual again. I can not control the bug it just appears from sometimes.

**Comment by inbaz** [comment]
This is because the form was let open too long. Therefore the form hash key doesn't fit anymore. An error message is shown on this site now if this happens. Simply reload the page and redo what you've done.
