### ISSUE TITLE
admin/order/detail/1543 show all matching infos

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#464]
similar to #453

Show all match infos in admin/order/detail/1543 like in admin/matching/unlink/1409. At the moment you see in Payment Detail: Total amount:	240,00 € You can think: "Oh it's paid". But it's not, because the amount which was transferred is only 120 €!!!

**Comment by inbaz** [comment]
Show matching detail in payment detail panel.

**Comment by inbaz** [comment]
done, *sigh* found out that credit card payment gets matched the wrong way, because there are statements which resulted in an error.
