### ISSUE TITLE
matches

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#465]
0.3.48

- I did this match: admin/matching/unlink/1405
- The order stays unpaid: admin/order/detail/3

But I expected that it would be status paid. Now I understand why not -> the amount of money is not fitting.

I think we should change this like this. You select the items which should be matched. Than you get the confirmation page and you have to comment why you like to match it. Now you have 3 options:
- cancel: You abort your action
- match: You match the orders to the payments and you want to set the orders to status paid
- half-match: You want to match the orders to the payments, but the amount of money does not fit. You are waiting for more incoming money to match. So the status is stays in unpaid.

See also: #461

**Comment by inbaz** [comment]
Check if 0.3.49 does what you want.
What to do if form input is set to partially paid but the amount is ok for the order? Set the order to paid or leave it unpaid?

**Comment by smadamit** [comment]
yes fine.

To your question: I am not sure... I would say unpaid, maybe the prereg-coor has something in mind when he does it.

Little enhancement. No radio-buttons for status paid and unpaid. Just two submit-buttons:
- green: "full-match" or "match as paid"
- yellow: "half-match" or "match as unpaid"

What do you think about that?

**Comment by inbaz** [comment]
done
