### ISSUE TITLE
check all features in admin/order/detail/1 and deactivate all we don't need yet

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#467]
0.3.48

check all features in admin/order/detail/1 and deactivate all we don't need yet

**Comment by inbaz** [comment]
Or which are not ready, yet. :)

**Comment by inbaz** [comment]
I had a look at all menu items and removed the ones which are not needed anymore and disabled the ones which are not implemented, yet. There is one exception: Send E-Tickets is not implemented, yet, but will be implemented for the next release.

Please be patient when testing the send E-Tickets menu Item, the E-Tickets will be really sent to the participants, even on the testing machines.

**Comment by inbaz** [comment]
checked all menu items and disabled the ones which are not implemented, yet.
