### ISSUE TITLE
design of status: unpaid -> yellow or red

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#469]
0.3.49

give the status div-box a red or yellow background if the status is not paid (grenn) but unpaid.

change here:
- admin/matching
- admin/matching/unlink/1405

maybe you can add these status in same design here:
- admin/order/detail/3
- order/view/85H97MAX....

**Comment by smadamit** [comment]
see like it is done in #286

**Comment by inbaz** [comment]
I implemented the colored status in admin/matching, admin/matching/unlink/123 and order/view/XYZ. I had no idea how to show that nicely on the order detail page. Maybe we should reopen a new ticket with "redesign order detail page" and include this last issue.
