### ISSUE TITLE
Set nationality for persons/participants

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#47]
Set country as default after first selection

When a participant was created the chosen country should be held in the session to set this country as default for the next participant creation.

**Comment by smadamit** [comment]
v 0.2.9: If you create a new person, you have to select: "where are you from". So what I mean, the nationality is not important, it's just statistics and we want to know from which countries the jugglers come.
I like it!

**Comment by inbaz** [comment]
In 0.2.19 I did some major changes on this topic. Countries can be ordered in the admin panel, so at the moment there are five countries which are displayed at the top and the rest of the list is displayed below in alphabetic order.

**Comment by smadamit** [comment]
Good!

two little suggestions:
- participant/add: don't preselect the first country, but select an empty select. This prevents that there are much more Italian selected than there are in reality.
- admin panel menu: put country as submenu to shop.

what do you think?

**Comment by smadamit** [comment]
v 02.19

Got a second time this bug:
- admin/country/edit/153: "Message: Params is expected to be an array or a Traversable object"

But can't reproduce the bug.

**Comment by inbaz** [comment]
I fixed that bug in 0.2.20. This error occurs when Hensel and Gretel were in the forrest but did not spread out breadcrumbs, so they cannot find their way back. :)

**Comment by smadamit** [comment]
Ah I understand :-) Seems to be fixed.

**Comment by inbaz** [comment]
Oh, I missed the point to move the country menu item to shop. This will be there in 0.2.21.
