### ISSUE TITLE
little enhancement: Accept match

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#471]
tested in dev

low prio and minor change. Little enhancements in admin/matching/accept?statements...
- swap the two buttons: "match -> unpaid" and "match -> paid". Than you have there links to click in a order of: 1) best and most frequent case 2) rare and not perfect 3) cancle
- give the sum of the amounts after: "orders for this match" and "statements for this match". Than you can see in one second if the sum of the orders and the sum of the payments fit or not. You can even give a color code for this two sums. Make them green if they fit, red if not.

**Comment by inbaz** [comment]
I like the idea to have the sum at the bottom. This was really simple it's implemented. Let's discuss the order of the buttons after ejc.
