### ISSUE TITLE
admin/order/detail -> show match info

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#472]
tested in dev

show in the "Payment Detail" in admin/order/detail the match info like: match-id, who matched, etc. And you can even add the functionality to unlink a payment from the order.

So in principle just like in admin/matching. Example for admin/order/detail/251

now it looks like this:

![screen1](https://cloud.githubusercontent.com/assets/1533081/8116176/d97a0336-1080-11e5-87c0-d10c038d2003.png)

suggestion:

![screen3](https://cloud.githubusercontent.com/assets/1533081/8116196/ea8d754a-1080-11e5-9e32-f51bb66843cb.png)

Maybe instead of just "unlink" better "unlink payment from order"

As already mentioned in #453 you can list the disabled matches to the order at the end but in grey.

**Comment by smadamit** [comment]
One more idea. Show the sum of all payments anywhere. Maybe on the top of the table "payment details"

**Comment by inbaz** [comment]
check in 0.3.68

**Comment by smadamit** [comment]
looks nice, but:
- unlink does not work. The action has no effect. Ups, maybe it's working but this bug is the problem: #539
- if you unlink and confirm or cancel the action you get directed here: admin/matching Should be here admin/order/detail/...

**Comment by smadamit** [comment]
0.3.75 -> OK
