### ISSUE TITLE
status of the order

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#475]
let's think about the status of an order. Maybe in a short call...

At the moment you can set the status of an order e.g. from unpaid to paid, or from paid to refund, etc. The system will set the status of all items of the order to the same status right?

Now if you set the status of one item, this will in general not change the status of the order. But what if there is only one item, or if you set all included items of one order to a new status. Should the order change is status too? Or is this the task of the admin-panel user to check this?

Same issue for packages...

**Comment by inbaz** [comment]
Can we move this issue? How often will this happen that items will be put into a different state and how often will this happen that all items of a order will be changed separately without cancellation of the whole order but cancellation of each item?

**Comment by smadamit** [comment]
Yes sure, I put it to GoLiveMatching because I wanted to discuss it now. We solve it later. Let's talk in the SkypeCon...

**Comment by inbaz** [comment]
TODO: remove order status in database + implement functions to calculate status out of packages
