### ISSUE TITLE
confirm for manual sending of eTicket

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#479]
There is the function to manual send the eTicket to an order or an package by email to the buyer/participants. Not 100% implemented yet, but please add a confirmation page where the admin-panel-user have to confirm that he/she really wants to send the eTicket manually to avoid mistakes. AND deactivate this feature for orders which are in status unpaid!

**Comment by inbaz** [comment]
move the part of enabling the function only for paid orders to #489

**Comment by inbaz** [comment]
This confirmation is already prepare like on all delete pages.

**Comment by smadamit** [comment]
And don't forget when you implement the manual send feature, that only etickets to packages which are in status paid will be send... It's clear, but... So there can be an order with status paid, but several packages where some of them are not in status paid!

**Comment by smadamit** [comment]
0.3.71 -> OK
