### ISSUE TITLE
email warning if there are more than X tickets of the gala show sold

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#480]
We need a email warning if there are more than X tickets of the gala show sold

@inbaz What do you think about this idea?

**Comment by smadamit** [comment]
@Bone008 This feature became a very high prio issue. Are you able to think about a solution soon. Which ticket and what is the limit -> via Skype or email...

**Comment by Bone008** [comment]
@smadamit 
* How much configuration should be possible for the feature in the AdminPanel?
A setting for each product variant (= show day) to set the threshold?
Or is this just a temporary hack and just hardcoding some values would be enough?

* Who are the recipients for the e-mails? Hardcoded? supradm? Configurable?

(See skype as well)

**Comment by smadamit** [comment]
see my answer in skype

**Comment by inbaz** [comment]
If we have a solution that is that performat to run it every time a user loads the product page it would be nice to enable/disable options according to this. We already have multiple example on how the sites for the Counters can look like in the AdminPanel. Therefore I don't like the idea to just send an email but set the visible status for a specific product variant value.

**Comment by smadamit** [comment]
I am also fine with your solution. But we need a solution.

**Comment by Bone008** [comment]
@smadamit I implemented the feature the way @inbaz suggested (automatic checking whenever the /product page is loaded and then disabling the show day). The threshold is not yet configurable in the AdminPanel, but I'm planning on adding that.

An email warning/notice could also be added in a second step, maybe after a percentage of that threshold has been reached?

**Comment by smadamit** [comment]
That's enough for the moment!

**Comment by Bone008** [comment]
@smadamit The limits are now configurable in the admin panel as well (Shop > Counter). The changes still need to be merged by @inbaz, then you can start testing. (see 76a4dae96025023fdc50e3b9d7f78359f3599034)

Screenshot:
![screenshot_4](https://cloud.githubusercontent.com/assets/830913/8317894/ed12e7da-1a00-11e5-96b2-fc64e93f61e4.png)

*Note for the future: In the backend, multiple variant values per counter are supported. This could become necessary when they start being used for t-shirts, which could e.g. have a variant combination of size&color, for which you need to set a limit counter.*

**Comment by smadamit** [comment]
OK, I will test when it's merged.

"Note for the future: In the backend, multiple variant values per counter are supported...." -> see also #80

**Comment by inbaz** [comment]
merged in 0.3.68

**Comment by smadamit** [comment]
tested on preprod 0.3.72 -> is not working...

**Comment by smadamit** [comment]
@Bone008 Just  have a look for your own on preprod. You can set the counter, but the products are not set to invisible if the counter is reached.

**Comment by Bone008** [comment]
@smadamit The internal counter values and the numbers shown in Statistics>Participants unfortunately do not match, because cancelled orders are still counted by the statistics, but not by the disabling module.

Right now, there seem to be 2 cancelled/refunded gala tickets for Friday on preprod. I ordered one more, then the disabling happened.
Stats page shows 1247 tickets now, the counter is set to 1245. The stats are wrong, I will fix them.

**Comment by smadamit** [comment]
OK, that's fine! One short question: If the counter is set to 1000 and there are 999 tickets sold. Than the next buyer can buy 5 tickets in one order. That's OK, because I consider an additional buffer for the limits.

Just to confirm, I am pretty sure you implemented it like:
```
if($count > $limit){
   set_ticket_inactive()
}
```
and not
```
if($count == $limit){
   set_ticket_inactive()
}
```

**Comment by smadamit** [comment]
skype -> OK
