### ISSUE TITLE
filter payments: errors for ipayment and negative ones for sepa

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#481]
filter payments in the csv-uploads:
- errors for ipayment
- negative ones for sepa

**Comment by inbaz** [comment]
Yeah, there are two new fields in format of a bank account now. Please check out if the names of the fields are already self explaining in 0.3.54 on preprod. If you encounter duplicate key errors, please delete all csv files and reload them again. If I should do it with a small script (already written), reassign this ticket to me again with the request for that. I don't want to delete your test data without asking.

**Comment by smadamit** [comment]
OK, I think I understood.

Got this exception:

```
An exception occurred while executing 'UPDATE BankStatement SET hash = ?, updated = ? WHERE id = ?' with params ["a2c88504c1d625c1686cb9f8f03acb7b", "2015-06-13 23:53:41", 2]:

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'a2c88504c1d625c1686cb9f8f03acb7b' for key 'UNIQ_EED4C7C7D1B862B8'
```

You can destroy all data and we start from the beginning if you want. My tests with the current preprod data are finished.

**Comment by inbaz** [comment]
Yesterday I loaded the prod data, all database changes for the new version were done quite well from the live database status. Please retest.

**Comment by smadamit** [comment]
0.3.62 -> tested with live data for credit card and sepa -> OK
