### ISSUE TITLE
sending of eTickets for credit card

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#482]
When will the etickets of orders, which are sold by credit card, be sent? Can this mail go out just after the successful order or is there are risk that the payment is not successful even if the ipayment said OK? So should this mail with etickets go out after the matching process?

**Comment by inbaz** [comment]
There is no problem. When the iPayment System says it's paid, then it's paid. The only problem we have is to match orders where birthdates have been changed, because we are not able to ask the iPayment System again if this order is paid. This is wha the iPayment csv export is needed.
