### ISSUE TITLE
bug: admin/matching is empty

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#485]
0.3.51

See on preprod admin/matching -> empty list

**Comment by inbaz** [comment]
I don't understand, can you give further info? If there are no matches this list will be empty. There was a problem with the execution time on the server I already fixed. What exactly do you see?

**Comment by smadamit** [comment]
There are several payments which are empty or partly empty. See the screenshot the disabled empty payments:

![screen](https://cloud.githubusercontent.com/assets/1533081/8144590/954279da-11e5-11e5-8cf1-af1efc1ace4b.png)

Ups, but this is very low prio.

**Comment by smadamit** [comment]
retest in 0.3.52 -> now it works

**Comment by smadamit** [comment]
retest in 0.3.53

-> blank page, maybe server timeout?

**Comment by inbaz** [comment]
found this bug: memory limit exceeded. We should try to get a pagination or at least only some of the results as fast as possible. Would be 50-100 enough?

**Comment by smadamit** [comment]
I would LIMIT the result to 100. Later we can take care about this issue again. We have the solution already in #457

**Comment by inbaz** [comment]
Solved it with results of 50 and a paginator. 50 is a good number where the page load time is still quite fast.

**Comment by smadamit** [comment]
0.3.54 -> OK
