### ISSUE TITLE
deactivate "send e-ticket" function for orders in status unpaid

### ISSUE THREAD

**Issue by inbaz** [inbaz/ers#489]
deactivate "send e-ticket" function for orders in status unpaid

from #479

**Comment by inbaz** [comment]
Please check in 0.3.54

**Comment by smadamit** [comment]
0.3.54

If the order is in status unpaid you can still send an eticket of a package (in the submenu of "Package") -> this should not be possible

**Comment by inbaz** [comment]
Should be fixed in next version.

**Comment by smadamit** [comment]
0.3.71 -> OK
