### ISSUE TITLE
welcome site

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#49]
The landingpage should be a welcome site where is explained how the pre registration works.

**Comment by inbaz** [comment]
Is this already solved?

**Comment by smadamit** [comment]
@christianbross For me the text of the home site is fine. Do you have any improvements? If you have, post it here and assign the issue to inbaz. Otherwise close the ticket.

**Comment by christianbross** [comment]
Version 0.2.39
Proposed text changes:
1) This site provides a shop to purchase ticket for the EJC 2015.  --> change ticket into tickets
2) You can take a look at the product list --> Browse the _product list_ to select your ticket(s)
3) Your shopping cart shows the chosen products +add text+ , and is the first step to check out and pay.
All the rest is good. :-)

**Comment by inbaz** [comment]
Changed in 0.2.46, please recheck
