### ISSUE TITLE
No confirmation mail is sent.

### ISSUE THREAD

**Issue by PiQuer** [inbaz/ers#491]
Version 0.3.52.

I did not receive a confirmation mail for any of the orders.

**Comment by smadamit** [comment]
manual retest in 0.3.52

See screenshot, I guess this is the problem. This is the page a got after clicking on "buy now":

![screen](https://cloud.githubusercontent.com/assets/1533081/8144507/887b76e6-11e2-11e5-8285-6600d95cf07f.png)

**Comment by PiQuer** [comment]
Yes, this is #490

**Comment by PiQuer** [comment]
Fixed in 0.3.53, which is no on preprod.

**Comment by smadamit** [comment]
it's working...
