### ISSUE TITLE
SQL error when ordering as logged in user

### ISSUE THREAD

**Issue by PiQuer** [inbaz/ers#492]
Version 0.3.52.

On checkout when trying to buy a week ticket, as logged in user:

![error](https://cloud.githubusercontent.com/assets/1511250/8144536/72cb7bba-11e3-11e5-9d26-484c959981a0.png)

This is right after 'buy now'.

**Comment by PiQuer** [comment]
Seems to be fixed in 0.3.53, cannot reproduce this anymore.

**Comment by inbaz** [comment]
I saw the exceptions and fixed it. This also should happen as not logged in user.
