### ISSUE TITLE
maybe a bug? duplicate payments in the db?

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#494]
0.3.52

See for example: https://preregpp.eja.net/admin/order/detail/1249 (It's the same for all matches I checked)

There are two equal payments and I am pretty sure they are duplicates. Is it a bug in the csv-Upload?

**Comment by smadamit** [comment]
see my email for the csv-file I uploaded

**Comment by inbaz** [comment]
This is caused by a change of the layout of the csv file.

**Comment by smadamit** [comment]
I guess you have no clue why the csv format has changed

This is serious, you implemented the csv-upload under the assumption that the format does not change. There are two questions coming in my mind:
- will this happen again?
- is there a solution how to handle such a case. My first idea: Add a confirmation if there were no duplicates found, except it's the first upload: "There are no duplicate payments in the csv data. Are you sure the format of this csv file is correct?". In  general there are always overlaps, so there should be duplicates.

@jackcaveman Can you please comment this issue.

**Comment by smadamit** [comment]
@inbaz  suggestion, let's put this issue to milestone Matching. Than we have to check the format manually before uploading for now...

**Comment by smadamit** [comment]
I guess this will fix also #484

**Comment by jackcaveman** [comment]
The Bank changed the filename of the csv exports at the beginning of the month. I did not expect them to change the format as well. My guess is that is should be stable now, but there are no guarantees as its not an ISO standard.

**Comment by smadamit** [comment]
OK good to know what happened

**Comment by smadamit** [comment]
I want to think about this issue again after the EJC. For 2015 this is solved.

**Comment by smadamit** [comment]
I close this and open a new issue to that.
