### ISSUE TITLE
change color/design of test-systems like preprod

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#496]
Sometimes I am really afraid, that I swap prod and preprod. What about a automatic detection of the prod-server and change the design (background-color, or change the CI green to a red color) for all test-systems (preprod, dev, etc.). Detection could be the productive domain: "www.eja.net", for all other domains it have to be a test system.

@inbaz What do you think about this? I do it in a similar way for some of my projects.

**Comment by inbaz** [comment]
I already thought about an environment variable which can be set in the webserver configuration. Color code is a great idea. I mainly thought about this function to know where to send emails to. :)

**Comment by smadamit** [comment]
emails, yes also a good point!

**Comment by inbaz** [comment]
I realized that with environment variables for dev and preprod. I tried to set "production" as environment which hides the message at the top.
