### ISSUE TITLE
refund -> undo refund gives 404 error

### ISSUE THREAD

**Issue by PiQuer** [inbaz/ers#499]
Version 0.3.54.

Any order (I used NV2M2U26) -> Detail -> Tools -> refund -> Yes -> Tools -> undo refund gives a 404 error. The status is still refund afterwards.

One can undo the refund by canceling the order and then uncancel it again. After that the status is "ordered".

Or one can use Status->Unpaid to reset the refund.

**Comment by inbaz** [comment]
fixed
