### ISSUE TITLE
[fix before test] List of all orders in the system

### ISSUE THREAD

**Issue by jackcaveman** [inbaz/ers#5]
This feature is required for testers to have a look whether the data that they entered is stored correctly in the system.

**Comment by inbaz** [comment]
In the backend of actual git master there is a list of order where you can see who has ordered this and the amount of the order. Would be great if you can give me a list of fields that you expect in this table.

**Comment by jackcaveman** [comment]
Essentially you want to check all the data that the testers have entered.
Whether that is in one list, or some page. For example if you have list of
all orders, with basic fields such as payment status, name of the buyer,
order date. you can then link to pages where you can view the full order
(such as during checkout), so we can check participant names/birthdates,
tshirt sizes etc.

**Comment by inbaz** [comment]
There is a order list in the backend now and you can view details on each order.
