### ISSUE TITLE
set-up the starting shop configuration

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#50]
set-up the starting shop configuration like it should be at golive. At least a week before.

**Comment by smadamit** [comment]
@inbaz If I want to set-up the starting configuration like it will be on going live. How should we do that? Would be nice to start with tabula rasa in the admin panel.

**Comment by inbaz** [comment]
Should we just setup a preprod instance to be able to configure the system at it will go live in there? I think I will take a mysqldump of this instance and bring it to production once we're ready. What do you think?

**Comment by smadamit** [comment]
That would be nice!

**Comment by inbaz** [comment]
@smadamit You got mail. I'll give this ticket to you.

**Comment by smadamit** [comment]
see also: #134

**Comment by smadamit** [comment]
**country sorting**

for country sorting we will take the first 5 of the following list:

**prereg EJC 2011**
	
nr | country | participants
----|-----------|----------------
1 | German | 3490
2 | French | 594
3 | Italian | 369
4 | Austrian | 270
5 | British | 249
6 | Swiss | 179
7 | Dutch | 176
8 | Belgian | 129
9 | Spanish | 89
10 | Czech | 62
11 | Us-american | 62
12 | Irish | 57
13 | Polish | 52
14 | Swedish | 37
15 | Japanese | 36

**Comment by smadamit** [comment]
first iteration done

**Comment by smadamit** [comment]
-> OK
