### ISSUE TITLE
Details page for Gala Show Ticket not working

### ISSUE THREAD

**Issue by PiQuer** [inbaz/ers#500]
Version: 0.3.54.

For example: admin/order/detail/2137

![bug](https://cloud.githubusercontent.com/assets/1511250/8148331/5bc1afb0-1298-11e5-8b1d-7e952ea86fec.png)

**Comment by inbaz** [comment]
This has nothing to do with the gala show ticket. You managed it to add a user without a date of birth. I'm checking for a correct date of birth before showing it on the details page. This solves the problem.

**Comment by PiQuer** [comment]
Yes: order a gala show ticket, don't add a person but select the age group by radio button, continue to checkout, add a buyer. No birthday asked in this input form.

**Comment by inbaz** [comment]
Ahja, perfect, so this is solved when I'm not displaying the date of birth anymore if there is none.
