### ISSUE TITLE
Order details: mismatch between status on search page and status on details page

### ISSUE THREAD

**Issue by PiQuer** [inbaz/ers#501]
Version 0.3.54.

Orders with credit card payment are marked as "paid" on the order search and in the title of the order detail page. However the status on the detail page is "ordered".

For example: admin/order/detail/2134

Is this a bug?

**Comment by smadamit** [comment]
Not sure.

@inbaz let's talk via phone. It depends on my question: #482

**Comment by inbaz** [comment]
The order 2134 is marked as unpaid in search and detail. Can you please recheck?

**Comment by PiQuer** [comment]
Probably I changed the status manually on this one... Any unaltered credit card payment, for example HV53HA99, order 2149.

**Comment by inbaz** [comment]
Ah, you mean the status of the item, right? The status of the order is paid on both sites, however the status of the item is ordered, that's not correct.

**Comment by inbaz** [comment]
Please recheck in 0.3.56

**Comment by PiQuer** [comment]
Yes, the item is what I meant.

**Comment by PiQuer** [comment]
It's still the same in 0.3.56, for example HV53HA99, order 2149. Item status is still 'ordered', or am i missing something?

**Comment by inbaz** [comment]
No, not just look at the order detail page, but do a new order and check if the status are still wrong. Only correct it in the database would not solve the problem. Keep in mind that all data in preprod and dev a not real and can contain errors at any time.

**Comment by PiQuer** [comment]
With a new order the status is indeed correct.
