### ISSUE TITLE
Error when trying to send E-Ticket

### ISSUE THREAD

**Issue by PiQuer** [inbaz/ers#502]
Version 0.3.54.

On a paid order (paid by credit card), sending the E-Ticket via Order->Send E-Tickets gives a 404 error page.

For example: admin/order/detail/2134       Order->Send E-Tickets

Also for other orders (paid or unpaid), trying to send the E-Ticket via Package->Send E-Ticket gives an error: 

    Zend\View\Renderer\PhpRenderer::render: Unable to render template "admin/package/send-eticket"; resolver could not resolve to a file

Is this a bug or not implemented yet?

**Comment by smadamit** [comment]
not implemented yet
