### ISSUE TITLE
Order details: credit card payment can be marked as 'unpaid' with no way back

### ISSUE THREAD

**Issue by PiQuer** [inbaz/ers#504]
Version 0.3.54.

One can mark a credit card payment as "unpaid", but cannot revert this step. Does the auto-match run also include credit card payments? Otherwise there is no way to mark such an order as paid again.

**Comment by smadamit** [comment]
yes the cronjob will set it to paid again if the amount of money is OK. Even for credit card.

@inbaz Am I right? Please close the ticket after a short comment.

**Comment by inbaz** [comment]
After the iPayment CSV is uploaded, yes, that's correct.
