### ISSUE TITLE
Recalculate price of day ticket: date is deleted

### ISSUE THREAD

**Issue by PiQuer** [inbaz/ers#505]
Version 0.3.54.

To reproduce: Order a day ticket, in the order details change the age to under 16, recalculate the price. The result can be seen here: admin/order/detail/2133

There is a canceled day ticket with a date and a new day ticket without a date. Probably as a result of this bug, when you try to download the e-ticket via Package->Download E-Ticket, it is not a PDF but a HTML page which is generated, with some ill-encoded characters in it (for "regular" day tickets the pdf generation works fine).

**Comment by smadamit** [comment]
already reported here #320

**Comment by inbaz** [comment]
Please test in 0.3.58

**Comment by PiQuer** [comment]
Works in 0.3.62.
