### ISSUE TITLE
Gala Tickets not personalized -> agegroup stored in database?

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#509]
is the agegroup of a Gala Tickets which is not personalized stored in database?

See screenshot. It's not clear, but this gala ticket is unpersonalized with agegroup adult.

![screen](https://cloud.githubusercontent.com/assets/1533081/8149664/e55c8a3c-12cb-11e5-8895-47365bd6f368.png)

**Comment by inbaz** [comment]
No, the agegroup is not saved in the item. The price gets calculated once and is saved into the item. That's it.

**Comment by smadamit** [comment]
we have to think about that after the EJC
