### ISSUE TITLE
bug: blank page for admin/bankaccount/upload-csv

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#512]
0.3.57

not able to upload csv for credit card -> blank page after upload...

**Comment by smadamit** [comment]
maybe a server timeout or memory limit?

**Comment by smadamit** [comment]
in 0.3.58 -> no blank page, but upload fails and I get back to admin/bankaccount

**Comment by smadamit** [comment]
0.3.58 -> no again blank page for credit card bank account

**Comment by inbaz** [comment]
please retest in 0.3.60. The problem was the check to disable the statements without format set. That was not possible - should be now.

**Comment by smadamit** [comment]
OK
