### ISSUE TITLE
bug: blank page for admin/bankaccount/format/2

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#516]
0.3.60

-> blank page after defining the format of the csv of credit card

**Comment by smadamit** [comment]
same for admin/bankaccount/format/7

**Comment by inbaz** [comment]
fixed in 0.3.62

**Comment by smadamit** [comment]
0.3.62 -> not working as expected

Test for admin/bankaccount/format/8

- first upload OK
- define format OK
- second upload: all payments have been deactivated -> admin/matching/disabled

**Comment by smadamit** [comment]
0.3.62 -> OK for credit card and sepa csv
