### ISSUE TITLE
auto-matching: YKX1X239 should be in status paid, not unpaid

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#520]
0.3.62

admin/order/detail/1543 (YKX1X239) -> should be in status paid, not unpaid. There are 2 x 120 € to pay and two payments with 120 € matched to the order 2x120 = 2x120. Should be fixed in the auto-matching-script.

**Comment by inbaz** [comment]
fixed in 0.3.64. Please reload all the bank statement things so that I can run the auto-matching again to test.

**Comment by smadamit** [comment]
I unlinked both 120 € payments to the 240 € order, you rerun the automatching script, we see again. OK?

**Comment by smadamit** [comment]
0.3.66 in prod -> OK
