### ISSUE TITLE
admin/matching/manual: CM4WYH44 should be in the manual matching list

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#521]
0.3.62

admin/order/detail/158 (CM4WYH44) ->  should be in the manual matching list. There is a macthing, but with status unpaid. As we discussed here #455 the order of this matching and the payments of this matching should appear in the manual matching module: admin/matching/manual

So all order which are in status unpaid (NOT paid, refund, cancelled, etc.) should be listed in the list on the left-hand side. All payments which are unmatched, or have a match to an order, which is in status unpaid, should be listed on the right-hand side.

**Comment by smadamit** [comment]
see also #477

**Comment by inbaz** [comment]
test in 0.3.64

**Comment by smadamit** [comment]
0.3.65

- the order CM4WYH44 is now listed on the left hand-side -> this was the more important part -> OK
- the payment to this matched but unpaid order is not listed on the right hand side -> open issue

**Comment by smadamit** [comment]
open part of this issue is duplicate to #477
