### ISSUE TITLE
set the correct status of all items in prod

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#527]
For an unmatched order with credit card: order in paid, items in status "?"

e.g. 6CRK9M12 in prod

**Comment by smadamit** [comment]
please run a script on prod to set the correct status of all items (depending on the status of the order). This should be tested before running on prod and it should be done before sending the first eTickets.

PS: At the moment there are many items with status "?"

**Comment by inbaz** [comment]
This is done in the next versions auto-matching script.

**Comment by smadamit** [comment]
0.3.66 in prod

@inbaz tested 10 random orders -> status of the items seems to be set correctly. Do you agree, we can close this ticket right?

**Comment by inbaz** [comment]
this should be done. This has nothing to do with the version of the system but if the according script already run through the items.
