### ISSUE TITLE
remark to the agegroup

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#53]
When you choose the agegroup of a ticket, or you type in the birthdate of a participant, there should be a short remark for the user, that the ticket will only be handed out by showing the ID card -> so the birthdate / agegroup could be checked at the registration.

**Comment by inbaz** [comment]
Please give me a small sentence that I can just copy paste in there and the correct position to add this remark.

**Comment by smadamit** [comment]
I think about it after you have implemented the agegroups

**Comment by inbaz** [comment]
just a reminder. :)

**Comment by smadamit** [comment]
@jackcaveman I hope you understand my intention. Do you have a short and precise formulation for that?

note to the birthdate field in my persons form:
- Please enter the correct date of birth since it will be validated for personalized tickets at the onsite registration by checking the identification card.

**Comment by jackcaveman** [comment]
I don't think a remark will be any clearer, I suggest to change the form as follows:
![image](https://cloud.githubusercontent.com/assets/11071240/6673923/b2821484-cc16-11e4-9a86-1bd5d3677223.png)

**Comment by smadamit** [comment]
I like your notes to firstname and surename. But in my opinion a similar one for the date off birth is also important.

**Comment by inbaz** [comment]
Made an example in 0.2.39

**Comment by smadamit** [comment]
I like it
