### ISSUE TITLE
Statistics: improve display of bank statements

### ISSUE THREAD

**Issue by Bone008** [inbaz/ers#533]
#### Disabled bank statements
Should not be included in the aggregation.

#### Virtual bank accounts
Motivation: "Volunteers" are matched to a single 0€ statement, but it would be handy to see the actual value of tickets for volunteers.
For virtual accounts, sum the order amount instead of the bank statements and display them in a separate view (special case: a volunteer may be part of a bigger order, example: CM4WYH44).

**Comment by Bone008** [comment]
Disabled bank statements are now properly excluded (when the commit above is merged).
The virtual bank accounts part still needs to be done.

@smadamit Is that part also "must have"? If not, please remove the label.

**Comment by smadamit** [comment]
0.3.75 -> very nice

**Comment by inbaz** [comment]
@Bone008 is the open task the idea I send you yesterday via mail?

**Comment by Bone008** [comment]
@inbaz Yes, it is pretty similar.

The complexity of orders being matched to statements from different bank accounts remains to be solved.

(e.g. an order is mostly matched to a bank statement, but also contains one volunteer ticket)

Then the order would be counted twice - and for volunteers it also biases the value for "how much money was spent for volunteer tickets".

Not sure how to solve this the best way ...

**Comment by inbaz** [comment]
By either make it possible to partly match packages or even items to bank statements or split up orders which needs to be matched to different bank accounts.
