### ISSUE TITLE
items with a price >0 but for person with age <6 years

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#537]
In a few orders there are items which have a price >0, but for a person with age <6 years. So the price should be 0. But maybe the persons are really adults? We have to solve this case by case and we should get behind the miracle how this cases were generated.

The concerned order IDs:
- 2091
- 1035
- 1274
- 1283
- 925

IMPORTANT: Are there also other cases. e.g. adults with price for youth or youth with price for adults? Or is it a specific problem for 0€-tickets?

**Comment by smadamit** [comment]
Maybe this can be interesting: #541

**Comment by inbaz** [comment]
Duplicate #541
