### ISSUE TITLE
easy bug: unlinked payments are shown in order detail page

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#539]
I unlinked the two orders of YKX1X239 (for testing #520) and as expected the orders are gone in the match-overview. But they are still shown in the order detail page: admin/order/detail/1543 This is for sure because the matches are not deleted anymore, but deactivated.

By the way, to unlink this two payments to the order I had to click throw nearly all pages of the matching overview. This issue would have made this task very easy: #472

**Comment by inbaz** [comment]
fixed in 0.3.68

**Comment by smadamit** [comment]
test in 0.3.71 -> is not working!

**Comment by inbaz** [comment]
Ah, there is nother status in the match itself. I only used the one in the statement. In 0.3.74 this should be fixed.

**Comment by smadamit** [comment]
0.3.75 -> bug

- unlink a match -> OK
- the order which is now in status unpaid -> OK
- the order is shown in manual matching -> OK

but

- the payment of the old match is gone -> not in manual matching bank transfer list and even not in the disabled bank statements list -> not OK

**Comment by inbaz** [comment]
fixed in 0.3.78

**Comment by smadamit** [comment]
0.3.78 -> bug

- after doing a match -> the order is not shown in the manual matching list -> **OK**. But the bank transfer to this match is shown in the manual matching list -> **not OK**.
- after unlinking the match -> the order is shown in the manual matching list -> **OK**. And the bank transfer to the unlinked match is shown in the manual matching list -> **OK**.

**Comment by inbaz** [comment]
I excluded matched bank statements from the manual matching list. So this bug should be fixed and hopefully there is no new one.

**Comment by smadamit** [comment]
0.3.79 -> same bug

**Comment by inbaz** [comment]
The close was not intended and was triggered by the commit. Can you please test again if it's shown correctly? Maybe we need a more general plan for this issue. Because I think with the solution now it won't be possible to match multiple orders to one bank transfer in multiple steps. But since the cheque payments will be managed by a virtual bank account, I don't think this will be a big problem. But keep that in mind.

**Comment by inbaz** [comment]
Last status is to retest this issue. It's important that this is working correctly.
