### ISSUE TITLE
Put all needed information into bank account to make international bank transfers

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#540]
For international bank transfers you need also an address... Maybe more...

**Comment by inbaz** [comment]
We should provide this information for the default SEPA account next time. Let's try to collect all these information.

**Comment by inbaz** [comment]
I think most of the information is already in the system. Let's see if international bank transfers are possible after GoLive.

**Comment by inbaz** [comment]
I saw a question on prereg@eja.net according this. What are the information that are missing within the website frontend what participants need to to the bank transfer from all over the world?

**Comment by inbaz** [comment]
done
