### ISSUE TITLE
check all texts in e-tickets and in e-ticket mails of all versions (agegroups)

### ISSUE THREAD

**Issue by inbaz** [inbaz/ers#550]
Please check all texts of the e-tickets and e-ticket e-mail.
There are differences for agegroups for:
- adult
- U18
- U16/U6

The e-ticket e-mail is for all e-tickets the same.

Please check also all links in the e-mail and e-ticket (if there are links).

**Comment by smadamit** [comment]
This sentence in the email have to be fixed: "Please **not** that you cannot register onsite if your name and date of birth don’t match your ID card."

**Comment by smadamit** [comment]
apart from that everything seems to be correct
