### ISSUE TITLE
bug -> upload bank statements on prod -> blank page

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#561]
bug -> upload bank statements on prod -> blank page

-----------------------------------

![screen](https://cloud.githubusercontent.com/assets/1533081/8437046/d31cea18-1f5c-11e5-874a-16624ff0165e.png)

-----------------------------------

**Comment by smadamit** [comment]
0.3.82 -> same error

**Comment by smadamit** [comment]
prerprod 0.3.84 -> it works

I will test one more time on prod 0.3.84.

**Comment by inbaz** [comment]
Deployed 0.3.85 to prod, please retest.

**Comment by smadamit** [comment]
prod 0.3.85 -> OK
