### ISSUE TITLE
auto-matching

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#58]
auto-matching of bank transfers

**Comment by inbaz** [comment]
This needs to be tested in 0.3.40. Do we do a manual start of the auto-matching run by clicking a link no the admin panel or is there a cronjob active which is running every night?

**Comment by smadamit** [comment]
first tests concerning the manual matching:
- #396, #397, #398, #399

**Comment by smadamit** [comment]
I guess we can close this ticket?
