### ISSUE TITLE
implementation of packages

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#59]
We need it for selling a week ticket together with a gala show ticket. Is there a simple work around?

**Comment by inbaz** [comment]
Chaka, hard work this day provided product packages in the admin panel, yeah! Check it out at Product -> Detail of one product (at the bottom). At the product overview you can see if a product has childProducts by a symbol of a box. Do we need a symbol for "this product is a child of another product" aswell?

**Comment by smadamit** [comment]
please fix #104 first

Looking forward to seeing the new feature

**Comment by smadamit** [comment]
first test -> it works

Do we need a symbol for "this product is a child of another product" aswell?
-> no

**Comment by inbaz** [comment]
There needs to be an option to be able to select no gala show ticket. The variants of the subproduct needs to be displayed in the frontend.

**Comment by smadamit** [comment]
don't forget: #216

**Comment by inbaz** [comment]
I've implemented product packages in 0.2.52, please test. #216 is not solved, yet.

**Comment by inbaz** [comment]
Ah, I still need to modify some mails and some overview pages...

**Comment by smadamit** [comment]
@inbaz  OK, I will test it. For clarifications I will comment #216 later. Just to prove that we have the same solution in mind.

**Comment by smadamit** [comment]
tested in 0.2.52 -> OK.
