### ISSUE TITLE
Keep Search and QR Code button next to the search bar

### ISSUE THREAD

**Issue by inbaz** [inbaz/ers#595]
On the onsite reg screens the search and qr code button flips under the search field when the tablet is held upright. I think it's as simply as changing col-md-x to col-sm-x or col-xs-x.

**Comment by Bone008** [comment]
Fixed with 9bedc06c31cfaea2e48f8256de5d1fae632e3657.

Also changed the button texts to icons so they don't take up that much space on the tablet.
