### ISSUE TITLE
My Profile

### ISSUE THREAD

**Issue by jackcaveman** [inbaz/ers#6]
1) The [My profile] button is not the same as the "my profile" page you get directly after logging in.
2) In the "after login" page you can [click view tickets], which currently returns an error.

**Comment by inbaz** [comment]
Correct, this point is wip (work in progress). There are some more profile functions we need than the module I'm using for that supplies. Therefore I exactly need bugreports like this because the logic of the system is broken here and the user does not know why the system is doing this.

**Comment by smadamit** [comment]
duplicate to #57
