### ISSUE TITLE
show gala show agegroups in onsite module

### ISSUE THREAD

**Issue by inbaz** [inbaz/ers#607]
We do have a single gala show ticket. For childs until 6 they don't pay for a gala show ticket, therefore they get two holes in it. For childs until 14 they are cheaper, therefore they get one hole in it. To be able to do that fast we need to add the agegroups
- adult
- U14
- U6
next to the date and time of the gala show. This can be checked against the AgegroupService:price, but I think we need a new field in Agegroup that can be used in this case.

**Comment by Bone008** [comment]
Done in f-onsite.
Note that the agegroups stored for the gala tickets in the database still need to be corrected, as there are some inconsistencies.
