### ISSUE TITLE
order: checkout step by step

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#62]
the steps of the checkout (register, payment, checkout) should be reachable step by step. E.g. it should not be able to click to payment when the step before register is not finished.

**Comment by inbaz** [comment]
Why not? At the last step you get an error message if anything is missing.

**Comment by smadamit** [comment]
It is not a big problem -> prio 3. But I think it is kind of confusing for the purchaser.

**Comment by inbaz** [comment]
Since this is very complicated to solve within this system I'll not fix this problem. There is a workaround with the error messages on the checkout page. Before the requirements are not met the buy now button gets not enabled.
