### ISSUE TITLE
Implement PayPal payments

### ISSUE THREAD

**Issue by inbaz** [inbaz/ers#640]
https://github.com/Payum/PayumModule

**Comment by inbaz** [comment]
@Bone008 Maybe this is interesting when you look into the PayPal stuff.

**Comment by Bone008** [comment]
I decided against using Payum because I already had experience with the official PayPal SDK for the REST API, which is now used.

The payment type is in development on the f-paypal feature branch.

**Comment by inbaz** [comment]
perfect, if it works quite well with the official sdk we'll close this issue.
