### ISSUE TITLE
Age group

### ISSUE THREAD

**Issue by jolieno** [inbaz/ers#647]
We see the age groups at the product page. 
I'd like to not see the agegroups with prices when there's only one price for the product (bus and t-shirts)

Can you creat this at the backend for us?

**Comment by inbaz** [comment]
Maybe this can simply be sorted out in the frontend without any changes in the AdminPanel. I'll check that.

**Comment by inbaz** [comment]
Changed in 0.4.16. Have a look if this is what you expect.

**Comment by davebarnesy** [comment]
What should I be looking for? I still see age groups on T-shirts and bus tickets.

**Comment by inbaz** [comment]
Everytime I fixed an issue I'll write the version in which the issue has been fixed into it. On the plattform you can find the version at the bottom right. For your testing plattform it's still 0.4.14. Hopefully I can find the time tomorrow to setup your testing plattform to the latest version. So simply please be patient.

**Comment by davebarnesy** [comment]
On the admin panel it looks like this might be OK. But in the fronted, it looks like age groups still apply to T-shirts and bus tickets, which should not be the case.

**Comment by inbaz** [comment]
Ah, I just changed it on the product list page. Now the product page itself has only the single price and no message for increasing prices, as well. (0.4.19)

**Comment by inbaz** [comment]
We need to search for an alternative to the participant select box when there is no agegroup needed. At the moment there are the two tabs Agegroup and Person on the product page. I don't think that there will be somebody who orders a t-shirt or bus ticket without connecting the ticket to a person. At least  all unassigned tickets get assigned to the buyer.

**Comment by jolieno** [comment]
Can't we make this without any tabs to choose from? Or if there has to be a tab, than only the person one.

And i also think (at the moment) the system doens't allow you to choose a product without it being connected to a person.

**Comment by inbaz** [comment]
At least the not connected products are connected to the buyer at the checkout process, so yes, it's possible to move this functionality and have only one tab on the product site. Would that be a valuable solution for you?

**Comment by jolieno** [comment]
yes!

**Comment by jolieno** [comment]
can we loose the 'do not assign this product' and always let people assign a product to a person?

**Comment by inbaz** [comment]
If the agegroup tab is completely kicked out, yes we can.

**Comment by jolieno** [comment]
Do you mean kick out the agegroup at all the different products? Or only at bus and t-shirt?

And does the system recognize a persons age after adding in person, so that kids are able to get in cheaper? I want to prevent people getting over charged or under charged.

At the full event one, the agegroup isn't available anymore. The system does seem to charged the correct amount at testing with different ages.

If this is possible, lets then kick out the agegroup tab!

**Comment by inbaz** [comment]
I kicked out the agegroup tab. Please have a try if the system is usable and everything that needs to be done can be done.

**Comment by jolieno** [comment]
I think it gives a problem now with selecting the right price. I just tried to buy a full festival and a dayticket as a 12 year old, the system now charges me the full price.

**Comment by inbaz** [comment]
The price bug was handled in a separate ticket. Is this ticket fixed for now?

**Comment by jolieno** [comment]
Yes!
