### ISSUE TITLE
Text front page

### ISSUE THREAD

**Issue by jolieno** [inbaz/ers#649]
At the moment the text on the front page is the one from last year.

We would like to have it changed or preferably we would like to be able to change this ourselfs.

If you want the lines again, let me know and i'll send theme over.

**Comment by inbaz** [comment]
This is no problem and will be changed in one of the next releases.

**Comment by jolieno** [comment]
:)

**Comment by inbaz** [comment]
fixed in 0.4.16

**Comment by jolieno** [comment]
Hi Andi,

Can you make the following line orange too; Come and make it gezellig with us! 

thanks!

jolien

**Comment by inbaz** [comment]
Check it out in 0.4.19. My opinion is that this is confusing because there is no link to click on like the others. Should we simply link to your EJC homepage with the text "Come and make it gezellig with us!"?

**Comment by jolieno** [comment]
Ah. I see what you mean. Let's link it to the EJC homepage.

**Comment by inbaz** [comment]
done in the next version
