### ISSUE TITLE
product/edit: routing

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#65]
tshirt in shopping card
click edit
in edit form there is the link "back to Overview", which route you to product/index. Should be order/index

**Comment by inbaz** [comment]
I need to do some major changes in my breadcrumb service. This makes many things eaysier but please have a special eye on the routing. Hopefully everything still works like expected including edit of products via the shopping cart.

**Comment by smadamit** [comment]
So please let us know when you finished your changes on the breadcrumb service
