### ISSUE TITLE
order/checkout: bug

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#66]
at the last step of checkout: blank page except of "11"

tested in v0.2.3

**Comment by inbaz** [comment]
I saw a problem with sending the confirmation email, but I don't know why. Could you please check that again? What was in the shopping cart for this checkout?

**Comment by smadamit** [comment]
test v0.2.7:
was logged out. put in a week ticket. checkout. bank transfer. all right, no error. match-code: MP1GR209

But no email!

**Comment by smadamit** [comment]
This issue seems to be solved. 2 times tested.

Andi did you fix something? Or was it just luck (2 times)?

**Comment by inbaz** [comment]
I ran composer update to get the new html2text module in place. That was missed on the testing system. Therefore this bug is fixed.
