### ISSUE TITLE
admin/product/delete bug

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#67]
failed to delete product with several prices

An error occurred
An error occurred during execution; please try again later.
Additional information:
Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException
etc.

**Comment by smadamit** [comment]
same with a product without prices

**Comment by inbaz** [comment]
Aha, products for which already orders have been made cannot be deleted anymore. Should I add a message for that?

**Comment by smadamit** [comment]
Ah good point. Yes a message would be nice. After that we can change to solved...

**Comment by smadamit** [comment]
Sorry for generating work for a low prio isue.

I tested this again 0.2.45:

```
Message:
An exception occurred while executing 'DELETE FROM Product WHERE id = ?' with params [6]:

SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`erspp`.`Item`, CONSTRAINT `FK_BF298A20AD9658A` FOREIGN KEY (`Product_id`) REFERENCES `Product` (`id`))
```

Please let's do the following steps:

## 1. Add error message

Can you please add an error message that products which have already been ordered, can not be deleted.

## 2. retest

After that I can retest.

## 3. delete product/add/6

Please delete product with ID=6 in the database, since is not possible in the admin panel. After taht we can close the issue.

**Comment by smadamit** [comment]
exactly the same issue for: admin/payment-type/delete/3

**Comment by inbaz** [comment]
Tell me if there are these problems somewhere else if you find one. These two should be fixed.

**Comment by smadamit** [comment]
tested in 0.2.48 -> OK
