### ISSUE TITLE
Can we make 4 different desgins to choose from at t-shirts

### ISSUE THREAD

**Issue by jolieno** [inbaz/ers#670]
At the moment there are 2 types of t-shirts products in the system.

Can we make one product T-shirt. And make it so that within this product you can choose:
- men / woman
- size 
- type of design (tulip, windmill, cow or cycling)

I'll have a look at the system see if i can do this myself

**Comment by inbaz** [comment]
Configuring this product will not be a big problem.
Having a picture for each variant of the product which changes is not implemented, yet. And there is no possibility to set a counter for these different products, i.e. to say there are 50 shirts of woman, size s, windmill. I don't know if this function is really needed or if you just order those shirts that are ordered until a specific date.

**Comment by jolieno** [comment]
i've just configured the product. 

Would i be an option to add one picture with all the diferent types on it?

**Comment by jolieno** [comment]
let's close this issue and get the picture in on issue #646
