### ISSUE TITLE
Daytickets, bustickets and t-shirts with agegroup chosen don't show up in overview list

### ISSUE THREAD

**Issue by jolieno** [inbaz/ers#672]
The daytickets, busticket and t-shirt don't show up in the overview list from the shoppingbasked and they don't add up in the pricelist. 

At the moment we can't seem to be buying any other products than the full event one.

Can this be fixed?

thanks!

**Comment by jolieno** [comment]
and after 'buying' this dayticket it shows up as a extra galaticket on order/checkout page. here: https://ejc2016.ers.inbaz.org/order/checkout

So i guess there is something wrong in the setup of the dayticket.

This needed to be solved.

**Comment by inbaz** [comment]
Please check again in 0.4.27 I was able to add a day ticket to the basket and could see it.

**Comment by jolieno** [comment]
i just checked, i still can't see them in 0.4.27. my basket is still empty.

**Comment by inbaz** [comment]
Can you describe the steps you do exactly from the beginning, so I can have a try?

**Comment by jolieno** [comment]
I use the other browers to go to ers system, i do not login, i make a new person and start adding the products which. 

After adding a product, i choose 'add more products' untill i'm done. It doens't seem to matter if I uses a differt size, type or desgin for the t-shirt or if I choose a different bustime.
When i then enter the shoppingcart overview, none of the products apear (except the full ticket one).

i hope this helps.

**Comment by inbaz** [comment]
I bed you're doing much more things in between. Do you choose an agegroup or do you connect the day ticket to the person added as well? Same for the other products.

Can you confirm that you're using the options in the agegroup tab at the product site? That's really not working at the moment, but with Dave I'm in the discussion of kicking this options out at all in #647.

**Comment by jolieno** [comment]
ah! It only works when you assign the product to a person!

**Comment by inbaz** [comment]
This is not fixed until we have a decision if we just skip the agegroup tab or if we really need that tab.

**Comment by jolieno** [comment]
ok, sorry.

**Comment by inbaz** [comment]
So, do we already have a decision on this or is any information missing to make a decision? I kicked out the agegroup tab for the moment. I think that solves this issue. If so, please close it again.
