### ISSUE TITLE
Full event (incl. galaticket) an extra galaticket is added in the end

### ISSUE THREAD

**Issue by jolieno** [inbaz/ers#673]
When buying a full event (including a galashowticket), the system now adds a seperate galaticket and charges for it.

I think it has to do with choosing a time for the galaticket, but i'm not sure.

**Comment by inbaz** [comment]
This is a bug in the system I'm already fixing it. Hopefully it works in the next version.

**Comment by jolieno** [comment]
this one is fixed now :)
