### ISSUE TITLE
the add more product options is not there anymore

### ISSUE THREAD

**Issue by jolieno** [inbaz/ers#680]
What happend to the 'add more products' option, after you added something? 

I really liked this option and it made it clear that you had already added a product, after which you could choose to add more or go to the checkout. 
Now it's not so clear, since the system now gives you a empty productpage. People might get confused and start adding the same product again.

Can the 'add more products' funtion be restored again? Or is there a good reason why it;s not in the system anymore?

**Comment by jolieno** [comment]
Thanks for putting this option back!

**Comment by inbaz** [comment]
I didn't do anything - I think.
