### ISSUE TITLE
The textcolor from 'select a person' has changed

### ISSUE THREAD

**Issue by jolieno** [inbaz/ers#682]
After clicking on the box 'this ticket belongs to' the textcolor from 'select a person' now is unclear.

Can we make this clearer again? Thanxs!

**Comment by inbaz** [comment]
How was the color before? Which color do you want do have in there?

**Comment by jolieno** [comment]
now it's half shaded? and not a color at all, black is fine, that was who it was before.

**Comment by inbaz** [comment]
The item didn't exist before. It's new because there's a ticket that says that participant needs to be selected explicitly if no participant is chosen, yet. #258

**Comment by jolieno** [comment]
If you click on it now a gray field (beam?) comes behind it and the letters turn white. This only happens when the attendee hasn't entered any personal details.

I want the letters to stay black and the field behind it white. (the same 'color' as when you add a t-shirt size, type or design)

**Comment by inbaz** [comment]
This is beacuse the item is disabled, so it cannot be chosen as selection. Can you please make a screenshot of it? This is even a part which looks different in different browsers.

**Comment by jolieno** [comment]
So yes, as discussed in the email we'll leave this one like this.
