### ISSUE TITLE
changing / deleting a product in the shopping cart deletes too much

### ISSUE THREAD

**Issue by jolieno** [inbaz/ers#683]
When deleting a product in the shoppingbasket, now all the products in the shoppingbasket disappear and also the just added attensee. The attendee has to start over again.

**Comment by inbaz** [comment]
I know of that problem but I was not able to find a solution for that. I'm working on this.

**Comment by inbaz** [comment]
This could be part of the cascading configurations in mysql.

**Comment by hattom** [comment]
Example test (currently fails):
* create 2 people
* add one ticket to person A
* shopping cart
* person A's ticket -> edit -> assign person B
Expected result:
Shopping cart: 1 ticket (person B). Persons: 2 persons (A and B)
Result (failure):
Shopping cart empty. Person details empty.

**Comment by inbaz** [comment]
Hopefully all the issues of this ticket are fixed in 0.4.36, have a look.

**Comment by jolieno** [comment]
yes :)
