### ISSUE TITLE
Update order confirmation to 2016

### ISSUE THREAD

**Issue by odegroot** [inbaz/ers#690]
This concerns:

- [x] The *Pay via Bank Transfer*-page: [The Pay via Bank Transfer-page.docx](https://github.com/inbaz/ers/files/102315/The.Pay.via.Bank.Transfer-page.docx) → #694
- [x] The confirmation email: 
[Old and New Text mail pre reg.docx](https://github.com/inbaz/ers/files/102317/Old.and.New.Text.mail.pre.reg.docx) → #702
- [x] The [My Order](https://ejc2016.ers.inbaz.org/order/view/6GP3D5G3286AWCFA458NVP1UR627UK53)-page

**Comment by odegroot** [comment]
This PR was over-the-shoulder reviewed and approved by Jolien.

**Comment by odegroot** [comment]
WIP: https://github.com/odegroot/ers/tree/690-order-confirmation-email

**Comment by jolieno** [comment]
Oscar, you finished all items yesterday right? At the moment the confirmation mail is not the correct one, although al the links are correct. Does Andi know he can release all these items?

**Comment by odegroot** [comment]
@jolieno No, I did not; I only finished the first item, so the email is unchanged and only item 1 can be released ATM.

**Comment by jolieno** [comment]
Ah, ok.

**Comment by inbaz** [comment]
I added a new version at set it online, please check what's already working and what's still missing.

**Comment by jolieno** [comment]
It looks good! I think it is working, at least i've not been able to find bugs in this one. Accept the ones we already know off  ( #683 )

Still missing:
- Change attendees - > personal details #427 
- issue #701 
- correct document send out with the confirmation email (i've just made new issue of that #703 )

**Comment by odegroot** [comment]
Okay, so no further changes are needed for the *My Order*-page? Then we can close this issue, right?

**Comment by jolieno** [comment]
Let's change the following text on the My Order-page -

The buyer will receive all e-Tickets for all registered participants. If you have provided an email address for a participant this participant will be informed once the ticket is paid and will be able to download the e-Ticket on his own as well.

into:

The buyer will receive all e-Tickets for all registered participants. If you have provided an email address per participant, this participant will be informed once the ticket is paid and will be able to download the e-Ticket on his own as well.

So change the word  'for a' into 'per'. Better english i think.

And under the text Payment, i don't know what we mean with the word; Explanation.
Let's delete this word.

Bedankt!

**Comment by jolieno** [comment]
al changes are fixed.
