### ISSUE TITLE
The system now charges youth the full price for full event, daytickets and a seperate galaticket. It doesn't seem to recognize youth persons anymore.

### ISSUE THREAD

**Issue by jolieno** [inbaz/ers#695]
The system now charges youth the full price for full event, daytickets and a seperate galaticket. It doesn't seem to recognize youth persons anymore. 

In version 0.4.33

#647

**Comment by inbaz** [comment]
I found the bug and fixed it for the next version.

**Comment by jolieno** [comment]
jup. fixed :)
