### ISSUE TITLE
Add participants workflow is confusing

### ISSUE THREAD

**Issue by jackcaveman** [inbaz/ers#7]
When you add a participant you "expect" that the ticket has been added to your cart. Some suggestions: 
*) Integrate the webform in the product details page (product/view/2). You have to enter the name and birthdate to select "add to cart". This works better for weektickets than for daytickets.
*) Blank out participants in the list which already have week tickets (or day tickets), maybe set them to disabled. So people see them, but can't select them. 
*) Blank out participants which do not have the correct age range
*) Change the name "add participant" to "add name"

**Comment by inbaz** [comment]
I think I got the problem, but you suggest more than one solution for that problem. To add the form into the product view is making things very complicated, so this won't be a way to go. Would it help to change the button name from product/view to "add name" or "add person" or even "create ..."? On the participant/add we can change the button to i.e. "save & back to product" to make it clear that the product will not be added to the cart at this point.

There is an open point at our side for agegroup integration which is not implemented, yet. This needs to be done first to be able to add the feature to blank out or disable participants by age. This is a seperate issue.

**Comment by smadamit** [comment]
For me it would work if:
- rename button in product view: "create person"
- rename menu: "persons"
- person add: "save & back to product"

I overall think person is better than participant. It is more general. Maybe you want to buy a t-shirt for a person which is not a participant. Or a gala show ticket.

**Comment by inbaz** [comment]
I renamed the buttons. Is this better now?

**Comment by smadamit** [comment]
For me that's working
