### ISSUE TITLE
price change between deadlines

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#70]
I created a product in the admin panel and created 4 different prices for 4 different deadlines (1 minute between each deadline). Than I added the product to the card at 4 different times and got as a result the shopping card as you can see in the screenshot:

![screen2](https://cloud.githubusercontent.com/assets/1533081/6486138/1e67b3b2-c289-11e4-9b1d-ba357cc0dc61.png)

Is this the behavior we want? Can a purchaser save a shopping card?

My proposal: Every shopping card, where the checkout is not competed till one hour after a deadline will be destroyed. That meens, that a juggler who put in a week ticket April 30 at 23:55 for a price of 120 € can checkout this order until May 1 at 0:55. After that his shopping card gets destroyed and he has to order a new week ticket for the price of the next deadline (170 €).

**Comment by inbaz** [comment]
I'm not saving shopping carts in the database. Therefore this is not possible. They're stored only in the session. If the session is destroyed the shopping cart is gone. What you can do if you want to do this a little bit nicer is to set the deadline for a price not to DD.MM.YYYY 00:00 but i.e. to DD.MM.YYYY 05:00.

**Comment by smadamit** [comment]
The session is destroyed after one hour inactive right? Than that's for me no issue anymore. That means a juggler could click a ticket for 120 € in to the card a minute before deadline change. He can order the ticket as long he keeps the session on life.
