### ISSUE TITLE
the second sentence of the first paragraph of text at the home page is to spread out

### ISSUE THREAD

**Issue by jolieno** [inbaz/ers#701]
The second sentence of the first paragraph of text at the home page is to spread out.

Can this layout made the same as the sentences?

thanks!

**Comment by jolieno** [comment]
And I just found out there is a wrong link on this page www.ejc2016.org/registration. it needs to be:
http://www.ejc2016.org/tickets

Oscar can you change these two items? Thanks!

**Comment by odegroot** [comment]
After discussion with Jolien, we've decided to leave this as-is.

**Comment by odegroot** [comment]
@inbaz I just noticed that you had changed the link in commit e57c01f9317fff30bff9f3c7a4832878085bded8, but that you hadn't pushed it to master yet. Jolien and I also changed to the link today, in commit 9a45676aaf16016aeab19f4c2d7e3a957811bf3a.

Our changes should merge without conflicts, but if they don't they now you know what happened.
