### ISSUE TITLE
With the confirmation email the pdf documents which the system sends out are those from 2015

### ISSUE THREAD

**Issue by jolieno** [inbaz/ers#703]
With the confirmation email, the pdf documents that the system sends out are those from 2015. These pdfs need to be changed to the 2016 ones. 

- [x] The order confirmation email
- [x] The *Terms and Conditions*-page https://ejc2016.ers.inbaz.org/info/terms

**Comment by jolieno** [comment]
these documents also need to be changed on the help page and here https://ejc2016.ers.inbaz.org/info/terms

**Comment by odegroot** [comment]
Andi made a start with this in commit 0ce7053b6b6415cf42c22deb9a14b4ba93d1c908.

**Comment by odegroot** [comment]
Technically, had already done all of this before I started, he just hadn't pushed the last bit to master and hadn't closed the issue.
