### ISSUE TITLE
When trying to delete the design option at Hoodie the system gives an error

### ISSUE THREAD

**Issue by jolieno** [inbaz/ers#705]
When trying to delete the desig option at Hoodie the system gives an error:

/home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:64

When putting the designs on disabled - the system no says that they are 'sold out'. I want to delete the design option because there are no different designs to choose from.

**Comment by inbaz** [comment]
Since there already have been made purchases for this option it cannot be deleted. I deleted all purchases so you can manage them again. Have a second try.

**Comment by jolieno** [comment]
yes, i've been able to change it now. Thanks!
