### ISSUE TITLE
testing process

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#71]
should we test fixed bugs before the issue gets closed?

The process would be:
- Andi fix it
- Andi change the label from bug -> Test
- testers test it and if succeeded set the issue to closed

Andi you could also set directly to closed if you are the opinion a retest is not necessary

**Comment by inbaz** [comment]
The only thing I want is to not have the ticket assigned to me, because this is a thing what I'm filtering for. If I should assign it to you instead that's no problem.

**Comment by smadamit** [comment]
Yes assign it to me, but only if you want to have a retest
