### ISSUE TITLE
Error when trying to add and/or edit participants

### ISSUE THREAD

**Issue by jolieno** [inbaz/ers#710]
When trying to add and/or edit participants there seem to be some errors 

- after adding mutiple participants (three or more), when you delete the first participant - the system then changes details of all the participants in the last filled in one. Trying to edit these details and making them to different ones again, doesn't work. The system stays with the last filled in one.
- when trying to add a number 3 participant without an email address, the system duplicates the last filled in participant.

it looks likes these errors are connected to filling in an email address.

**Comment by odegroot** [comment]
At some point, Jolien and I both had the participart with id 50 in our list of attendees. Jolien even had participant 50 three times. When she deleted him, he disappeared from my list too.

**Comment by odegroot** [comment]
Found a cause: when adding a new participant, the ERS checks to see if another participant/user already exists with the entered email address. This check considers all participants/users *without* an email address to be the same person.
