### ISSUE TITLE
the long description and explanation for payment types

### ISSUE THREAD

**Issue by jolieno** [inbaz/ers#719]
- At the payment page under the box SEPA BANK Transfer the words Long Despription are written.

Can we delete the words 'long description' or do we need to replace these with other words?

I would opt for just deleting 'long description' since i think i would be clear without.

- at the checkout page under the box SEPA Bank Transfer the word Explanation is written. 

Lets change the word 'explanation' for 'you've choosen to pay you EJC products through bank transfer.

**Comment by inbaz** [comment]
Have a look at Shop -> Payment Type, choose one and click on the edit link on the right side. There you're able to edit these texts.

**Comment by jolieno** [comment]
A Great! Yes, i'll change it!
