### ISSUE TITLE
Adding a person doens't work 

### ISSUE THREAD

**Issue by jolieno** [inbaz/ers#723]
When trying to register now, the system doens't seem to upload any of the filled in 'personal details' after adding a person. There is no different in trying to do this at the 'personal details tab' or straight away at the 'home' tab.

So people are not able to buy any products at the moment. There seems to be a bug preventing this to happen. 

I hope this can be fixed soon. 

Thanks!

**Comment by inbaz** [comment]
Fixed that small bug in 0.4.44.
