### ISSUE TITLE
Country is not saved when adding a person

### ISSUE THREAD

**Issue by Bone008** [inbaz/ers#725]
Tested on the current live version.

When adding people on the "Personal Details" page, the selected value of Country is ignored.
It will always be "no Country" after adding them.

The edit form saves the country properly, but the dropdown is not populated correctly when the form is loaded (it seems to always contain the value that was last selected).

It would be sad if we lose all the country information from people who regularly add people, so I think this is high priority.

**Comment by inbaz** [comment]
Found this bug and fixed it for the next version.

**Comment by jolieno** [comment]
great :)
