### ISSUE TITLE
when waiting to long before finishing a EJC order the system saves the enterd emailadress

### ISSUE THREAD

**Issue by jolieno** [inbaz/ers#726]
When waiting to long (i don't know how long) before finishing a EJC order, the system saves the enterd emailadress. The system gives out this message:

_A person with this email address already exists. To make changes to your existing order contact prereg@eja.net or chooser another e-mail._

After this people aren't able to finish the order without entering a new email adress.

**Comment by jolieno** [comment]
Can we let the system only save the emailadres after a person has recieved the confirmation email, so after booking al the products?

**Comment by inbaz** [comment]
fixed in 0.4.45

Please test precisely the following steps:
- [ ] add a participant which you know does not exist, yet and make an order (needs to be successful)
- [ ] add a participant start an order and cancel this order by closing the browser windows completely. Add the same participant and finish an order (needs to be successful)
- [ ] try to place an order with a participant which already exists (This needs to give an error message)

Try to find more scenarios which users can make to test them as well.

**Comment by hattom** [comment]
**At 10:06pm:**
Created Testy2206 O'Tester, dob:22.06.1980[1], email myemail+2206@gmail.com
Clicked add ticket, closed browser window + cookies
**At about 10:09pm:**
Created Testy2206 O'Tester, dob22.06.1980, email address myemail+2206@gmail.com
"A person with this email address already exists. To make changes to your existing order contact prereg@eja.net or chooser[2] another e-mail

Is that the correct procedure for test#2 in your comment @inbaz ?

[1] first dob is possibly wrong, I forgot to remember it.
[2] s/chooser/choos

**Comment by inbaz** [comment]
@hattom Sounds correct, but you need to test on our preprod plattform. I don't know if you have the credentials for it. I try to mention the version in which the fix was made. You can find the version at the bottom right.

**Comment by inbaz** [comment]
@hattom the dob is no identification field in the user table. Only the email address is used to identify a person, nothing else. Can you do some more tests on preprod?

**Comment by jolieno** [comment]
i've just fixed text chooser to choose.

**Comment by jolieno** [comment]
**at 16.55:** 
created 'test vijf voor vijf', email: vijfvoorvijf@ejc2016.org
after adding this participant, check it if it was found at 'personal details' and than closed the brower.

**at 17.00:**
created 'test vijf voor vijf', email: vijfvoorvijf@ejc2016.org
A person with this email address already exists. To make changes to your existing order contact prereg@eja.net or chooser another e-mail.

I'll test the next step in 1 1/2 hours :)
