### ISSUE TITLE
cancel an order in the AdminPanel crashes

### ISSUE THREAD

**Issue by davebarnesy** [inbaz/ers#728]
I tried to cancel order 796V6W93 on the live EJC2016 system at 10:13 on 11-02-2016.  
I got some kind of type conversion error.

**Comment by jolieno** [comment]
Andi wrote: I need to fix that. It's only possible to pay with VISA and MasterCard, but at the moment with the actual form there is the problem that every card number can be entered. I need to develop the function that it works like last year. There we were able to change the payment type in the backend and resend the payment information to the participant. I'll add a function to send participants the link to the credit card payment form again. 

So they do not worry about anything and you neither we'll sort out all issues and they'll get the ticket of the first prereg phase.

**Comment by jolieno** [comment]
Would it help if we add a line at creditcard saying 'VISA and Mastercard only' ?

**Comment by inbaz** [comment]
I think there is the possibility to add a select box which only have these two possibilities.

**Comment by inbaz** [comment]
I added the select box for the preprod system, please have a look and check if it works like expected. CreditCard Numbers for testing can be found here: https://hilfe-center.1und1.de/hosting/online-marketing-c10085303/1und1-ipayment-c10082678/bedienung-c10082775/kreditkartennummern-zum-testen-von-ipayment-a10784577.html

All VISA and MasterCard must work and all others may not work.

**Comment by jolieno** [comment]
at the moment the 'wait 5 seconds and you will get redirected' and  the link to the creditcard option doens't work. So i;'ve not been able to test if it works like expected.

**Comment by inbaz** [comment]
In which system? Do you get any error message?

**Comment by jolieno** [comment]
in 0.4.48. I didn't get a error, the page seems to be 'stuck' and keeps at the 'wait for 5 seconds and you will get redirected' page.

My test order does show up in the overviewlist.

**Comment by inbaz** [comment]
Oh, the ipayment configuration was missing in the preprod system. I added the configuration, please try again.

**Comment by jolieno** [comment]
Ok, the link works now. Some of the text on this page is in german;

- zahlung mit kreditkarte (this is writen on the tab)
- the buttons 'zuruck' and  'zahlung durchfuhren'
- Der Zahlungsvorgang kann mehrere Sekunden dauern. Bitte haben Sie einen Moment Geduld und klicken Sie nicht erneut auf die Schaltfläche. 

Can we change this in English?

**Comment by inbaz** [comment]
Hi, I did not reach the 1und1 iPayment support. That hangs at the moment at the missing contract information to get access to the support hotline. @jackcaveman, can you help?

**Comment by inbaz** [comment]
Moved the german parts in iPayment form issue over to #736.

**Comment by jolieno** [comment]
I think we can close this issue, it works and the german text is moved too #736

**Comment by Tobias-Horstmann** [comment]
version 4.5.2:
I tried to cancel the order "HWV3YK60" of participant "Tobias ToCancel" and got the same error message (some type of conversion error):

"
Additional information:
Doctrine\ORM\ORMInvalidArgumentException

File:

    /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php:204

Message:

    Expected value of type "ErsBase\Entity\Status" for association field "ErsBase\Entity\Item#$status", got "string" instead.

Stack trace:

    #0 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(2229): Doctrine\ORM\ORMInvalidArgumentException::invalidAssociation(Object(Doctrine\ORM\Mapping\ClassMetadata), Array, 'cancelled')
    #1 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1693): Doctrine\ORM\UnitOfWork->cascadePersist(Object(DoctrineORMModule\Proxy\__CG__\ErsBase\Entity\Item), Array)
    #2 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1630): Doctrine\ORM\UnitOfWork->doPersist(Object(DoctrineORMModule\Proxy\__CG__\ErsBase\Entity\Item), Array)
    #3 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(579): Doctrine\ORM\UnitOfWork->persist(Object(DoctrineORMModule\Proxy\__CG__\ErsBase\Entity\Item))
    #4 /home/ejc2016/www/ejc2016.ers.inbaz.org/module/Admin/src/Admin/Controller/ItemController.php(123): Doctrine\ORM\EntityManager->persist(Object(DoctrineORMModule\Proxy\__CG__\ErsBase\Entity\Item))
    #5 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Admin\Controller\ItemController->cancelAction()
    #6 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
    #7 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
    #8 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
    #9 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
    #10 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
    #11 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
    #12 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
    #13 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
    #14 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
    #15 /home/ejc2016/www/ejc2016.ers.inbaz.org/public/index.php(18): Zend\Mvc\Application->run()
    #16 {main}
"
