### ISSUE TITLE
not all the booked tickets show up with names in the overview list

### ISSUE THREAD

**Issue by jolieno** [inbaz/ers#729]
There are booked orders in the live overview list, where the overview list says:

_no buyer could be found - no payment type could be found - 127,50 €_

If you than click on the detail button, there is information about the booker. So a person did buy product for EJC?

- does this person recieve an order confirmation mail now?
- Can we make all the booked tickets show up in the overview list with name and payment type.

**Comment by inbaz** [comment]
Nope, this is new this year, orders are saved in the database even if they're not bought, yet. So these are orders which are not bought. What do you need the list of booked tickets for? So which feature do you exactly missing and which information do you want to get. Maybe the order overview is not the correct place for exactly this information.

**Comment by jolieno** [comment]
Ok, i need to be clearer. There are also orders in the system which so no information at all, I thought those are the ones people just looked at a didn't book anything at all. With those there isn't any detail information.

These ones made me wonder if people did buy a product and if it might be a new bug and/or if those people thought they had bought a ticket, but didn't.

**Comment by inbaz** [comment]
So the order overview page will not be able to load at the time where there are much more orders in there. After that the search orders page needs to be used. Maybe that's a good info for @davebarnesy and Andrea as well.

With the search you will be able to get every tickets even the ones which do not show up in this list.

So is the title of this ticket: "create a overview page over all participants with their tickets"? If so, I need an explanation what this site is for and which need is solved with that page. I don't see the reason for this page, yet.

**Comment by jolieno** [comment]
If we are sure that the people who where in the system at the 0.4.44 release 

like order number - 64R8RC93 _no buyer could be found - no payment type could be found - 127,50 €_

know that they haven't bought any EJC products, i'm fine and than we can close this issue.

**Comment by inbaz** [comment]
Yes, we are sure.
