### ISSUE TITLE
The statistics: orders don't give the correct information

### ISSUE THREAD

**Issue by jolieno** [inbaz/ers#730]
The **Statistics: Orders** don't give the correct information.

We need the information from these statistics to plan our FacebookPromotions about EJC, therefor it's very important if we have the correct information.

Let's make the statistics had out the correct information.

Thanks!

**Comment by inbaz** [comment]
Can you be clearer in answering the questions: What is shown at the moment? What do you expect to see? Do you miss the correct amount of participants or the amount of money that has already been ordered? Why is this important for the facebook promotion? Last year the statistics module was developed in May or June. Everything went quite fine without statistics until then.

**Comment by jolieno** [comment]
In the **Statistic; Order now ** all the orders show up, also the ones without a bought product behind it. 

To get a 'beter' number how many people registerd i now count the emails manualy in the overview order list. I like to just have to look at this statistic order, to get the correct number at onces.

We want to know if this number (of pre registration) stays 'behind', we can than use FB to focus more on the pre reg and get people to register. To use it as a message something like 'do you want to be part of the first 500 people to register? do it now! at ... '

Or is there an other function in the system I can use to get this information, without counting manualy?

**Comment by inbaz** [comment]
What exactly is on 18.2. that you created a milestone for that date? It would be really great if I could keep the creation of milestones. If you have suggestions I'm open for any ideas.

**Comment by jolieno** [comment]
There is nothing exatctly on 18-2. I just wanted to have another milestone because the other milestones didnt fit with this issue. 
It would be nice to have a milestone to choose from when there is an function/issue which we want to have working as soon as possible.

**Comment by inbaz** [comment]
This is not what milestones are intended for. This is what prio1 is intended for. If there's a real big problem on the platform there is the Hotfix Milestone but this is only for really really urgent issues. That the Milestone Matching & E-Ticket ends at 1. April does not mean that all issues are fixed on 31. March and will go live on the next day.

I'm working with the green milestone bar that shows how far we are with the currect milestone. Therefore it's not more productive to add milestones for every week. I'll try to fix upcoming issues within 1-2 weeks as long as they are not really urgent. Tomorrow we're online for just one week. With that fact in mind last week happend pretty much when you look at the preprod system, or not?

**Comment by jolieno** [comment]
Participants by product variant:

- [ ] please add the bus which goes on saturday 30 july in the list

- [ ] About the t-shirts, can we get the system to combine information about the t-shirts? So that for each desgin the system gives out information how many we need to order, in which size and in which type.

**Comment by jolieno** [comment]
I've split these issues in seperate ones and will close this issue.
