### ISSUE TITLE
Email already registered, can't pay for ticket, cant reset password

### ISSUE THREAD

**Issue by kskwared** [inbaz/ers#734]
there are a couple of issues

1. I preregistered with my email katharine.kirkbride@gmail.com
2. I didn't buy a ticket
3. I tried to buy a ticket a few days later
4. I was not able to progress from the page https://prereg.eja.net/order/buyer The reason is that when I  try to save my email address as the buyer, then I get a message "A person with this email address already exists. To make changes to your existing order contact prereg@eja.net or chooser another e-mail"
5. I tried to log in to get around the problem - I don't know what my password is
6. There is no link to reset the password
7. I still don't have tickets!
8. You now have a ticket!

**Comment by inbaz** [comment]
:) Thanks for your report. We're alreay on the e-mail address already exists bug. With one of the next versions this will be fixed and you will be able to order your tickets. So please be patient for about a week or two, then we'll release the new version. If it helps: you're not alone. :)

Cheers
Andi

**Comment by kskwared** [comment]
Thank you Andi, now I will go back to my own tickets and bugs


KK


________________________________

**Comment by inbaz** [comment]
Sounds interesting, what tickets and bugs are you working on? If you want to write me a mail to andi@inbaz.org.

**Comment by kskwared** [comment]
I'm a project manager on a platform and tool for a small Chinese investment bank. Not as exciting as the EJC. http://en.dealglobe.com/ Our main product is just for our internal users really.

KK
[http://en.dealglobe.com/wp-content/uploads/2016/01/dealgloe_logo_en_2016.png]<http://en.dealglobe.com/>

DealGlobe | The M&A platform connecting capital across ...<http://en.dealglobe.com/>
en.dealglobe.com
DealGlobe is a China-Europe M&A development specialist, delivering unique efficiency to our clients through our combination of technology and investment banking skills.




________________________________

**Comment by inbaz** [comment]
That sounds really great. If would like to support the EJC we're always searching for a helping hand, especially one with software development background. :) At the moment it would be great to have a helping hand in prioritizing issues and structuring the upcoming test environment scenarios. Do you feel like doing some stuff for the ERS?

**Comment by kskwared** [comment]
Roughly how many hours a week would it be?


________________________________

**Comment by inbaz** [comment]
As much as you like. I would be happy about 1h a week. Every other pair of eyes that has a look at what needs to be done is perfect. If you like to project more and more while you're helping you're welcome to do more if not you're free to decide if you want to stop your support. It's a project on a voluntarily basis.

**Comment by kskwared** [comment]
OK Andi - It will be a good opportunity to get to know some other jugglers before the event as well.


I will probably be happy to help with the projecty things, priroitising, writing bugs, testing. Should we have a Skype call some time to see how it would work practically. (skype = kk3.1415)


KK




________________________________

**Comment by inbaz** [comment]
duplicate #726
