### ISSUE TITLE
Upload csv file

### ISSUE THREAD

**Issue by kskwared** [inbaz/ers#737]
The steps to produce the bug were

log into the admin panel
visit upload csv https://ejc2016.ers.inbaz.org/admin/bankaccount/upload-csv 
download a csv from https://seafile.sixhop.net/d/95950e3f7b/ I took Bank_Transfer_2016-02-11.csv
I went back to upload csv and selected the csv from my local computer and pressed upload

The result was that I got a warning message "The form submitted did not originate from the expected site." - which is apparently an expected result because the csrf security key is to old. Then you need to simply try it again. 

I tried again with the same result

The third time, I got a different result instead. The following error was reported. Instead, I would expect to either get the same warning message, or for the upload to be successful
______________________________________________________________
An error occurred
Sorry!
The page you are looking for doesn't exist. If you think this is an error, please let us know at info@ejc2016.org.

If you encounter any error with this system, please send us a full copy of this page.

You might be looking for:
the products page
your current shopping cart
the login to access your previous purchases
An error occurred during execution; please try again later.
Additional information:
Doctrine\ORM\ORMInvalidArgumentException
File:
/home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php:92
Message:
A new entity was found through the relationship 'ErsBase\Entity\BankStatement#bankStatementCols' that was not configured to cascade persist operations for entity: ErsBase\Entity\BankStatementCol@000000004718e4420000000071a3e6c8. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"}). If you cannot find out which entity causes the problem implement 'ErsBase\Entity\BankStatementCol#__toString()' to get a clue.
Stack trace:
#0 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(844): Doctrine\ORM\ORMInvalidArgumentException::newEntityFoundThroughRelationship(Array, Object(ErsBase\Entity\BankStatementCol))
#1 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(732): Doctrine\ORM\UnitOfWork->computeAssociationChanges(Array, Object(Doctrine\ORM\PersistentCollection))
#2 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(444): Doctrine\ORM\UnitOfWork->computeChangeSet(Object(Doctrine\ORM\Mapping\ClassMetadata), Object(ErsBase\Entity\BankStatement))
#3 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(757): Doctrine\ORM\UnitOfWork->computeScheduleInsertsChangeSets()
#4 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(332): Doctrine\ORM\UnitOfWork->computeChangeSets()
#5 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(356): Doctrine\ORM\UnitOfWork->commit(NULL)
#6 /home/ejc2016/www/ejc2016.ers.inbaz.org/module/Admin/src/Admin/Controller/BankaccountController.php(399): Doctrine\ORM\EntityManager->flush()
#7 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Admin\Controller\BankaccountController->uploadCsvAction()
#8 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#9 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#10 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#11 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#12 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#13 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#14 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#15 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#16 /home/ejc2016/www/ejc2016.ers.inbaz.org/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#17 /home/ejc2016/www/ejc2016.ers.inbaz.org/public/index.php(18): Zend\Mvc\Application->run()
#18 {main}

**Comment by inbaz** [comment]
Should be fixed in 0.4.51

**Comment by inbaz** [comment]
Sorry to be strict: We're handling personal data, so could you please not paste internal links or data that contain information that should be held secure? That would be really great.

**Comment by inbaz** [comment]
I corrected the upload of csv files.
