### ISSUE TITLE
new paymenttype: PayPal

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#74]
- sepa direct debit
- PayPal

**Comment by smadamit** [comment]
PaymentType: PayPal

​http://devzone.zend.com/370/choosing-the-right-paypal-solution/
​https://github.com/speckcommerce/SpeckPaypal
php composer.phar require speckcommerce/speck-paypal:dev-master
​https://developer.paypal.com/webapps/developer/docs/api/

**Comment by smadamit** [comment]
@inbaz So it would be really nice to have PayPal this year :-)

**Comment by inbaz** [comment]
I don't think sepa direct debit is really needed in this case but PayPal would be really nice -> changing title.

**Comment by inbaz** [comment]
This will be solved in another ticket. #640
