### ISSUE TITLE
ERS for non-EJC-Convention

### ISSUE THREAD

**Issue by PiQuer** [inbaz/ers#744]
Hi Andi, hi ERS team,

I'm involved with the organization of this year's Freiburg Convention, and we are currently evaluating the possibility to use ERS for the regestration. I already installed it on my own server (not publicly accessible), and I have some questions:

- First of all, do you approve such a use case, and can it be done without disrupting the regular EJC preregistration? I noticed several hard-coded websites and email adresses pointing to the EJA and just want to make sure not to get in the way...
- During the installation I had to work around some exceptions by commenting out function calls until products were added, otherwise I wouldn't be able to log in for the first time. At a few other places I now still see exceptions. Are you interested in bug reports for an installation from scratch?
- I have some difficulties getting the product prices and deadlines right, and I cannot add products to the cart ("Please complete the whole form to put this product into the cart." although everything seems to be fine), if you say yes to the first question I will open individual issues to call for help ;)

Thanks, and keep up the excellent work!
Cheers
Raimar

**Comment by inbaz** [comment]
Yes of course! ERS should become an easily installable registration system for event, therefore the name: Event Registration System. Yes, please use the system for the Freiburg Convention. To not get into the way of EJC prereg I suggest to add a branch freiburg-live which will be the one versioned for the Freiburg Convention. For Changes we'll make branches from this one and merge to this one to not brake other live systems. After the several convention these different live branches should be merged together again.

There is already an issue #637 to create an installer workflow. I thought the readme of the project explains it quite well what needs to be done to get the system initially running.

**Comment by PiQuer** [comment]
Thanks Andi. The readme is mostly fine, although a few things needed to be adjusted during the installation. I will create issues accordingly.

I have created two branches in a fork on my account, PiQuer/ers. The freiburg-live branch is intended for changes and bugfixes needed to get the system running for the Freiburg convention, the branch freiburg-branding is inteded for changes to the website text, logos etc. I would then regularly merge freiburg-live into freiburg-branding to get a version for the server. This way commits to freiburg-live are commits touching only the system, not the texts, and might be merged back to master more easily. What do you think?

**Comment by inbaz** [comment]
It figured out that text changes are best made in a two column word file and have the old text on the left and the new one on the right side. Therefore it's not needed to have a separate branch for text changes.

Do you want to host the system yourself or do you want to have the system hosted at my side?

I don't know how the merges back to the official ERS is possible from an external branch as yours, therefore I rather thought of creating a freiburg branch on the inbaz/ers project, but I think that doesn't really matter. It should be possibel either way round.

**Comment by PiQuer** [comment]
I have it installed on my webserver because I figured it would be easier for me to test stuff this way. This is a very light-weight virtual server, probably not suited for the final production system. For testing porpuses now, if it turns out to be easier to have it on your server, that's totally fine with me.

Where to host the final product I would have to discuss with the others (that is, after discussing if we can use it at all, once I have a presentable test system to show them).

Having the freiburg branch on inbaz/ers is also fine, if you maybe could give me permissions for this branch.

**Comment by inbaz** [comment]
You're a collaborator, so you have access to all branches of the inbaz/ers project. For live systems it would be nice to have a 128 MB memory_limit Webspace and a ssl certificate to encrypt user details on the transfer to the webserver. That's it. A lightweight virtual host would do the job. If you want support by me during the prereg phase it's much more easier when I have directly access to the system and I think I will not support external webspace anymore, because I don't want to end up in discussions on how to setup webservers anymore.

**Comment by PiQuer** [comment]
I wasn't aware that I already had write permissions. I will push a freiburg-live branch to inbaz/ers then.

If you could give us support during prereg that would be great, in case something goes wrong. And of course  then it is better to have it hosted on your webspace. The only thing I would need is enough permission to deploy the live system from the freiburg-live branch, so that I can make the necessary changes to the site without bothering you every time, would that be ok?

**Comment by inbaz** [comment]
Are all your questions answered in this issue? If so, could you please close it?
