### ISSUE TITLE
Suggested readme changes

### ISSUE THREAD

**Issue by PiQuer** [inbaz/ers#745]
Related to #637. I would suggest the following changes:

- [x] Add the php modules `iconv` and `intl` to the needed modules. Missing these modules leads to subtle errors when trying to send an email or when adding prices.
- [x] Remove the `vendor/` part from the commands in section 6, the `bin` directory now seems to be in the top-level installation directory
- [x] Maybe add a section about permissions: the `data` directory should be writable by the http process, and the doctrine-module script from section 6 should be executed as http user. Something along the lines `sudo -u http php bin/doctrine-module ...`. Alternatively, if the doctrine-module is executed as a regular user, the logfiles created under data during the doctrine-module run have do be adjusted to be writable by http afterwards. Otherwise, if the http user cannot write to the log files for whatever reason, we get an Exception from the logger when trying to access the site.
- [x] Maybe add a section about copying `ers.global.php` to `ers.local.php` and adjusting this file accordingly. I needed to add a line `'registration_info' => "http://some.site.com",` which was not present in the `ers.global.php` file.

**Comment by inbaz** [comment]
I changed the README.md in the develop branch. You have have a look if all the above points are corrected.

**Comment by PiQuer** [comment]
Looks good to me.
