### ISSUE TITLE
Missing dependency in composer.json?

### ISSUE THREAD

**Issue by PiQuer** [inbaz/ers#746]
Related to #637. Directly after installation of ERS, I get an exception when trying to access the site:
```
Error: Call to undefined method Zend\Mvc\View\Http\ViewManager::getResolver() in /usr/share/webapps/freiburg_prereg/vendor/dino/dompdf-module/src/DOMPDFModule/Mvc/Service/ViewPdfRendererFactory.php on line 39
```

I can work around this by adding the following line to `composer.json` in the "require" section:
```
"zendframework/zend-mvc": "dev-master",
```
and call `php composer.phar update` afterwards, but I have no idea if this is the correct solution.

```
$ php --version
PHP 7.0.3 (cli) (built: Feb  2 2016 18:23:27) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.4.0RC4, Copyright (c) 2002-2016, by Derick Rethans
```
See also commit c319e53383a8bcc5fcc3a874a59df40bfb7e2732.

**Comment by inbaz** [comment]
Interesting. I'll have a try on this when setting up the testing system for Freiburg. I see some modules that require zend-mvc. If you delete the requirement of composer.json and run php composer.phar update again does composer delete zend-mvc again? If not there was an error while installing the dependencies. Could you please have a try?

**Comment by PiQuer** [comment]
zend-mvc does not get removed, even after removing the line from composer.json again and running php compser.phar update.

**Comment by inbaz** [comment]
I changed zf2 version to 2.4.x in composer.json. Looks like there are some changes to the mvc in 2.5.x which breaks the dompdf module that's used in this project for generating the e-ticket pdfs. I thin even if this issue is not fixed at the moment we can close it.
