### ISSUE TITLE
Question about a simple product and deadlines

### ISSUE THREAD

**Issue by PiQuer** [inbaz/ers#748]
I need some help adding a simple test product to a fresh install. Please let me know if this is not the right place to ask for support.

Just adding a product with a price but without deadline gives me `PreReg is closed` on the product page. I get the same result if I add some deadline which cannot change the price, the deadline being in the future or in the past.

The only way to get the product to actually be displayed at all on the product page is to add a deadline in the future which can change the price, and then to add **two** prices to the product, one with and one without the deadline. But then it sais "The prices will increase after <deadline>" which is not what I want at the moment. If I add only one price to the deadline, the product is missing from the product page.

Probably I am just very confused how this is supposed to work, could you maybe explain a very basic example?

**Comment by inbaz** [comment]
PreReg is closed when there are no valid payment types available at the moment. Do you have payment types configured?

**Comment by PiQuer** [comment]
Solved in private communication, minimum one "can change price" deadline is needed.
