### ISSUE TITLE
a bug which prevents all bustickets to be shown in Statistics: Participants / Participants by product Variant

### ISSUE THREAD

**Issue by jolieno** [inbaz/ers#754]
It seems there is a bug which prevents all bustickets to be shown in **Statistics: Participants / Participants by product Variant**

At the moment the list under 'variant value' only shows the bustickets for the sunday 7th of august, the bus back to schiphol.

Can we fix this bug so that all the different bustickets (saturday 30 july - 12pm, saturday 30 july - 14pm, saturday 30 july- 16pm, saturday 30 july - 18pm and saturday 30 july - 20 pm) people are able to buy are shown in this list? 

thanks!

**Comment by Bone008** [comment]
Done.
