### ISSUE TITLE
Bug in 'item count' for t-shirts

### ISSUE THREAD

**Issue by jolieno** [inbaz/ers#755]
The 'item count' for the t-shirts in **Statistics; Participants / Participants by Product Variant** doesn't seem to be correct. 

At the moment when you add up the 'item count' for ' variant - design' tulip 44 + cow 52 + windmill 52 + clycling 33, the amount of bought t-shirts is **181**. 

When you add up the 'item count' behind 'variant - type' Men (57) + Woman (23) it is a lower amount **80**. This number should also be 181, since with each t-shirt people need to chose Men or Woman to finish.

Also the 'item count' for sizes (80 at the moment), doesn't match with the amount for designs.

Can this bug be fixed, so that the 'item count - variant/design' stays the same with the 'item count - type' and 'item count - sizes'?

**Comment by kskwared** [comment]
I had a look and it is not possible at this time to add a tshirt to the cart without choosing male or female

**Comment by jolieno** [comment]
That's correct, that shouldn't be possible. For ordering the t-shirts we need to know if people want male or female fit.

**Comment by Bone008** [comment]
Fixed with the new handling of variants.
