### ISSUE TITLE
the Hoodies are not shown in the Statisic; Participants / participants by product variant list

### ISSUE THREAD

**Issue by jolieno** [inbaz/ers#757]
The Hoodies are not shown in the **Statisic; Participants / participants by product variant ** list.

People are able to buy Hoodies for this EJC, at the moment this item is not shown in the participants by product variant list. 

Can we add this item (or fix the bug which might be preventing this) in this list? There is no design to choose from, the information it needs to give is size, type and amount.

This might be a similar bug with not all the bustikets showing #754  in the list.

**Comment by inbaz** [comment]
In general on all statistics pages the filter for ordered items is missing. Once the filter is implemented to only count ordered and paid items the numbers should look much more correct.

**Comment by jolieno** [comment]
this is fixed in 0.4.53.
