### ISSUE TITLE
The text of the E-tickets needs to be adjusted

### ISSUE THREAD

**Issue by jolieno** [inbaz/ers#758]
The text of the E-tickets needs to be adjusted.

At the moment the text in the E-tickets haven't been adjusted to 2016 jet, it's the text from team 2015.

To change these text, jolien needs to be send a 'test E-ticket', after which she can make a word document and uploaded that in the githubb.

Can we send out a 'test E-ticket' to me? 

Thanks.

**Comment by inbaz** [comment]
I send the e-tickets as they are to you @jolieno. The changes to the product list are managed in #761.

**Comment by kskwared** [comment]
Suggest priority 2 because e-tickets will not be sent til nearer the event

**Comment by jolieno** [comment]
Here by the new text for the E-tickets;

[7.4.10 old an new text E-tickets.docx](https://github.com/inbaz/ers/files/169471/7.4.10.old.an.new.text.E-tickets.docx)
