### ISSUE TITLE
Error after clicking on the link in the payment reminder email

### ISSUE THREAD

**Issue by jolieno** [inbaz/ers#760]
I'm testing if all the steps in de 'send payment reminder' are working. The steps for the pre-reg coordinator seem to work; they can send out a 'payment reminder email' without any problems. 

But as the reciever i encounter the folowing error: 

After clicking on the 'please pay your order at http://prereg.eja.net/order/view/VDGDMNCWDX7P15A8DKRN1R9A7WK8H570 ' the following error occurred:

_A 404 error occurred
Sorry!

The page you are looking for doesn't exist. If you think this is an error, please let us know at info@ejc2016.org.

If you encounter any error with this system, please send us a full copy of this page.
You might be looking for:

    the products page
    your current shopping cart
    the login to access your previous purchases

Page not found.

The requested controller was unable to dispatch the request.

Controller:
    PreReg\Controller\Order

No Exception available
_

Can this error get fixed?

**Comment by inbaz** [comment]
Testing should only happen on the preprod plattform. For functions that have not been used before by the EJC 2016 team, do not use these functions in the live system. They could break the live system because the admin panel is not fully tested, yet.

**Comment by inbaz** [comment]
I looked into it. The payment reminder e-mail has never been prepared for EJC 2016. Please do only use the function to "resend confimation". That's all you need at the moment, because in this e-mail all information to pay the order is prepared and documented. The payment reminder e-mail is only in case there are missing payments for orders, which is at the moment not the case.

**Comment by inbaz** [comment]
Aha, maybe I see where this error comes from. prereg.eja.net was hard coded for the links in this e-mail. Therefore if you place an order on preprod you will still get links to prereg.eja.net and of course in the live system they do not exist. I corrected the links to be generated according the system you're on. in 0.4.51

**Comment by jolieno** [comment]
ok, clear. i'll test this in 0.4.51.

thanks.

**Comment by jolieno** [comment]
@kskwared can you assgine this to one of the new testers too? I'm currently busy with other EJC stuff.

**Comment by kskwared** [comment]
@jolieno Who are the new testers? Can you send me a bit more info on who they are and what their involvement is? katharine.kirkbride@dealglobe.com

**Comment by jolieno** [comment]
hi katharine, i've send you an email from jolien@ejc2016.org.

thanks!

**Comment by Tobias-Horstmann** [comment]
it is also fine with version 0.4.52
