### ISSUE TITLE
Question; How does a person gets the link to complete his payment, after changing the paymenttype from banktransfer to creditcard

### ISSUE THREAD

**Issue by jolieno** [inbaz/ers#768]
I've done some testing with changing payment types at preprod and resending confirmation mails. These functions seems to be working well, no errors occured. 

The only question i have is; how does the person gets the creditcard link to do the payment?

In the confirmation mail (see below) you can send out after this change, there is no link included.

> Dear jolien preregtest,
> 
> This is the confirmation for your order from 15.03.2016 with the order ID 8D5FW486. 
> 
> To receive this email in another language you can visit the resend email link. 
> 
> Thank you for registering for the 39th European Juggling Convention! Your registration makes it easier for us to organize a gezellig EJC for you and all fellow jugglers. 
> 
> You've chosen Credit Card as payment method.
> 
> Please consider our general terms and conditions, which are attached to this email. To be able to read the document, you need to install Adobe Acrobat Reader, which you can download here: http://get.adobe.com/reader 
> 
> Your eTickets and further information concerning the 39th European Juggling Convention will be delivered in another email as soon as we start distributing the eTickets and your payment has been confirmed. 
> 
> See you in Almere, the Netherlands between the 30th of July and the 7th of August 2016 for EJC 2016! 
> 
> Regards,
> 
> Your European Juggling Association and the local 39th European Juggling Convention organizers.

Can we add the link in this mail? Or is there another way of sending out the creditcard link i'm missing?

**Comment by inbaz** [comment]
To start over the payment again the buyer needs to visit the order link. It's in the text "This is the confirmation for --> your order <-- with the order ID ...". After klicking on this link on the right side there will be a button for start credit card payment again.

Since the e-mail is the same for sepa and credit card I would like to keep it the same for those two. Maybe the text of the e-mail can be enhanced to tell the buyer that he can find more information about the payment on the order page. I'm open for any suggestions.

**Comment by jolieno** [comment]
maybe add the following text;

"You've chosen Credit Card as payment method. Click on here to pay for your order."

and make the here the same link as the 'your order' one?

**Comment by inbaz** [comment]
As I already said the emails are the same for creditcard and sepa bank transfer. Therefore it needs to be a text that matches for both.

**Comment by jolieno** [comment]
hi,

In the testing I just did, i started booked my order with creditcard. The payment for this order i  changed, through the adminpanel, to bank transfer. After which I had the system send out a new confirmation email:

>

>  You've chosen SEPA Bank Transfer as payment method.
> 
> To complete your order, we need to receive your bank transfer within 14 days.
> 
> 
> Please transfer the amount by SEPA bank transfer to the following account:
> 
> Owner STICHTING EUROPEAN JUGGLING ASSOCIATION 
> IBAN NL84 INGB 0007 8721 92 
> BIC INGBNL2A 
> Bank ING BANK N.V. 
> Country Netherlands 
> Amount 127,50 € 
> Reason for payment 8D5FW486 
> 
> Make sure to fill in this reason for payment 8D5FW486 as the reference for the transfer. Otherwise we won't be able to match your payment and your order can't be processed.
> 
> 

So to me this is a different email, that the creditcard email. And since this email is more detailed how to do the payment, it made me question how the creditcard person knows what to do.
