### ISSUE TITLE
Test Barcode and QR-Code

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#77]
Test printed Barcodes and QR-Codes. Especially with different printers and also bad printers. If there are problems we have to print them larger.

**Comment by smadamit** [comment]
see #332

**Comment by inbaz** [comment]
It's possible to generate eTickets in AdminPanel Order Detail for single packages. These tests can start in 0.3.43

**Comment by smadamit** [comment]
tested in 0.3.43 -> work's very smoothly. reliable even with a bad printer and after crumple the printed eTicket.

I tested QR-Code and Barcode...
