### ISSUE TITLE
Testing new release - status of payment creditcard says ordered instead of paid

### ISSUE THREAD

**Issue by jolieno** [inbaz/ers#774]
Testing new release - status of payment creditcard says ordered instead of paid

One thing is not working as expected after ordering and paying with the creditcard:
- the status of payment say 'ordered' instead of 'paid'. 

With the testing I just did, I got to this page all the times;

![credicard betaald ding](https://cloud.githubusercontent.com/assets/16348281/13903677/15a979f2-ee86-11e5-9077-28243d584fdf.PNG)

The rest of the statistics seem to work as wanted, also for the orders I did with banktransfer.

**Comment by Tobias-Horstmann** [comment]
Is fixed with version  0.4.53 (see #777)
