### ISSUE TITLE
Order not marked as "paid" when paid with credit card

### ISSUE THREAD

**Issue by Tobias-Horstmann** [inbaz/ers#777]
v.4.52
When paying with credit card, the participant status is not set to "paid".

I have ordered full week + galashow as participant "Tobias Testing4CreditCard", Order "WMU4KU61" and chose credit card payment. I paid with visa test credit card number "4111111111111111" and a message appeared stating payment sucessful.

problem:
However when clicking on "order" in the admin panel and search for the participant and look at the details the status is set to "ordered" and not marked as "paid".

expectation:
When paying by credit card the status should be immediately set to paid.

It was also possible to pay by credit card twice, see #743 
(https://github.com/inbaz/ers/issues/743)

**Comment by jolieno** [comment]
also see #774

**Comment by Tobias-Horstmann** [comment]
tested with version 0.4.53 and works fine.
Multiple paiment with creditcard is also not possible (#743)
