### ISSUE TITLE
"Reset My Shopping Cart and My Persons" does not work

### ISSUE THREAD

**Issue by PiQuer** [inbaz/ers#782]
Version: 0.4.53
To reproduce:

- Products -> Full event + Gala show ticket -> add a new person
- fill in personal details
- select show and add to cart
- Go to "My shopping cart"
- click on "Reset My Shopping Cart and My Persons"

I would expect that the list of persons and the shopping cart is reset. Instead, an empty page is displayed. After returning to the shopping cart, the added product is still there, same for the added person.

**Comment by inbaz** [comment]
You should get the CartController out of the develop branch. We already made a fix to really delete this started order even from the database.

**Comment by PiQuer** [comment]
The described bug was found on the EJC test server. In the freiburg branch, develop is already integrated (and CartController is present), still clearing the shopping cart does not work. Do I need to do something else to activate the CartController? The symptoms on the freiburg branch are a little bit different: instead of an empty page, the confirmation page just reloads, still the product remains in the cart.
In the log files I could not spot anything suspicious.

**Comment by PiQuer** [comment]
Works in develop.
