### ISSUE TITLE
No confirmation page after completing an order (freiburg branch)

### ISSUE THREAD

**Issue by PiQuer** [inbaz/ers#783]
Version: freiburg-live (https://anmeldung.jonglieren-in-freiburg.de)
This bug does not occur at the EJC prereg testing server.

To reproduce:

- Add a product to the shopping cart
- go to the shopping cart and select buyer and payment method, save and continue
- at the checkout, accept the terms and conditions and click "Jetzt kaufen"

I would expect a page confirming the order and displaying the payment details and order number. Instead a completely blank page is shown.

In the AdminPanel, the order can be seen at Order->Overview nevertheless.

**Comment by inbaz** [comment]
A completely empty page is a failure in the php code. Maybe the logfile which you can find in the SSH account can help with this error. Maybe we should proof a special variable to get an error message instead of a white page. But that's just a guess.

**Comment by inbaz** [comment]
Yes the role "buyer" was missed in the database. I added a exception to my development branch. I added the buyer role in the freiburg setup, therefore you'll see this page now.

**Comment by PiQuer** [comment]
Thanks, it works now.
