### ISSUE TITLE
The friday show says sold out but the counter limit hasn't been reached

### ISSUE THREAD

**Issue by jolieno** [inbaz/ers#784]
The friday show says sold out but the counter limit hasn't been reached.

I wanted to book a fridayshowticket for a friend and now the system say's its sold out. But looking at the statistics this number is on 1329 and not jet on the counter limit 1500.

I think this is a bug.

**Comment by inbaz** [comment]
That's correct, this is a bug. At the moment the system counts even the order pending gala show tickets. I corrected this in the develop branch. The fix will go live with the next version. As a workaround please set the counter limit to 1600 then there can be 100 more tickets put in the shopping basket. Hopefully this will be enough until the next version will go live.

**Comment by inbaz** [comment]
@Bone008: can you check the PreReg/ProductController? I added the TicketCounterService checkLimits method to addAction and editAction as well. It was only in the indexAction. Why did we do that this way?

Inside of the TicketCounterService I added the join to the status table and added order pending to exclude them from the counter. Maybe a nicer way is to use the active flag we introduced in the status. What do you think?

**Comment by jolieno** [comment]
ok, i've changed the settings to 1600 for now. Thanks for looking into it.

**Comment by Bone008** [comment]
@inbaz Yes, using the active flag would be the nicer way to go. I changed it, see dcf994c.
 Putting the checkLimits call in the ProductController was only a temporary hack that worked well enough. Ideally it should be called whenever something about the item count is changed (checkout complete, admin cancels an order, admin uncancels an order, etc.).

But it is quite easy to miss a situation there, so I think updating it in the Frontend when the items are viewed is enough.

**Comment by jolieno** [comment]
I've changed the settings to 1600, the live version keeps saying (or says again) the tickets are sold out. 

When can I expect the new version to go live?

**Comment by Bone008** [comment]
@jolieno Increasing the counter currently does not automatically make the variant available again. Please re-enable the Friday product variant of the Gala tickets manually.

**Comment by jolieno** [comment]
ah, thanks for the tip! Now they are available again.

**Comment by inbaz** [comment]
I had a seond look at the code and it looks like the active flag is already used for the ticket counter. Please test with:
- check in statistics how many gala tickets has been sold for one product variant value
- set the counter to this amount +1.
- start a new shopping cart, put in a gala show ticket for the previous mentioned product variant value
- check in another browser if you're able to choose the same gala show ticket in another cart again.
- once one of these shopping carts has been ordered the other one may not be able to put in another gala show ticket anymore.

**Comment by jolieno** [comment]
I just tested this in 0.4.55; 

- After putting in a gala show ticket and before finishing the order, you can still choose the same ticket in another browser. 
- after finishing this order, galashow ticket for this time in the other browers is 'sold out' immediately.

So i guess it works as wanted :)
