### ISSUE TITLE
Deleting an item or person out of the shopping cart does not work

### ISSUE THREAD

**Issue by PiQuer** [inbaz/ers#785]
Maybe related to #782. This bug, however, is only reproducible on the freiburg test server.

To reproduce: Choose a product, add a person, add the product to the shopping cart. Go to the shopping cart and click the trash bin icon next to the product or next to the person. On the confirmation page, click "Ja".

Instead of deleting the person (together with the items) or the item, one returns to the unchanged shopping cart.

**Comment by inbaz** [comment]
Hi, just had a quick look where this problem comes from and it's the translation. The code actually checks against the "Yes" on the delete button. Since there is "Ja" now it's not working. I wanted to change the form used here anyway. That's a good reason to correct that.

**Comment by PiQuer** [comment]
Cherry-picked da868af to freiburg-live, works great. Thanks!
