### ISSUE TITLE
Order Search hard fails (Error 500) when query has trailing space

### ISSUE THREAD

**Issue by jackcaveman** [inbaz/ers#798]
The trailing space seems to be the problem. Other characters (?, &, +) seem towork fine. Compare:

https://prereg.eja.net/admin/order/search?q=Boutang+Pierre+
Returns error 500 page
https://prereg.eja.net/admin/order/search?q=Boutang+Pierre
Returns results just fine

Version: 0.4.53

**Comment by inbaz** [comment]
fixed in next version, 0.4.63
