### ISSUE TITLE
"Buy now" button at the end of checkout is broken

### ISSUE THREAD

**Issue by jackcaveman** [inbaz/ers#8]
In the last stage of checkout, when I accept the terms and conditions and press "buy now" I get an php exception. Unexcepted value 

Error message:
The type hint of parameter "inputFilter" in method "setInputFilter" in class "ersEntity\Entity\User" is invalid.

**Comment by inbaz** [comment]
Fixed that problem in new verion.

I added error messages of needed fields which are displayed instead of 
the "accept terms" checkbox. The buy now button is disabled when there 
are any errors.

Am 22.02.2015 um 19:08 schrieb jackcaveman:
