### ISSUE TITLE
Cannot add user through admin panel

### ISSUE THREAD

**Issue by PiQuer** [inbaz/ers#800]
Version: 0.4.54
To reproduce: Admin Panel -> User -> User, then click on "+", add Details (Firstname, Surname, Date of Birth, Email, Country), click on "Add".
Result: Blank page

**Comment by inbaz** [comment]
At the moment this behaviour is intended until the roles are clearly developed. Not everybody with access to the admin panel should be able to do that. At the moment as a workaround register the person, then set the roles in the database and lead them to the password request page. Once a password is set they get activated and will not be deleted by any cleanup script.

**Comment by PiQuer** [comment]
Got it. Thanks.
