### ISSUE TITLE
Cannot cancel order in admin panel

### ISSUE THREAD

**Issue by PiQuer** [inbaz/ers#805]
On the Freiburg system (I don't have access to the EJC2016 testing server at the moment), I cannot cancel an order through the admin panel.

To reproduce: login, Admin Panel, Order->Overview, choose any order, go to "Detail", Status -> Cancelled, confirm Yes.

Error:

    File:

    /home/freiburg/www/freiburg.ers.inbaz.org/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php:204

    Message:

    Expected value of type "ErsBase\Entity\Status" for association field "ErsBase\Entity\Item#$status", got "string" instead.

**Comment by inbaz** [comment]
This is fixed in the develop branch. Can you just get the code out of there and put it in the freiburg branch?

**Comment by PiQuer** [comment]
Fixed by 6c565cac9b69fb3ca32d4b13b81530c018147dfd.
