### ISSUE TITLE
problem when bank statement is deleted and a new one is uploaded again

### ISSUE THREAD

**Issue by Tobias-Horstmann** [inbaz/ers#807]
v0.4.55
I have created a new bank account, uploaded a csv file (bank statement), defined the format and clicked on manual matching. There I found the two entries of the csv file. Afterwards I have deleted the bank statement and uploaded the same statement again and now after clicking on manual matching the system says "No bank statements could be found." (even after redefining the format).

**Comment by inbaz** [comment]
It could be that by deleting a bank statement they are not deleted but deactivated, maybe we need to check if that's the case.
