### ISSUE TITLE
After manual matching a blank page is shown withoud doing the matching

### ISSUE THREAD

**Issue by Tobias-Horstmann** [inbaz/ers#809]
v0.4.55:
After choosing a registered participant and an entry of a bank statement to manually match both, you get directed to a "overview" page to specify the reason and match it as "paid" or "unpaid". After specifying a reason and clicking on either "paid" or "unpaid" I see a blank page and nothing happens. When clicking to previous page in the browser or refresh the url you get to the "overview" page again but the matching hasn't been working.

That has been the example url:
 https://ejc2016.ers.inbaz.org/admin/matching/accept?orders[0]=6367&statements[0]=23

**Comment by inbaz** [comment]
fixed blank page error in 0.4.56
