### ISSUE TITLE
details of paid orders are shown incorrectly

### ISSUE THREAD

**Issue by Tobias-Horstmann** [inbaz/ers#811]
v0.4.56:
When searching for orders and clicking on details of "paid (ordered)" orders, the info page is not displayed correctly (style sheet problem?). The page for "ordered" marked orders is shown correctly.

example url: https://ejc2016.ers.inbaz.org/admin/order/detail/6367

**Comment by inbaz** [comment]
That's a problem with the way matches are shown on the order detail page. I already fixed it in dev.

**Comment by inbaz** [comment]
Should be in master as well, now. Please retest.
