### ISSUE TITLE
Failure when loading order detail page where order has already a match

### ISSUE THREAD

**Issue by jolieno** [inbaz/ers#813]
The layout of the page after opening a order through the 'search order' button doens't look like the rest of the layout on the ERS system. It looks like this;
![ers](https://cloud.githubusercontent.com/assets/16348281/15474787/baee2b9e-2106-11e6-98f7-4107ccbe1549.PNG)

Can we change it so the lay-out is the same?

**Comment by inbaz** [comment]
This is not a layout issue. Everytime the layout is not set correctly there happened an error before and the code was not calculated completely. Fix in dev, at the moment there are problems with github so I cannot put it onto preprod. I will do as soon as github works again.

**Comment by jolieno** [comment]
Ok, thanks for the explanation!

**Comment by inbaz** [comment]
This should work now, please retest.

**Comment by jolieno** [comment]
It works! Thanks, you can close this issue.
