### ISSUE TITLE
Sending out E-tickets doens't work jet?

### ISSUE THREAD

**Issue by jolieno** [inbaz/ers#814]
After matching an order, i can download the order but can not send it to the person by mail. I've been trying to do this by on the following page; order/detail/send e tickets.

As tobias wrote, the E-tickets are still in the layout from EJC 2015. But also ? marks shows up on the right, instead of the order products. In this case a weekticket for an child. Because i'm not sure you are aware of this i made this issue

![e ticket](https://cloud.githubusercontent.com/assets/16348281/15475321/c3f23516-2109-11e6-807a-e8a8e0fdb077.PNG)

**Comment by inbaz** [comment]
I'm aware of this. Sending E-Tickets is not ready, yet.
