### ISSUE TITLE
Workflow for Freiburg on-site registration

### ISSUE THREAD

**Issue by PiQuer** [inbaz/ers#816]
At the Freiburg on-site registration, we need a way to check in participants, that is to indicate in the system that someone has received his badge. As I understand it, this is done via the OnSite panel.

However, even when the status is "paid" I cannot register a person. Probably this is only possible after the E-Ticket has been sent out? If this is the case, that's fine, but E-Tickets cannot be sent at the moment (see #814). Either the sending of E-Tickets has to be fixed, or we need a way to register a participant without having sent an E-Ticket.

The decision of the organization board was not to send out E-Tickets to the participants. Should we need the E-Tickets for the registration workflow, I can work around this by sending the E-Tickets on my virtual machine with a mail catcher installed, so that no real emails will be sent.

**Comment by inbaz** [comment]
I don't know it exactly but I think the etickets don't need to be sent out to be able to do the onsite registration. This is a bug from the database changes that has been made and the recognition of the status with which a item can be handed out need to be fixed. I'll try to look into that the next days.

**Comment by PiQuer** [comment]
OnSite registration works in current develop branch and freiburg-localize.

Thanks!
