### ISSUE TITLE
matched orders at the manual matching step keep on the list of unpaid orders

### ISSUE THREAD

**Issue by Tobias-Horstmann** [inbaz/ers#817]
v. 0.4.56

If you match orders manually and mark them as "paid", the orders are still displayed on the left side in the manual matching display after the matching. Consequently, the amount of unpaid orders stays the same.

**Comment by inbaz** [comment]
fixed in 0.4.57. The problem was that status were set on items but not on the order itself. But the status that is checked to list the order in this list is the one of the order. Please retest.

**Comment by inbaz** [comment]
Can somebody please catch this issue and test if this is working now?

**Comment by jolieno** [comment]
This works as wanted.
