### ISSUE TITLE
Listing of 0€-Week-Tickets shows error (?) & lacks css

### ISSUE THREAD

**Issue by philip-n** [inbaz/ers#825]
### Current status / problem:

Selecting Search > 0€-Week-Tickets from the admin panel leads to a page that lacks any css / menu / ... with the following content:

**Order Overview which do include 0€ Week Tickets
Wrong date of birth?
Code    Date    Buyer   Payment type    Price   Status**

In the HTML markup of the page, there's an incomplete table.
### Expected behaviour:
- Display a list of 0€-week-tickets (and correctly close the table in html)
- Load correct CSS and menu
- Maybe show a message if there are no 0€-week-tickets available

**Comment by inbaz** [comment]
This page was intended for finding week tickets with participants that have provided a wrong date of birth. Last year we had many headaches and discussions about this topic, but the solution was quite simple. We sent out the E-Tickets with the information that they can only attend the EJC when the date of birth on the E-Ticket matches the date of birth on their ID card. With this message we had nearly all participant details corrected within just some weeks.

I will fix the page for a last check.
