### ISSUE TITLE
E-Ticket: Remove additional checkboxes without content

### ISSUE THREAD

**Issue by philip-n** [inbaz/ers#829]
If somebody did not order a shirt / hoodie, there is an additional empty checkbox displayed in the line after shirt / hoodie:
![empty-checkbox](https://cloud.githubusercontent.com/assets/3903619/16176821/f740f018-3619-11e6-9044-8afd04d2d599.gif)

Can we remove them?

Note: This behaviour might already have been fixed / modified, as checkboxes were put in front before items (as per #827).

**Comment by inbaz** [comment]
That was a separate checkbox. I've removed it. 0.4.63 is online on preprod, now. Please check if it works like expected.

**Comment by philip-n** [comment]
Works, closed, thx!
