### ISSUE TITLE
Load testing

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#83]
Even if it's just a labratory test. Lets try to find a valuable number of concurrent users which are using this system.
i.e. 100 Requests with 10 concurrent users:
or 1000 Requests with 50 concurrent users:
Let's even check some session and database actions and write some examples for these tests.

Not sure if we really should test it...

**Comment by inbaz** [comment]
We can configure the webserver to only serve the page to an amount of users. Other users see a page where they get informed that the server is under high load at the moment and they should come back later. This ensures that the system is functioning for the users who are already on the page.

**Comment by smadamit** [comment]
Job for EJA-Server -> Staffan

**Comment by smadamit** [comment]
@inbaz We start with the current Apache config. If we will get problems we can have a look to this issue. OK? I move this issue to SecondLife.

**Comment by smadamit** [comment]
@inabz I guess we can close this issue right?

**Comment by staffanu** [comment]
Sure -- I have to admit I haven't given it much attention, but it also
doesn't seem like a problem from what I understand...

Staffan

**Comment by inbaz** [comment]
This is not a problem since not that much people just surfed through the product and did not buy them. There is not that high server load which needs to be tested. Therefore close.
