### ISSUE TITLE
E-Ticket: Layout of supervision options (U16 / U18)

### ISSUE THREAD

**Issue by philip-n** [inbaz/ers#832]
I think that the supervision options are correct and clear, but I'm biased as I already know them in and out.

Suggestions for even better visiblity:
- Put small border around each option
- Align the "OR" in the center (instead of left)

See below for example.
### Current

![08-supervision-unboxed](https://cloud.githubusercontent.com/assets/3903619/16177140/22631c20-3625-11e6-9b12-df214f67c9cd.gif)
### Proposed

![09-supervision-boxed](https://cloud.githubusercontent.com/assets/3903619/16177141/27828f88-3625-11e6-874d-7d2eee902c8c.gif)

**Comment by jolieno** [comment]
Let's not make this changes for this year, but for next year. These lay-out improvements are not necessary for now, because they will take up more time before we can get the E-tickets out.
