### ISSUE TITLE
E-Ticket: Scaling of text

### ISSUE THREAD

**Issue by philip-n** [inbaz/ers#833]
There is the problem that quite a lot of text needs to go on one page. Extending to two pages is not viable, as then the disclaimer and the signature might become separated.

With the given constraints: Can the font size be scaled differently based on the age-type of ticket?
- Adults: Increase the font size to some standard size for printouts (like 12 or 14pt in word)
- U18: Increase the font size for the first two paragraphs (Brief instruction and Disclaimer) just so that the text still fits onto one page
- U16: If possible, increase the font size of first paragraph slightly (as this is the most important one)
### Mockups for adult and U18

_(intro text for U18 is wrong in mockup, just ignore)_
![text-adult](https://cloud.githubusercontent.com/assets/3903619/16177300/95a6350c-3628-11e6-90ce-20e95ec02df5.gif)
![text-u18](https://cloud.githubusercontent.com/assets/3903619/16177301/97ba806e-3628-11e6-999e-4b57c6754872.gif)

**Comment by jolieno** [comment]
Can we make the text of disclaimer smaller? Like last year? Then it al fitted on one page. That would be our preference, if possible. Thanks!

**Comment by inbaz** [comment]
The idea in general is to remove the whole disclaimer of the e-ticket. It's possible to have only the checkbox on the checkout to mark the disclaimer as read and accepted. What I'd like to add is a possibility in the AdminPanel to prepare orders for participants to be able to help them setup their order correctly. Then they get a link with which they can finish the order and where they need to mark the disclaimer as read and accepted. An additional hint on the e-ticket would be great to have the disclaimer on the e-ticket as well.
