### ISSUE TITLE
E-Ticket: Multiple day tickets for same day are not visualized differently from single one

### ISSUE THREAD

**Issue by philip-n** [inbaz/ers#835]
With the current design, the checkbox for each day (for which a ticket can be purchased) is either checked or unchecked. Therefore, when multiple day tickets are ordered for the same day, the e-ticket looks the same as if only one day ticket has been ordered.

Proposal: Print number or circle with number (like http://www.fontscape.com/pictures/gallo/NumbersTwoCircleNegative.gif) if more than one day tickets have been ordered for a single day.

**Comment by inbaz** [comment]
It should not be possible to buy more than one personal ticket per person. However at the moment this check is not implemented. So if they managed it do buy multiple day tickets for the same day for them, we need to get a list of those orders and sort them out. I think there will be even some participants who bought multiple week tickets for themself.

The e-ticket gets valid in conjunction with their id card. So they cannot buy day or week tickets for other persons within one e-ticket (package).
