### ISSUE TITLE
Change birthday dates after adding an order to the shopping card but before buying

### ISSUE THREAD

**Issue by TobiasHorstmann** [inbaz/ers#846]
V 0.4.64

If you change birthday dates after adding an order to the shopping card but before buying, the ticket price isn't updated. 

For example it is possible to get a free ticket with a valid e-ticket by adding a ticket for a person with birthday in 2016  to the shopping card, then change the the birthday to the actual birthday (e.g. 1983) by editing the personal details and afterwards continue and finalize the shopping procedure.

**Comment by inbaz** [comment]
Before EJC, these tickets need to be recalculated to have the correct price. The owner need to be informed that their tickets are not valid, yet.
