### ISSUE TITLE
OnsiteReg

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#88]
At the EJC on the first two days there will arrive about 80% of the participants which means for a 3000 people EJC there will be 2400 people in front of the door. They all want to have their badge as fast as possible to be able to get the best camping place for their tent. :) So mainly ERS needs to be a system that provides functions that get good camping places to the jugglers fast.

Quick search for:
- code
- firstname
- surname
- email address
- birthday

overview of all articles that were ordered
hand out single articles

**Comment by inbaz** [comment]
What is the task in this issue which is not handled by other issues, yet?

**Comment by Bone008** [comment]
I figured this is the base issue for the OnsiteReg module in general. I will base the feature branch for OnsiteReg off of this ticket, for example.

**Comment by smadamit** [comment]
Maybe we need an access role for the infopoint:
- is allowed to search for orders by name of the buyer or the order id -> display all order details
- is not allowed to hand out tickets / change status to shipped

-> we need this for looking up orders for handing out invoices...

But maybe the infopoint should have the same access rights as the registration.

**Comment by inbaz** [comment]
solved
