### ISSUE TITLE
Galaticket im Ticket schlecht beschrieben

### ISSUE THREAD

**Issue by cpingel** [inbaz/ers#884]
Wenn man für die Münchener Con das WE Ticket auswählt, dann muss man ja etwas später die Uhrzeit für die Galashow bestimmen. Dort steht dann aber am Ticket "Showticket (für externe Gäste)"
Ist etwas verwirrend, da das Ticket für mich ist und nicht für einen zusätzlichen EXTERNEN Gast.

**Comment by inbaz** [comment]
Hab ich umbenannt, sollte jetzt passen.
