### ISSUE TITLE
Angabe IBAN mit Leerzeichen

### ISSUE THREAD

**Issue by cpingel** [inbaz/ers#886]
Unter "meine Bestellung" wird die IBAN mit Leerzeichen ( 	DE87 7025 0150 0027 0180 27) angegeben. Past an Copy in eine Überweisung ist so nicht möglich, da man anschließend die Leerzeichen löschen muss.
Niklas hatte mir mal erklärt, dass es einen Zeichensatz/Programmierung gibt, wo man die Leerzeichen für die bessere Übersichtlichkeit nur künstlich erzeugt. Also man sieht die Leerzeichen, beim kopieren sind sie aber nicht vorhanden.
Dto auch in der Mail, IBAN mit Leerzeichen.

**Comment by inbaz** [comment]
Hi @cpingel, kannst du den Niklas bitte mal fragen? Das wäre ja eine optimale Lösung dafür. Ich kenne das noch nicht.

**Comment by cpingel** [comment]
Andi, mache ich

Gruß Carsten
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 06.10.2016, 09:18, Andi Nitsche <notifications@github.com> schrieb:

  
    
      Hi @cpingel, kannst du den Niklas bitte mal fragen? Das wäre ja eine optimale Lösung dafür. Ich kenne das noch nicht.

**Comment by inbaz** [comment]
Ich hab's gefunden und eingebaut, die Iban wird jetzt zumindest auf der Übersichtsseite schön dargestellt und beim Kopieren werden keine Leerzeichen mit kopiert.
