### ISSUE TITLE
Order adjustment does update the total_sum

### ISSUE THREAD

**Issue by jackcaveman** [inbaz/ers#887]
I was working with the Orders Export  from Andi.
There are a few cases were this was a difference between Value from the Bank statement and the Total_sum in the Table. Potentially adjusted orders do not update datebase correctly. Please check.

CV6NF508, Has two associated statements: 
63.5 + 1149 = 1212.50
However, the Total_sum column in the Export 1049. But online it's 1.212,50

MNY72300
Order was adjusted from 300 to 255
255 was paid
total_sum was 300 in table, but 255 online

FR7KV824
Ticket swap from 150 to 127,50 (127.50 paid)
Order_sum was still 150 in table, but online 127.50

**Comment by jackcaveman** [comment]
Order_sum is also not adjusted

**Comment by inbaz** [comment]
I changed that in the newest version. order_sum and total_sum needs to be checked in a dev system after changing the price of a ticket.
