### ISSUE TITLE
Cached birthday not used upon hitting 'Enter'

### ISSUE THREAD

**Issue by Albapasser** [inbaz/ers#894]
I've used the prereg system before. Hence my birthday is cached (in a cookie, I suppose).
When the system asks me to enter my birthday, I press the first key and the drop-down list appears to suggest the value which I entered the last time.
I use the 'cursor down' key to select the suggestion and press 'Enter'. 
Expected result:
The selected value from the auto-suggestion gets imported into the 'Birthday' control
Observed result:
The current date (13.10.2016) gets imported into the "Birthday" control.
Only when I hit the "Enter" key a second time, the current date gets replaced with the right value.

**Comment by inbaz** [comment]
Hi, thanks for you issue. It looks like the dropdown you're using is your browsers form cache. I think it's only possible to turn it off. The calendar that's loaded is part of the jquery-ui and is loaded when you enter the date form field. It looks like the calendar caches the enter key press.
