### ISSUE TITLE
admin/product-price/add bug agegroup not stored

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#90]
If I set a agegroup it is not stored in database.
For edit form it works.

**Comment by smadamit** [comment]
And after creating a price you should route to admin/product-price/view not admin/product/index

**Comment by inbaz** [comment]
agegroup gets stored and routing is fixed in complete admin panel. So for further tests, please keep in mind to look if routing works and is possible even for Cancel links.

**Comment by smadamit** [comment]
works perfect v0.2.7
