### ISSUE TITLE
admin/order/detail more info

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#91]
can you please add:
- matching-code in admin/order/index and admin/order/detail
- order datetime in admin/order/detail

Very useful for testing.

**Comment by inbaz** [comment]
fixed in 0.2.8

**Comment by smadamit** [comment]
OK fine for now. Please add more infos to the detail view later.
- datetime of order
- matching code
- payment type costs
- etc.

all infos associated to an order...

**Comment by inbaz** [comment]
Added datetime of order the other point were already at the detail page. For further changes I need a mockup.

**Comment by smadamit** [comment]
it's fine for the moment
