### ISSUE TITLE
Edit Products in Admin Panel

### ISSUE THREAD

**Issue by Tobias-Horstmann** [inbaz/ers#912]
v.0.5.33
When editing products in overview -> configs -> edit following error occur:

An error occurred
Sorry!

The page you are looking for doesn't exist. If you think this is an error, please let us know at info@ejc2017.org.

If you encounter any error with this system, please send us a full copy of this page.
You might be looking for:

    the products page
    your current shopping cart
    the login to access your previous purchases

An error occurred during execution; please try again later.
Additional information:
Doctrine\DBAL\Exception\DriverException

File:

    /home/andi/www/lublin.ers2.inbaz.org/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:120

Message:

    An exception occurred while executing 'UPDATE product SET `tax_id` = ?, `position` = ?, `active` = ?, `visible` = ?, `deleted` = ?, `personalized` = ?, `updated` = ? WHERE `id` = ?' with params ["1", "4", "1", "1", "", "0", "2017-02-16 22:33:53", 5]:

    SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'deleted' at row 1

Stack trace:

    #0 /home/andi/www/lublin.ers2.inbaz.org/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(154): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
    #1 /home/andi/www/lublin.ers2.inbaz.org/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\DBALException::wrapException(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'An exception oc...')
    #2 /home/andi/www/lublin.ers2.inbaz.org/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1001): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'UPDATE product ...', Array)
    #3 /home/andi/www/lublin.ers2.inbaz.org/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(480): Doctrine\DBAL\Connection->executeUpdate('UPDATE product ...', Array, Array)
    #4 /home/andi/www/lublin.ers2.inbaz.org/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(367): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->updateTable(Object(ErsBase\Entity\Product), 'product', Array, NULL)
    #5 /home/andi/www/lublin.ers2.inbaz.org/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1055): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->update(Object(ErsBase\Entity\Product))
    #6 /home/andi/www/lublin.ers2.inbaz.org/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(377): Doctrine\ORM\UnitOfWork->executeUpdates(Object(Doctrine\ORM\Mapping\ClassMetadata))
    #7 /home/andi/www/lublin.ers2.inbaz.org/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(359): Doctrine\ORM\UnitOfWork->commit(NULL)
    #8 /home/andi/www/lublin.ers2.inbaz.org/module/Admin/src/Admin/Controller/ProductController.php(97): Doctrine\ORM\EntityManager->flush()
    #9 /home/andi/www/lublin.ers2.inbaz.org/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Admin\Controller\ProductController->editAction()
    #10 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
    #11 /home/andi/www/lublin.ers2.inbaz.org/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
    #12 /home/andi/www/lublin.ers2.inbaz.org/vendor/zendframework/zend-eventmanager/src/EventManager.php(214): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
    #13 /home/andi/www/lublin.ers2.inbaz.org/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
    #14 /home/andi/www/lublin.ers2.inbaz.org/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
    #15 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
    #16 /home/andi/www/lublin.ers2.inbaz.org/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
    #17 /home/andi/www/lublin.ers2.inbaz.org/vendor/zendframework/zend-eventmanager/src/EventManager.php(214): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
    #18 /home/andi/www/lublin.ers2.inbaz.org/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
    #19 /home/andi/www/lublin.ers2.inbaz.org/public/index.php(18): Zend\Mvc\Application->run()
    #20 {main}

Previous exceptions:

    Doctrine\DBAL\Driver\PDOException

    File:

        /home/andi/www/lublin.ers2.inbaz.org/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107

    Message:

        SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'deleted' at row 1

    Stack trace:

        #0 /home/andi/www/lublin.ers2.inbaz.org/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(992): Doctrine\DBAL\Driver\PDOStatement->execute()
        #1 /home/andi/www/lublin.ers2.inbaz.org/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(480): Doctrine\DBAL\Connection->executeUpdate('UPDATE product ...', Array, Array)
        #2 /home/andi/www/lublin.ers2.inbaz.org/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(367): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->updateTable(Object(ErsBase\Entity\Product), 'product', Array, NULL)
        #3 /home/andi/www/lublin.ers2.inbaz.org/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1055): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->update(Object(ErsBase\Entity\Product))
        #4 /home/andi/www/lublin.ers2.inbaz.org/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(377): Doctrine\ORM\UnitOfWork->executeUpdates(Object(Doctrine\ORM\Mapping\ClassMetadata))
        #5 /home/andi/www/lublin.ers2.inbaz.org/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(359): Doctrine\ORM\UnitOfWork->commit(NULL)
        #6 /home/andi/www/lublin.ers2.inbaz.org/module/Admin/src/Admin/Controller/ProductController.php(97): Doctrine\ORM\EntityManager->flush()
        #7 /home/andi/www/lublin.ers2.inbaz.org/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Admin\Controller\ProductController->editAction()
        #8 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
        #9 /home/andi/www/lublin.ers2.inbaz.org/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
        #10 /home/andi/www/lublin.ers2.inbaz.org/vendor/zendframework/zend-eventmanager/src/EventManager.php(214): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
        #11 /home/andi/www/lublin.ers2.inbaz.org/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
        #12 /home/andi/www/lublin.ers2.inbaz.org/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
        #13 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
        #14 /home/andi/www/lublin.ers2.inbaz.org/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
        #15 /home/andi/www/lublin.ers2.inbaz.org/vendor/zendframework/zend-eventmanager/src/EventManager.php(214): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
        #16 /home/andi/www/lublin.ers2.inbaz.org/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
        #17 /home/andi/www/lublin.ers2.inbaz.org/public/index.php(18): Zend\Mvc\Application->run()
        #18 {main}

    PDOException

    File:

        /home/andi/www/lublin.ers2.inbaz.org/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105

    Message:

        SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'deleted' at row 1

    Stack trace:

        #0 /home/andi/www/lublin.ers2.inbaz.org/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(105): PDOStatement->execute(NULL)
        #1 /home/andi/www/lublin.ers2.inbaz.org/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(992): Doctrine\DBAL\Driver\PDOStatement->execute()
        #2 /home/andi/www/lublin.ers2.inbaz.org/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(480): Doctrine\DBAL\Connection->executeUpdate('UPDATE product ...', Array, Array)
        #3 /home/andi/www/lublin.ers2.inbaz.org/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(367): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->updateTable(Object(ErsBase\Entity\Product), 'product', Array, NULL)
        #4 /home/andi/www/lublin.ers2.inbaz.org/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1055): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->update(Object(ErsBase\Entity\Product))
        #5 /home/andi/www/lublin.ers2.inbaz.org/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(377): Doctrine\ORM\UnitOfWork->executeUpdates(Object(Doctrine\ORM\Mapping\ClassMetadata))
        #6 /home/andi/www/lublin.ers2.inbaz.org/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(359): Doctrine\ORM\UnitOfWork->commit(NULL)
        #7 /home/andi/www/lublin.ers2.inbaz.org/module/Admin/src/Admin/Controller/ProductController.php(97): Doctrine\ORM\EntityManager->flush()
        #8 /home/andi/www/lublin.ers2.inbaz.org/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Admin\Controller\ProductController->editAction()
        #9 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
        #10 /home/andi/www/lublin.ers2.inbaz.org/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
        #11 /home/andi/www/lublin.ers2.inbaz.org/vendor/zendframework/zend-eventmanager/src/EventManager.php(214): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
        #12 /home/andi/www/lublin.ers2.inbaz.org/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
        #13 /home/andi/www/lublin.ers2.inbaz.org/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
        #14 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
        #15 /home/andi/www/lublin.ers2.inbaz.org/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
        #16 /home/andi/www/lublin.ers2.inbaz.org/vendor/zendframework/zend-eventmanager/src/EventManager.php(214): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
        #17 /home/andi/www/lublin.ers2.inbaz.org/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
        #18 /home/andi/www/lublin.ers2.inbaz.org/public/index.php(18): Zend\Mvc\Application->run()
        #19 {main}

**Comment by inbaz** [comment]
I gave the deleted field a default value, that solves this issue.
