### ISSUE TITLE
product/delete: bug

### ISSUE THREAD

**Issue by smadamit** [inbaz/ers#96]
not able to delete week ticket child in the shopping card.

An error occurred
An error occurred during execution; please try again later.
Additional information:
Zend\View\Exception\InvalidArgumentException
File:
/var/www/ers/vendor/zendframework/zendframework/library/Zend/View/Helper/Url.php:76

**Comment by inbaz** [comment]
fixed in 0.2.9
When you want to give further information, please copy the message of the message field. The file where the error occurs is most likely one of the framework or an external module which can be recognized when theres is "vendor" in the path to the file.
