### ISSUE TITLE
Order: Checkout Register and Payment tabs do not load the saved data

### ISSUE THREAD

**Issue by jackcaveman** [inbaz/ers#98]
Go to the checkout procedure. Select a purchaser, select a paymentType. 
Click on Register, the purchaser is not selected (bug)
Click on PaymentTpye, the paymentType is not selected (bug)
Click on Checkout (rightmost), the purchaser and paymentType are displayed correctly

**Comment by inbaz** [comment]
fixed in 0.2.11

**Comment by smadamit** [comment]
v0.2.11

register retested -> OK
paymentType -> not able to retest -> bug #101

**Comment by inbaz** [comment]
Can you please retest and check if this is already solved?

**Comment by smadamit** [comment]
tested in 0.2.36 -> OK
