### ISSUE TITLE
Credit Card form: payment amount unclear

### ISSUE THREAD

**Issue by jackcaveman** [inbaz/ers#99]
All the products have whole number prices. On the checkout page the Payment Type charge is not really clear. Maybe give a short summary of the total product amount and payment charge. (or put a hoover text, explaining this)

**Comment by inbaz** [comment]
![2015-03-05 22_20_10-my shopping cart - ejc registration system](https://cloud.githubusercontent.com/assets/8452304/6514864/ed03e842-c385-11e4-8357-6da2d7ce79ac.png)

This is what is already on the checkout page. Make an example how this should look like, an image is enough.

**Comment by jackcaveman** [comment]
![image](https://cloud.githubusercontent.com/assets/11071240/6515027/3955ee42-c387-11e4-8975-37dfb36011ef.png)

**Comment by inbaz** [comment]
check the change in 0.2.11

**Comment by jackcaveman** [comment]
order/payment is broken in v0.2.11 can't test it.

**Comment by inbaz** [comment]
fixed it in 0.2.12

**Comment by smadamit** [comment]
tested in 0.2.12
